// AUTO-GENERATED by scripts/generate-matrix-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate the relevant cell instead.
// Servizio: E-Commerce
// Categorie: beauty-wellness, sanita-salute, studi-professionali, casa-edilizia, auto-mobilita, food-hospitality, retail-negozi, creativita-eventi

import type { ServiceCategoryContent } from '../seo-service-content';

export const E_COMMERCE_CONTENT: Record<string, ServiceCategoryContent> = {
  'beauty-wellness': {
  "description": "Nel beauty e wellness molti incassi finiscono quando il cliente esce dal salone: prodotti professionali venduti solo al banco, gift card gestite a voce, ordini sparsi tra Instagram e WhatsApp. Un e-commerce mette catalogo, pagamenti, spedizioni e recupero carrelli nello stesso posto.",
  "microStory": "Un centro estetico a Frosinone vendeva creme e voucher solo al banco. Online aveva una pagina “prodotti” senza acquisto, quindi ogni richiesta finiva in chat e veniva gestita a mano. L’e-commerce è stato costruito con categorie corte, varianti semplici, ritiro in sede e email chiare dopo l’ordine. Non abbiamo trasformato il salone in marketplace: abbiamo tolto 6 messaggi ripetuti per ogni vendita. Nel primo mese sono arrivati 38 ordini tra voucher e prodotti, quasi tutti fuori orario di apertura.",
  "caseStudyRef": undefined,
  "solutionTitle": "Il tuo salone non deve vendere solo quando qualcuno entra",
  "problems": [
    {
      "icon": "ph-shopping-bag",
      "title": "Banco troppo corto",
      "desc": "Shampoo, trattamenti, creme e accessori restano legati al passaggio fisico in salone. Chi ti segue su Instagram, ma non passa quella settimana, compra altrove. Il problema non è il prodotto: è il canale mancante."
    },
    {
      "icon": "ph-receipt",
      "title": "Gift card improvvisate",
      "desc": "A Natale, San Valentino o prima di una festa, i buoni regalo digitali dovrebbero essere pronti in due click. Se li gestisci con messaggi, bonifici e PDF manuali, perdi acquisti d'impulso. Fine della storia."
    },
    {
      "icon": "ph-chart-line-down",
      "title": "Incasso solo fisico",
      "desc": "Se il fatturato dipende solo da appuntamenti e passaggi in sede, ogni buco in agenda pesa. L'e-commerce separa una parte delle vendite dalla poltrona occupata, dalla cabina piena o dalla lezione prenotata."
    }
  ],
  "features": [
    {
      "title": "Catalogo beauty ordinato",
      "description": "Prodotti, kit, trattamenti domiciliari e gift card con categorie chiare, varianti, foto, schede tecniche e disponibilità. Niente scaffale digitale confuso copiato da un template qualunque."
    },
    {
      "title": "Pagamenti e spedizioni",
      "description": "Stripe, PayPal, bonifico, ritiro in sede e spedizioni configurate in modo coerente con il tuo modo di lavorare. Il cliente compra senza aspettare risposte su WhatsApp."
    },
    {
      "title": "Magazzino sotto controllo",
      "description": "Giacenze, varianti, formati, colori e prodotti esauriti gestiti senza plug-in messi a caso. Così non vendi online una crema che in salone è già finita."
    },
    {
      "title": "Email che chiudono ordini",
      "description": "Conferme d'acquisto, ricevute, recupero carrello e messaggi post-vendita scritti per clienti beauty, non per un negozio anonimo. Meno rincorse manuali, più ordine."
    },
    {
      "title": "Dati per Google Shopping",
      "description": "Schema Product e Offer, dati prodotto puliti, titoli comprensibili e pagine pronte per essere lette meglio da Google. Non basta caricare articoli: vanno presentati bene."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere sia prodotti fisici sia gift card per trattamenti?",
      "answer": "Sì. Prodotti, pacchetti, buoni regalo e kit possono convivere nello stesso shop, con regole diverse per consegna, ritiro in salone e invio digitale. La parte importante è separare bene ciò che viene spedito da ciò che viene riscattato su appuntamento."
    },
    {
      "question": "Se ho pochi prodotti, ha senso aprire uno shop online?",
      "answer": "Dipende da cosa vendi e da quanto spesso i clienti te li chiedono dopo il trattamento. Anche un catalogo piccolo può avere senso se include prodotti professionali, routine consigliate e gift card stagionali. Meglio poco catalogo ordinato che cento articoli caricati male."
    },
    {
      "question": "Posso collegare lo shop a Instagram?",
      "answer": "Sì, lo shop può diventare la destinazione dei link in bio, storie, campagne e messaggi. Instagram accende l'interesse, ma il pagamento deve avvenire in un posto chiaro, con scheda prodotto, disponibilità e conferma ordine. Altrimenti resta tutto fragile."
    },
    {
      "question": "Come gestisco il ritiro in salone?",
      "answer": "Il ritiro in salone può essere una modalità di consegna separata dalla spedizione. Il cliente compra online, riceve conferma e passa quando l'ordine è pronto. Per saloni, estetiste e palestre è spesso il modo più semplice per iniziare senza complicare la logistica."
    },
    {
      "question": "WooCommerce basta o serve una piattaforma custom?",
      "answer": "WooCommerce va bene quando catalogo, pagamenti e flussi sono standard. Una piattaforma custom ha senso se hai regole particolari: abbonamenti, credito cliente, listini riservati, integrazioni con gestionale o gift card molto specifiche. Prima si mappa il processo, poi si sceglie lo strumento. Punto."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gift card estetista"
},
  'sanita-salute': {
  "description": "Vendere online prodotti parafarmaceutici, integratori o kit post-trattamento in ambito sanitario non è un negozio qualunque. Serve catalogo chiaro, consenso informato dove serve, checkout sobrio, pagamenti tracciabili, spedizioni gestite e contenuti compatibili con regole deontologiche. Senza catene di fornitori che trasformano tutto in caos.",
  "microStory": "Uno studio nutrizionale voleva vendere percorsi introduttivi e documenti di preparazione senza far passare tutto da email. Il vecchio flusso era fragile: richiesta, risposta manuale, bonifico, invio file, appuntamento. L’e-commerce ha separato consulenza preliminare, materiali digitali e richiesta guidata, con consenso chiaro e conferme automatiche. Le segreteria ha tagliato circa 4 passaggi per ogni ingresso. In 6 settimane gli acquisti e le richieste pagate sono diventati 21, senza forzare promesse sanitarie o linguaggio commerciale fuori tono.",
  "caseStudyRef": undefined,
  "solutionTitle": "E-commerce sanitario senza carrelli improvvisati",
  "problems": [
    {
      "icon": "ph-shopping-bag",
      "title": "Prodotti comprati altrove",
      "desc": "Il paziente esce dallo studio con un consiglio preciso, poi cerca online, finisce su marketplace anonimi e compra alternative sbagliate. Il problema non è vendere di più: è perdere controllo su ciò che viene acquistato dopo la visita."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Carrello poco conforme",
      "desc": "Un e-commerce sanitario non può parlare come un sito di sneaker. Claim aggressivi, schede prodotto copiate e promesse fuori tono possono creare problemi deontologici, soprattutto per integratori, dispositivi, kit post-trattamento o prodotti consigliati in studio."
    },
    {
      "icon": "ph-gear",
      "title": "Plug-in senza regia",
      "desc": "WooCommerce installato da uno, pagamenti da un altro, spedizioni incollate dopo, email mai testate. Risultato: ordini persi, magazzino confuso, checkout fragile e uno studio sanitario costretto a inseguire problemi tecnici invece dei pazienti."
    }
  ],
  "features": [
    {
      "title": "Catalogo sanitario ordinato",
      "description": "Prodotti, varianti, disponibilità e categorie costruite per chi deve acquistare con chiarezza, senza pagine urlate e senza schede generiche prese dal fornitore."
    },
    {
      "title": "Checkout sobrio e tracciabile",
      "description": "Pagamenti con Stripe, PayPal o bonifico, conferme chiare, riepiloghi leggibili e passaggi ridotti al necessario. Il carrello deve essere serio, non scenografico."
    },
    {
      "title": "Contenuti deontologicamente attenti",
      "description": "Testi prodotto, avvertenze, limiti e microcopy pensati per il contesto sanitario. Nessuna promessa miracolosa, nessun tono da televendita, nessuna frase buttata lì."
    },
    {
      "title": "Email e carrelli recuperati",
      "description": "Conferme ordine, spedizione, pagamento fallito e recupero carrello scritti in italiano pulito, con tono professionale e informazioni utili per il paziente."
    },
    {
      "title": "Dati pronti per Google",
      "description": "Schema Product e Offer, struttura tecnica pulita e feed gestibile per far leggere correttamente prodotti, disponibilità e informazioni commerciali ai motori di ricerca."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere online integratori che consiglio già in studio?",
      "answer": "Sì, ma va impostato con attenzione. Schede prodotto, claim, avvertenze e percorso di acquisto devono rispettare il contesto sanitario. Non basta aprire un catalogo e caricare foto: bisogna decidere cosa vendere, come presentarlo e quali informazioni rendere evidenti prima del pagamento."
    },
    {
      "question": "Meglio WooCommerce o una piattaforma custom per uno studio sanitario?",
      "answer": "Dipende da catalogo, magazzino, flussi interni e livello di controllo richiesto. WooCommerce può bastare per cataloghi snelli e gestione ordinaria. Una piattaforma custom ha senso quando servono regole specifiche, integrazioni particolari o processi non coperti bene da plug-in standard."
    },
    {
      "question": "Il paziente deve registrarsi per acquistare?",
      "answer": "Non sempre. In molti casi il checkout ospite riduce attrito e basta raccogliere i dati necessari per ordine, pagamento e spedizione. La registrazione ha senso se ci sono riordini frequenti, storico acquisti, prodotti riservati o logiche legate allo studio."
    },
    {
      "question": "Come evito che il carrello sembri poco professionale?",
      "answer": "Si parte togliendo rumore: niente banner aggressivi, urgenze finte, pop-up invadenti o testi da marketplace. Poi si lavora su catalogo, foto, descrizioni, avvertenze, checkout e messaggi email. In sanità la fiducia nasce anche da quello che non viene urlato."
    },
    {
      "question": "Posso vendere solo ai miei pazienti?",
      "answer": "Sì, si può impostare un catalogo pubblico, riservato o misto. Alcuni prodotti possono essere visibili a tutti, altri accessibili solo tramite link, area privata o codice. La scelta dipende dal tipo di prodotto, dal rapporto con il paziente e dalle regole dello studio."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "comprare integratori"
},
  'studi-professionali': {
  "description": "Per uno studio professionale, l’e-commerce non è un bazar: serve a vendere consulenze standard, pacchetti operativi, documenti scaricabili e pratiche ripetibili senza passare ogni volta da email, telefonate e allegati sparsi. Meno catena di fornitori, più controllo sul flusso commerciale.",
  "microStory": "Uno studio tecnico riceveva richieste ripetitive per verifiche preliminari, visure e consulenze brevi. Tutto passava da telefono, allegati WhatsApp e fatture preparate dopo. L’e-commerce è stato usato come ingresso ordinato: servizio scelto, dati minimi, documento caricato, conferma automatica e stato richiesta. Il professionista non vendeva “pacchetti finti”: vendeva un primo step controllato. Dopo 2 mesi, 29 richieste sono arrivate già classificate per tipologia, e il tempo medio di triage è sceso da 18 a 6 minuti.",
  "caseStudyRef": undefined,
  "solutionTitle": "E-commerce per studi che vendono competenza, non caos",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Consulenze vendute a mano",
      "desc": "La consulenza standard esiste già, ma viene gestita con messaggi, bonifici manuali, conferme separate e file inviati dopo. Ogni acquisto diventa una micro-pratica amministrativa. Il problema non è il servizio: è il percorso rotto."
    },
    {
      "icon": "ph-receipt",
      "title": "Documenti via email",
      "desc": "Modelli, fac-simile, checklist e guide finiscono in allegati inoltrati a mano. Versioni diverse, accessi non tracciati, clienti che chiedono di nuovo lo stesso file. È il classico commercio digitale fatto con strumenti da ufficio anni Novanta."
    },
    {
      "icon": "ph-prohibit",
      "title": "Nessun compra ora",
      "desc": "Per pratiche standard, consulenze rapide o pacchetti ricorrenti manca una pagina chiara dove il cliente scelga, paghi e riceva istruzioni. Così anche ciò che potrebbe essere ordinato in tre minuti passa da una trattativa inutile."
    }
  ],
  "features": [
    {
      "title": "Catalogo servizi professionali",
      "description": "Consulenze, pacchetti, documenti e pratiche standard organizzati come prodotti acquistabili, con varianti chiare per durata, ambito, formato o categoria del cliente."
    },
    {
      "title": "Pagamenti e conferme",
      "description": "Stripe, PayPal o bonifico gestiti dentro un flusso ordinato, con email transazionali, ricevute operative e istruzioni automatiche dopo l’acquisto."
    },
    {
      "title": "Download protetti",
      "description": "Documenti, modelli e materiali digitali consegnati dopo il pagamento, senza inoltri manuali, link improvvisati o cartelle condivise lasciate aperte."
    },
    {
      "title": "Recupero carrello serio",
      "description": "Email di recupero per chi abbandona una consulenza o un documento prima del pagamento, senza messaggi da televendita e senza automazioni invadenti."
    },
    {
      "title": "Dati leggibili da Google",
      "description": "Schema Product e Offer impostati per far capire a Google cosa viene venduto: consulenza, documento, pacchetto o pratica standard. Pulito. Punto."
    }
  ],
  "faqs": [
    {
      "question": "Ha senso un e-commerce per uno studio professionale?",
      "answer": "Sì, quando lo studio ha servizi ripetibili: consulenze iniziali, pacchetti forfettari, documenti scaricabili, analisi preliminari o pratiche standard. Non sostituisce il rapporto professionale: elimina passaggi inutili prima dell’incarico, soprattutto quando il cliente sa già cosa gli serve."
    },
    {
      "question": "Posso vendere consulenze senza sembrare un negozio qualunque?",
      "answer": "Sì. La struttura deve restare sobria: pagina chiara, ambito del servizio, cosa è incluso, cosa non è incluso, tempi di risposta e modalità operative. Niente carrelli pacchiani, badge finti o urgenze artificiali. Uno studio deve vendere con ordine, non con rumore."
    },
    {
      "question": "Come gestisco documenti scaricabili e modelli?",
      "answer": "I file possono essere collegati all’ordine e resi disponibili solo dopo il pagamento. Si possono limitare accessi, aggiornare versioni e inviare email automatiche con istruzioni. Così non vivi più dentro una catena di allegati, richieste duplicate e link persi."
    },
    {
      "question": "Meglio WooCommerce o piattaforma custom?",
      "answer": "Dipende dal tipo di catalogo. WooCommerce va bene per pacchetti, documenti, consulenze e flussi standard. Una piattaforma custom ha senso quando ci sono regole particolari, accessi riservati, logiche documentali o integrazioni interne. Prima si mappa il processo, poi si sceglie lo strumento."
    },
    {
      "question": "Posso separare acquisto online e incarico professionale?",
      "answer": "Sì, e spesso conviene. Il pagamento può riguardare una consulenza preliminare, un documento, una verifica o una fase specifica. L’incarico principale resta separato, con condizioni e passaggi propri. L’e-commerce ordina l’ingresso, non banalizza la professione. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "consulenza online"
},
  'casa-edilizia': {
  "description": "Per idraulici, elettricisti, fabbri e rivendite tecniche, l’e-commerce non è una vetrina carina: è catalogo, disponibilità, schede prodotto, pagamenti e spedizioni. Se il listino resta in PDF o al telefono, ogni ordine nasce storto e passa da tre conferme inutili.",
  "microStory": "Un rivenditore di materiali edili aveva 420 articoli in un gestionale e zero catalogo pubblico. I clienti chiamavano per misure, disponibilità e ritiro, anche per domande da 30 secondi. L’e-commerce è partito con catalogo consultabile, richiesta disponibilità, ritiro in sede e schede prodotto con dati tecnici. Non tutti gli articoli erano acquistabili subito: meglio così, perché alcune varianti richiedono verifica. Dopo 8 settimane le telefonate ripetitive sono calate del 32% e le richieste arrivate dal sito erano già divise per categoria.",
  "caseStudyRef": undefined,
  "solutionTitle": "E-commerce edile: catalogo chiaro, meno telefonate inutili",
  "problems": [
    {
      "icon": "ph-shopping-bag",
      "title": "Vendita bloccata offline",
      "desc": "Materiali, ricambi, utensili e accessori tecnici restano fermi dietro banco o in magazzino. Chi cerca un miscelatore, una serratura, un interruttore o un profilo serramento non può comprarlo quando gli serve. Nel frattempo va altrove."
    },
    {
      "icon": "ph-clock",
      "title": "Disponibilità al telefono",
      "desc": "Ogni chiamata per sapere se un prodotto c’è consuma tempo operativo. Rispondere, controllare, richiamare, confermare: una catena inutile quando disponibilità, varianti e ritiro in sede possono stare già online, aggiornati e leggibili."
    },
    {
      "icon": "ph-database",
      "title": "Listini fuori controllo",
      "desc": "PDF vecchi, fogli Excel, codici scritti a mano e plug-in scelti a caso creano confusione. Il cliente vede una cosa, il magazzino ne dice un’altra, l’ordine parte male. Poi tocca sistemarlo a voce."
    }
  ],
  "features": [
    {
      "title": "Catalogo tecnico ordinato",
      "description": "Prodotti divisi per categorie reali: rubinetteria, ferramenta, elettrico, serramenti, materiali edili. Schede con codici, misure, varianti, compatibilità e foto pulite, senza descrizioni finte da template generico."
    },
    {
      "title": "Magazzino visibile online",
      "description": "Disponibilità chiare per vendita, ritiro in sede o richiesta dedicata. Il cliente capisce subito se può ordinare, ritirare o aspettare, senza intasare il telefono per ogni articolo."
    },
    {
      "title": "Pagamenti e spedizioni",
      "description": "Checkout con Stripe, PayPal, bonifico e regole di spedizione coerenti con peso, ingombro, zona e tipo di prodotto. Un bancale non si tratta come una maniglia. Punto."
    },
    {
      "title": "Email ordine e recupero",
      "description": "Email transazionali scritte in italiano chiaro: conferma, pagamento, spedizione, ritiro, carrello lasciato a metà. Niente frasi da agenzia a 6 mani, solo istruzioni utili."
    },
    {
      "title": "Dati per Google Shopping",
      "description": "Schema Product e Offer, titoli leggibili, disponibilità e dati prodotto pronti per farsi capire da Google. Non magia SEO: catalogo pulito, informazioni corrette, struttura stabile."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere online anche prodotti tecnici con molte varianti?",
      "answer": "Sì, ma le varianti vanno progettate bene: misura, colore, attacco, materiale, compatibilità, marca e codice articolo devono essere chiari. Se il cliente compra il pezzo sbagliato perché la scheda è vaga, l’e-commerce diventa solo un altro problema da gestire."
    },
    {
      "question": "Serve per forza WooCommerce o posso usare una piattaforma custom?",
      "answer": "Dipende da catalogo, magazzino e flussi interni. WooCommerce va bene quando la struttura è gestibile e serve partire con controllo. Una piattaforma custom ha senso se ci sono regole complesse su disponibilità, listini, spedizioni o integrazioni con gestionale."
    },
    {
      "question": "Posso mostrare il catalogo senza vendere tutto subito online?",
      "answer": "Sì. Alcuni prodotti possono avere acquisto diretto, altri solo richiesta tecnica, ritiro in sede o contatto dedicato. Per materiali edili, serramenti e articoli configurabili è spesso la scelta più pulita: il cliente vede cosa trattate, senza forzare ordini sbagliati."
    },
    {
      "question": "Come gestisco prodotti pesanti o difficili da spedire?",
      "answer": "Si impostano regole per peso, volume, zona, ritiro in sede e spedizione dedicata. Cementi, profili lunghi, porte, utensili e minuteria non possono seguire la stessa logica. Il checkout deve dirlo prima, non dopo l’ordine."
    },
    {
      "question": "Il mio listino è in Excel: si può usare?",
      "answer": "Sì, se il file viene ripulito: codici coerenti, categorie, descrizioni, varianti, disponibilità e immagini collegate. Caricare un Excel sporco dentro un e-commerce significa solo spostare il caos online. Prima si mette ordine, poi si pubblica. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "materiali edili online"
},
  'auto-mobilita': {
  "description": "Ricambi, accessori, pneumatici, kit tagliando e prodotti per officina non possono restare chiusi dietro il banco. Chi cerca online confronta disponibilità, compatibilità, ritiro in sede e spedizione. Se trova solo marketplace giganti, il rapporto locale parte già in salita.",
  "microStory": "Un negozio ricambi gestiva ordini da banco, telefonate e messaggi con codici scritti in modi diversi. Il rischio era spedire il pezzo sbagliato o perdere ore a chiedere targa, modello e anno. L’e-commerce è stato costruito con filtri, SKU puliti, richiesta compatibilità e ritiro in sede. Su 160 prodotti iniziali, gli errori di richiesta sono scesi da 11 a 2 nel primo mese. Il banco non è sparito: ha smesso di fare da motore di ricerca umano.",
  "caseStudyRef": undefined,
  "solutionTitle": "Ricambi auto online, senza perdere il controllo del banco",
  "problems": [
    {
      "icon": "ph-storefront",
      "title": "Banco troppo chiuso",
      "desc": "Il cliente chiama per sapere se hai quel filtro, quella batteria o quel treno gomme. Ogni telefonata interrompe il lavoro, mentre il catalogo resta invisibile a chi era già pronto a comprare o passare in sede."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Cataloghi improvvisati",
      "desc": "Schede prodotto copiate male, varianti confuse, compatibilità assenti e plug-in messi a caso creano ordini sbagliati. Nel mondo auto un errore su modello, anno o misura non è un dettaglio: diventa reso, tempo perso, nervosismo."
    },
    {
      "icon": "ph-chart-line-down",
      "title": "Marketplace davanti a te",
      "desc": "Norauto, Amazon e grandi catene intercettano ricerche che potrebbero arrivare a un ricambista, gommista o concessionaria locale. Non perché siano più vicini, ma perché Google capisce meglio il loro catalogo."
    }
  ],
  "features": [
    {
      "title": "Catalogo ricambi ordinato",
      "description": "Prodotti, categorie, marche, codici, compatibilità, varianti e disponibilità vengono strutturati per essere consultabili senza telefonate inutili e senza confondere chi cerca il pezzo giusto."
    },
    {
      "title": "Magazzino sotto controllo",
      "description": "Stock, prodotti esauriti, ritiro in sede e spedizione devono parlare la stessa lingua. Il sito non deve vendere merce fantasma né nascondere articoli pronti in deposito."
    },
    {
      "title": "Pagamenti e spedizioni",
      "description": "Stripe, PayPal, bonifico, corrieri e ritiro locale vengono collegati al flusso d'ordine in modo chiaro, con email transazionali leggibili e stati ordine comprensibili."
    },
    {
      "title": "Recupero carrelli persi",
      "description": "Chi mette una batteria o un accessorio nel carrello e sparisce può ricevere un promemoria sensato. Non spam aggressivo, solo recupero ordinato di acquisti lasciati a metà."
    },
    {
      "title": "Dati per Google Shopping",
      "description": "Schema Product e Offer aiutano Google a leggere prezzo, disponibilità, marca e prodotto. Per ricambi e accessori auto, la struttura tecnica pesa quanto la grafica."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere online anche se molti clienti ritirano in officina?",
      "answer": "Sì. Per ricambi, gomme e accessori il ritiro in sede è spesso il flusso più sensato. Il cliente controlla disponibilità, paga o prenota, poi passa quando gli è comodo. Meno telefonate, meno messaggi sparsi, più ordine tra banco e sito. Punto."
    },
    {
      "question": "Come si gestiscono compatibilità e varianti dei ricambi?",
      "answer": "Vanno progettate prima di caricare prodotti a caso. Codici, marca, modello, anno, misure e note tecniche devono essere campi chiari, non testo buttato nella descrizione. Altrimenti arrivano ordini sbagliati e il sito diventa un altro problema."
    },
    {
      "question": "Meglio WooCommerce o piattaforma custom per un negozio auto?",
      "answer": "Dipende dal catalogo e dal modo in cui lavori. WooCommerce è adatto se serve partire con una struttura gestibile e integrazioni comuni. Una piattaforma custom ha senso quando magazzino, compatibilità o flussi interni sono troppo specifici per essere piegati da plug-in random."
    },
    {
      "question": "Serve caricare tutto il magazzino subito?",
      "answer": "No. Spesso conviene partire dalle categorie più cercate: batterie, pneumatici, accessori stagionali, kit tagliando, prodotti con margine o rotazione alta. Un catalogo piccolo ma pulito batte mille schede confuse importate senza criterio. Fine della storia."
    },
    {
      "question": "L'e-commerce può aiutare anche chi vende soprattutto offline?",
      "answer": "Sì, se viene trattato come catalogo operativo, non come vetrina decorativa. Chi cerca un ricambio vicino vuole capire se c'è, se è compatibile e come ritirarlo. Se queste risposte mancano, finisce sulle grandi catene. Decidi tu."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "ricambi auto online"
},
  'food-hospitality': {
  "description": "Nel food e hospitality, un ristorante, un hotel o un agriturismo che vende solo tramite portali e app lascia margini, contatti e riordini fuori controllo. L'e-commerce serve per asporto diretto, cesti, prodotti tipici e voucher, con catalogo, pagamenti, spedizioni e dati leggibili.",
  "microStory": "Un locale con prodotti tipici vendeva cesti e asporto solo via telefono. Nei periodi caldi arrivavano messaggi incompleti: data, ritiro, allergeni e quantità mancavano quasi sempre. L’e-commerce ha introdotto schede chiare, fasce di ritiro, note ordine e email di conferma. Per i tavoli è rimasto il canale già usato, senza creare un altro pannello inutile. Nel primo periodo festivo sono entrati 54 ordini diretti dal sito e le chiamate per correggere dettagli sono scese sotto 1 su 10.",
  "caseStudyRef": undefined,
  "solutionTitle": "Vendere tavoli, cesti e asporto senza farsi mangiare dai portali",
  "problems": [
    {
      "icon": "ph-chart-line-down",
      "title": "Commissioni che mordono",
      "desc": "Se asporto e delivery passano solo da Glovo o Deliveroo, ogni ordine arriva già tagliato. Il cliente ricorda l'app, non il locale. Il margine resta fragile, soprattutto nei picchi."
    },
    {
      "icon": "ph-shopping-bag",
      "title": "Prodotti mai venduti",
      "desc": "Cesti regalo, conserve, vini, panettoni, box degustazione e gift card restano fermi perché sono raccontati su Instagram e poi ordinati in chat. Bello finché arrivano tre richieste, ingestibile appena crescono."
    },
    {
      "icon": "ph-calendar-blank",
      "title": "Tavoli senza anticipo",
      "desc": "Menu speciali, brunch, degustazioni e serate a numero chiuso vengono prenotati a voce, con messaggi sparsi e no-show. Senza pagamento o caparra online, il calendario resta pieno solo sulla carta."
    }
  ],
  "features": [
    {
      "title": "Catalogo per food",
      "description": "Prodotti, formati, allergeni, disponibilità, varianti e foto gestiti in modo ordinato. Un B&B può vendere voucher, una pasticceria box stagionali, un agriturismo pacchi misti."
    },
    {
      "title": "Pagamenti e spedizioni",
      "description": "Stripe, PayPal, bonifico, ritiro in sede, consegna locale e corrieri configurati senza catene di plugin messi lì a caso. Ogni ordine deve avere stato, ricevuta e tracciamento."
    },
    {
      "title": "Carrello recuperabile",
      "description": "Email transazionali, carrelli abbandonati e messaggi post-acquisto scritti per chi compra cibo, voucher o soggiorni. Nessuna frase finta da template americano riciclato."
    },
    {
      "title": "Magazzino senza caos",
      "description": "Scorte, disponibilità per data, quantità limitate e prodotti esauriti gestiti prima che il cliente paghi. Utile quando un lotto, una camera o un menu hanno numeri reali."
    },
    {
      "title": "Dati per Google",
      "description": "Schema Product e Offer, feed compatibili e informazioni chiare su prezzo, disponibilità e spedizione. Google deve capire cosa vendi senza interpretare pagine piene di slogan."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere asporto senza togliere tutto da Glovo o Deliveroo?",
      "answer": "Sì. L'e-commerce diretto può convivere con le app, ma serve a riportare una parte degli ordini sul tuo dominio. Ha senso spingere lì clienti abituali, ordini ricorrenti, box speciali e ritiro in sede. Le app restano canali, non padroni del locale."
    },
    {
      "question": "Per un ristorante ha senso un e-commerce o basta il sito con menu?",
      "answer": "Dipende da cosa vendi. Se hai solo consultazione del menu, basta una pagina fatta bene. Se vendi delivery, cene prepagate, gift card, degustazioni, prodotti confezionati o box per ricorrenze, allora serve un flusso d'acquisto vero, non un modulo contatti travestito."
    },
    {
      "question": "Si possono gestire voucher regalo per hotel, B&B o agriturismi?",
      "answer": "Sì, con voucher acquistabili online, email automatica, codice univoco e regole chiare su validità, servizi inclusi e modalità di riscatto. Meglio definirli bene prima, perché un voucher ambiguo crea telefonate, discussioni e lavoro manuale in reception."
    },
    {
      "question": "Come gestisco prodotti freschi, disponibilità limitata o ritiri su prenotazione?",
      "answer": "Si imposta il catalogo attorno ai vincoli reali: quantità giornaliere, fasce di ritiro, giorni chiusi, prodotti stagionali e limiti per ordine. Un sistema serio non deve accettare venti box quando in laboratorio ne puoi preparare dodici. Punto."
    },
    {
      "question": "WooCommerce basta o serve una piattaforma custom?",
      "answer": "WooCommerce va bene quando catalogo, pagamenti, spedizioni e gestione interna restano abbastanza standard. Una piattaforma custom ha senso se ci sono regole particolari: prenotazioni prepagate, disponibilità per data, integrazioni con gestionale o flussi misti tra tavolo, camera e prodotto."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "comprare online"
},
  'retail-negozi': {
  "description": "Per un negozio fisico, l'e-commerce non deve cancellare il banco: deve tenere aperta una seconda vetrina quando la serranda è giù. Catalogo, stock, pagamenti, spedizioni e schede prodotto vanno governati insieme, senza catene di fornitori e plug-in messi a caso.",
  "microStory": "Una boutique di provincia aveva 320 articoli gestiti tra cassa, Instagram e messaggi privati. Le disponibilità cambiavano in giornata e ogni vendita online diventava una trattativa. L’e-commerce è partito con click and collect, varianti taglia-colore e aggiornamento stock dal gestionale. Le schede non sembrano marketplace anonimo: mostrano materiali, vestibilità e ritiro. Nel primo mese sono arrivati 73 ordini o prenotazioni prodotto, e il negozio ha ridotto i messaggi “ce l’avete ancora?” di circa metà.",
  "caseStudyRef": undefined,
  "solutionTitle": "E-commerce per negozi veri, non template da marketplace",
  "problems": [
    {
      "icon": "ph-clock",
      "title": "Serranda chiusa online",
      "desc": "Il negozio vende quando è aperto, mentre chi cerca una borsa, un vaso o un libro dopo cena finisce altrove. Non serve trasformarsi in Amazon: serve un canale diretto che lavori anche fuori orario."
    },
    {
      "icon": "ph-database",
      "title": "Magazzino fuori controllo",
      "desc": "Senza stock collegato al catalogo, il cliente compra un articolo già finito in negozio. Poi arrivano telefonate, rimborsi, scuse e tempo buttato. Il problema non è vendere online: è vendere senza ordine operativo."
    },
    {
      "icon": "ph-shopping-bag",
      "title": "Clienti regalati ai marketplace",
      "desc": "Amazon e piattaforme simili incassano visibilità, dati e riacquisti. Tu spedisci, loro restano nella testa del cliente. Per un retail indipendente, questo significa margine eroso e relazione spostata fuori dal negozio."
    }
  ],
  "features": [
    {
      "title": "Catalogo gestibile",
      "description": "Prodotti, categorie, taglie, colori, materiali e varianti impostati con criterio. Un fioraio, una gioielleria o una libreria hanno logiche diverse: il catalogo deve seguirle, non schiacciarle."
    },
    {
      "title": "Stock e varianti",
      "description": "Magazzino leggibile, disponibilità chiare e regole per articoli esauriti, pezzi unici o prodotti su ordinazione. Meno vendite sbagliate, meno gestione manuale dopo l'acquisto."
    },
    {
      "title": "Pagamenti e spedizioni",
      "description": "Stripe, PayPal, bonifico, ritiro in negozio, consegna locale o corriere: il checkout viene costruito sulle modalità reali del punto vendita, senza passaggi inutili."
    },
    {
      "title": "Email che chiudono",
      "description": "Conferme ordine, aggiornamenti spedizione, carrello recuperato e ricevute devono essere pulite, riconoscibili e utili. Non newsletter urlate: messaggi transazionali che evitano dubbi e chiamate ripetitive."
    },
    {
      "title": "Dati per Google",
      "description": "Schema Product e Offer preparati per rendere leggibili prezzo, disponibilità, marca e prodotto a Google Shopping. Se la scheda è confusa, Google la capisce male. Punto."
    }
  ],
  "faqs": [
    {
      "question": "Ha senso fare e-commerce se ho già un negozio fisico?",
      "answer": "Sì, se viene trattato come estensione del banco, non come progetto separato. Un negozio di abbigliamento può vendere taglie rimaste, una libreria può gestire ordini locali, un fioraio può ricevere richieste fuori orario. Il fisico resta centrale, l'online toglie attrito."
    },
    {
      "question": "Devo caricare tutto il catalogo subito?",
      "answer": "No. Spesso conviene partire dai prodotti con più margine, più richiesta o gestione più semplice: best seller, articoli continuativi, idee regalo, pezzi disponibili a magazzino. Caricare tutto senza criterio crea schede deboli, foto mediocri e gestione pesante."
    },
    {
      "question": "Come evito di vendere prodotti non disponibili?",
      "answer": "Serve una logica di magazzino chiara: disponibilità aggiornata, soglie, varianti gestite bene e regole per prodotti esauriti. Per articoli unici, come gioielli o arredamento, il sistema deve bloccare doppie vendite e rendere visibile quando un pezzo non è più acquistabile."
    },
    {
      "question": "Meglio WooCommerce o piattaforma custom?",
      "answer": "Dipende da catalogo, flussi e autonomia richiesta. WooCommerce va bene quando serve partire con una base robusta e gestibile. Una piattaforma custom ha senso quando ci sono regole particolari: configurazioni, listini complessi, sincronizzazioni o processi che un plug-in generico complica."
    },
    {
      "question": "Posso usare l'e-commerce solo per ritiro in negozio?",
      "answer": "Sì. Per molti negozi è una scelta intelligente: il cliente ordina online, paga o prenota, poi ritira in sede. Funziona bene per librerie, ferramenta, fiorai e negozi con clientela locale. Meno spedizioni, più passaggi in punto vendita. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "comprare online"
},
  'creativita-eventi': {
  "description": "Fotografi, videomaker e organizzatori eventi vendono stampe, album, workshop e pacchetti tra DM, Drive e bonifici manuali. Il cliente non capisce cosa compra, la caparra resta appesa, il portfolio non diventa catalogo. Qui l'e-commerce deve fare ordine, incasso e conferma. Punto.",
  "microStory": "Un fotografo vendeva album, stampe e servizi evento solo nei DM. Ogni richiesta richiedeva listino, esempi, tempi, revisione, indirizzo e conferma manuale. L’e-commerce ha diviso prodotti fisici, servizi prenotabili e richieste evento, con upload dei dati essenziali e email di riepilogo. Il catalogo non ha svenduto il lavoro creativo: ha tolto confusione. In 7 settimane sono entrati 26 ordini tra stampe e album, mentre le richieste evento arrivavano già con data, luogo e numero indicativo di persone.",
  "caseStudyRef": undefined,
  "solutionTitle": "Basta vendere album, stampe e pacchetti evento nei DM",
  "problems": [
    {
      "icon": "ph-instagram-logo",
      "title": "Vendite disperse nei DM",
      "desc": "Stampe, libri foto, voucher e pacchetti vengono chiesti su Instagram, confermati su WhatsApp e pagati altrove. Ogni ordine diventa una mini-produzione manuale, con file, indirizzi e conferme sparsi."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Pacchetti poco chiari",
      "desc": "Un wedding-planner o un videomaker non può spiegare ogni volta cosa include un pacchetto. Senza listino, varianti e limiti chiari, il cliente interpreta, chiede sconti e rimanda la decisione."
    },
    {
      "icon": "ph-credit-card",
      "title": "Caparre gestite a mano",
      "desc": "Bonifico, screenshot, controllo conto, messaggio di conferma: la caparra diventa un passaggio fragile. Se manca un automatismo, l'evento resta in sospeso e il calendario non è davvero bloccato."
    }
  ],
  "features": [
    {
      "title": "Catalogo pacchetti chiaro",
      "description": "Album, stampe, workshop, gift card e servizi pre-confezionati organizzati con varianti, descrizioni, extra e limiti. Il cliente sceglie senza dover ricostruire tutto in chat."
    },
    {
      "title": "Caparre e saldi online",
      "description": "Pagamenti con Stripe, PayPal o bonifico tracciato, con conferme automatiche e stati ordine leggibili. Utile per bloccare date, sessioni fotografiche, eventi e consegne senza rincorrere screenshot."
    },
    {
      "title": "Varianti senza caos",
      "description": "Formati stampa, numero pagine, copertine, location, durata, extra video e opzioni regalo gestiti dentro il flusso d'acquisto. Meno messaggi ripetuti, meno errori in produzione."
    },
    {
      "title": "Email transazionali pulite",
      "description": "Conferma ordine, istruzioni upload file, promemoria pagamento, recupero carrello e aggiornamenti spedizione scritti in italiano chiaro. Non newsletter travestite: comunicazioni operative."
    },
    {
      "title": "Dati per Google Shopping",
      "description": "Schema Product e Offer per rendere leggibili prodotti, disponibilità e offerte ai motori di ricerca. Serve quando vendi stampe, album, corsi o kit digitali cercabili online."
    }
  ],
  "faqs": [
    {
      "question": "Posso vendere sia stampe fisiche sia pacchetti fotografici?",
      "answer": "Sì. Vanno separati bene: prodotti spediti con formati, materiali e indirizzo; pacchetti con data, caparra, saldo e condizioni. Mischiarli nello stesso calderone crea ordini ambigui e messaggi infiniti. La struttura deve riflettere come lavori davvero."
    },
    {
      "question": "Devo usare WooCommerce o una piattaforma custom?",
      "answer": "Dipende da catalogo, magazzino, varianti e automazioni. WooCommerce regge bene stampe, album, voucher e pagamenti standard. Una piattaforma custom ha senso quando il configuratore pacchetti, il calendario o i flussi interni sono troppo specifici."
    },
    {
      "question": "Come gestisco la caparra per matrimoni o eventi?",
      "answer": "La caparra può essere un prodotto, una quota collegata a un pacchetto o un pagamento iniziale con saldo successivo. La parte importante è la conferma automatica: data bloccata, email inviata, ordine registrato, niente controllo manuale ogni mattina."
    },
    {
      "question": "Posso far caricare file o preferenze dopo l'acquisto?",
      "answer": "Sì, ma conviene non caricare tutto nel checkout. Meglio raccogliere l'ordine, poi inviare istruzioni chiare per file, selezioni foto, note evento o preferenze. Il checkout resta rapido e la produzione riceve dati ordinati."
    },
    {
      "question": "Serve davvero il recupero carrello per questo settore?",
      "answer": "Se vendi album, stampe, corsi o gift card, sì. Molti clienti iniziano da mobile, guardano opzioni, poi si fermano. Un recupero carrello sobrio ricorda cosa avevano scelto senza spingere con frasi finte. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "comprare album foto"
}
};
