// AUTO-GENERATED by scripts/generate-matrix-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate the relevant cell instead.
// Servizio: SEO & Visibilità
// Categorie: beauty-wellness, sanita-salute, studi-professionali, casa-edilizia, auto-mobilita, food-hospitality, retail-negozi, creativita-eventi

import type { ServiceCategoryContent } from '../seo-service-content';

export const SEO_CONTENT: Record<string, ServiceCategoryContent> = {
  'beauty-wellness': {
  "description": "Nel beauty la ricerca parte spesso da Google, non solo da Instagram. Se il salone compare male, ha orari sbagliati o recensioni ferme, il cliente sceglie chi trova prima. La SEO serve a rendere parrucchieri, estetiste e centri visibili quando qualcuno cerca un appuntamento in zona.",
  "microStory": "Un salone a Frosinone era forte su Instagram ma invisibile per “parrucchiere frosinone” e “balayage frosinone”. Il sito aveva una home leggera, nessuna pagina trattamento e Google Business con categorie sbagliate. Il lavoro SEO è partito da schema locale, pagine servizi, foto nominate bene, link interni e scheda Google ripulita. Dopo 4 mesi la query principale è salita da posizione 18 a 4. Le chiamate tracciate da ricerca organica sono passate da 7 a 29 al mese.",
  "caseStudyRef": undefined,
  "solutionTitle": "Il tuo salone non può vivere solo di Instagram",
  "problems": [
    {
      "icon": "ph-instagram-logo",
      "title": "Solo Instagram, niente Google",
      "desc": "I post girano, qualche reel prende like, ma su Google non esci per ricerche come parrucchiere a città, estetista vicino a me o palestra in zona. Intanto il cliente pronto a prenotare finisce da altri."
    },
    {
      "icon": "ph-clock",
      "title": "Scheda Google trascurata",
      "desc": "Orari vecchi, foto del locale datate, servizi scritti male, categorie sbagliate. Google Business diventa una vetrina stanca proprio nel momento in cui una persona sta decidendo dove tagliare i capelli o prenotare un trattamento."
    },
    {
      "icon": "ph-chart-line-down",
      "title": "Recensioni ferme da mesi",
      "desc": "Le recensioni non arrivano da sole. Se non esiste un trigger chiaro dopo appuntamento, trattamento o abbonamento, la scheda resta immobile. E una scheda immobile, nel beauty, sembra un centro poco frequentato anche quando non lo è."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico SEO",
      "description": "Controllo Core Web Vitals, pagine indicizzate, errori di crawl, struttura tecnica e blocchi invisibili che impediscono al sito del salone o del centro di farsi leggere correttamente da Google."
    },
    {
      "title": "Keyword del settore",
      "description": "Mappo ricerche reali: taglio donna, balayage, pulizia viso, ceretta, personal trainer, scuola danza. Poi preparo una traccia contenuti sensata, senza articoli riempitivi scritti per nessuno."
    },
    {
      "title": "SEO locale ordinata",
      "description": "Sistemo Google Business, categorie, servizi, foto, citation locali e segnali territoriali. L’obiettivo è farti trovare da chi cerca in zona, non da traffico casuale che non prenoterà mai."
    },
    {
      "title": "On-page e schema",
      "description": "Rendo chiare pagine servizio, titoli, meta, collegamenti interni e dati strutturati. Google deve capire cosa fai, dove lo fai e perché quella pagina risponde a una ricerca concreta."
    },
    {
      "title": "Monitoring mensile pulito",
      "description": "Controllo posizioni, Google Search Console, GA4 e andamento delle ricerche locali. Niente report scenografici da agenzia a 6 mani: solo dati leggibili e decisioni operative. Punto."
    }
  ],
  "faqs": [
    {
      "question": "Ha senso fare SEO se il mio salone lavora già con Instagram?",
      "answer": "Sì, perché Instagram intercetta chi ti segue o ti scopre per caso. Google intercetta chi sta cercando ora un parrucchiere, un’estetista o una palestra vicino a casa. Sono due momenti diversi. Se manchi su Google, lasci fuori persone già pronte a prenotare."
    },
    {
      "question": "La scheda Google Business basta da sola?",
      "answer": "No. È fondamentale, ma non basta se sito, pagine servizio, recensioni, foto, categorie e contenuti locali non parlano la stessa lingua. Una scheda curata senza sito coerente regge poco. Un sito ordinato senza scheda curata perde richieste locali."
    },
    {
      "question": "Come faccio ad avere più recensioni senza sembrare insistente?",
      "answer": "Serve un processo semplice: richiesta dopo appuntamento, link diretto, messaggio breve e momento giusto. Dopo un taglio riuscito, un trattamento apprezzato o una prima lezione, il cliente è più disposto a lasciare una recensione. Nessuna pressione, solo metodo."
    },
    {
      "question": "Quanto tempo serve per vedere movimento su Google?",
      "answer": "Dipende dallo stato attuale: scheda Google, sito, concorrenza locale, recensioni e problemi tecnici. Di solito prima si mette ordine, poi si osservano ricerche, posizioni e richieste. La SEO locale non è un interruttore, è manutenzione commerciale."
    },
    {
      "question": "Devo scrivere articoli sul blog del salone?",
      "answer": "Solo se servono davvero. Meglio una pagina chiara su colore, trattamenti viso o corsi in palestra che dieci articoli generici copiati male. Il contenuto deve rispondere a domande reali dei clienti e portare verso una prenotazione sensata."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "parrucchiere a"
},
  'sanita-salute': {
  "description": "SEO per studi sanitari che devono farsi trovare senza scivolare nel marketing urlato. Dentisti, psicologi, fisioterapisti, veterinari e medici vivono di fiducia: se Google mostra colleghi, schede confuse e pagine generiche, il paziente non capisce chi scegliere. E la catena di fornitori peggiora il rumore.",
  "microStory": "Uno studio dentistico in Ciociaria appariva in posizione 17 per ricerche locali importanti. Il sito aveva testi duplicati, nessun markup medico locale e una scheda Google con servizi incompleti. La SEO è stata trattata come lavoro tecnico: pagine prestazione, FAQ sobrie, dati strutturati, citation NAP coerenti e link locali puliti. Dopo 4 mesi “dentista frosinone” era in posizione 3 stabile per molte ricerche da mobile. Le chiamate dal sito sono cresciute circa 4 volte, senza promesse da televendita.",
  "caseStudyRef": undefined,
  "solutionTitle": "SEO sanitaria senza agenzie a 6 mani e pagine copia-incolla",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "Invisibile in città",
      "desc": "Il paziente cerca dentista, psicologo o fisioterapista nella sua zona e trova altri studi. Non perché siano migliori, ma perché Google capisce meglio le loro pagine, la scheda locale e i segnali intorno al brand."
    },
    {
      "icon": "ph-code",
      "title": "Schema lasciato vuoto",
      "desc": "Molti siti sanitari hanno pagine belle da vedere ma mute per Google: niente MedicalOrganization, Physician, dati strutturati sui servizi, indirizzo coerente o segnali locali puliti. Risultato: meno contesto, meno fiducia, meno clic utili."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Contenuti scritti a caso",
      "desc": "Senza una strategia su sintomi, patologie, trattamenti e domande reali, il blog diventa riempitivo. Il paziente cerca risposte concrete, trova articoli generici e finisce sul sito di chi ha lavorato meglio sulla ricerca."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico SEO",
      "description": "Controllo Core Web Vitals, crawlability, indexing, errori tecnici, sitemap, redirect e pagine che Google ignora. Niente report ornamentali: solo blocchi reali da sistemare."
    },
    {
      "title": "Keyword sanitarie mirate",
      "description": "Analisi delle ricerche locali e informative: prestazioni, sintomi, patologie, quartieri, comuni serviti e intenti del paziente. Si lavora su ciò che può portare contatti sensati."
    },
    {
      "title": "SEO locale ordinata",
      "description": "Google Business Profile, citation, coerenza NAP, categorie, recensioni e segnali territoriali. Se lo studio lavora su una città specifica, Google deve leggerlo senza interpretazioni creative."
    },
    {
      "title": "On-page e schema",
      "description": "Titoli, heading, testi, internal link, dati strutturati MedicalOrganization o Physician dove pertinenti, pagine servizio più chiare. Il sito deve parlare al paziente e al motore di ricerca insieme."
    },
    {
      "title": "Monitoring mensile pulito",
      "description": "Rank tracking, Search Console, GA4 e controllo delle query che crescono o si fermano. Si corregge mese per mese, invece di cambiare plugin random sperando che succeda qualcosa."
    }
  ],
  "faqs": [
    {
      "question": "La SEO sanitaria deve rispettare le regole deontologiche?",
      "answer": "Sì. Per studi medici, psicologi, dentisti e professionisti sanitari il punto non è urlare promesse, ma rendere chiari servizi, competenze, sedi, modalità di accesso e contenuti informativi. La comunicazione deve restare sobria, verificabile e coerente con il settore. Fine della storia."
    },
    {
      "question": "Serve davvero lavorare sulla SEO locale?",
      "answer": "Sì, perché molte ricerche sanitarie sono territoriali: dentista a Bologna, fisioterapista a Verona, psicologo vicino a me. Se scheda Google, sito, indirizzi e recensioni non sono allineati, lasci spazio ai colleghi. Non è magia, è ordine tecnico e contenutistico."
    },
    {
      "question": "Possiamo scrivere contenuti su sintomi e patologie?",
      "answer": "Sì, ma con criterio. I contenuti devono informare, non sostituire una visita o fare promesse. Si costruiscono pagine utili su domande reali del paziente, percorsi di cura, segnali da non ignorare e quando rivolgersi allo studio. Punto."
    },
    {
      "question": "Quanto tempo serve per vedere risultati SEO?",
      "answer": "Dipende da concorrenza locale, stato tecnico del sito, autorevolezza del dominio e quantità di contenuti già presenti. Prima si puliscono errori e pagine deboli, poi si misura cosa cambia su query, impression, clic e richieste. Niente teatro, solo dati."
    },
    {
      "question": "Devo rifare tutto il sito per fare SEO?",
      "answer": "Non sempre. A volte bastano struttura, testi, schema markup, pagine servizio e scheda Google sistemati bene. Se invece il sito è lento, confuso o pieno di template incollati, conviene intervenire più a fondo. Decidi tu, ma partendo dai dati."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "dentista a"
},
  'studi-professionali': {
  "description": "Se il tuo studio vive di passaparola ma su Google resta dietro portali, directory e concorrenti meno qualificati, il problema non è il mercato. È una SEO lasciata a template generici, blog fermi e dati locali confusi: proprio dove il cliente cerca un professionista nella sua città.",
  "microStory": "Uno studio professionale aveva un sito elegante, ma Google vedeva una sola pagina generica per tutto: consulenza, pratiche, contatti, città. La SEO ha separato servizi, intenti e ricerche locali, con titoli puliti, internal linking e Google Business collegato alle pagine giuste. Nessun articolo riempitivo ogni settimana: prima le pagine che portano richieste. Dopo 90 giorni, 11 query locali sono entrate in top 10. Le richieste da form sono passate da 3 a 14 al mese, più leggibili per materia.",
  "caseStudyRef": undefined,
  "solutionTitle": "SEO per studi che devono farsi trovare nella città giusta",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "Ricerche locali perse",
      "desc": "Chi digita avvocato divorzista, commercialista o architetto nella tua zona trova directory, portali e studi più presenti online. Non perché siano migliori: spesso hanno solo pagine più chiare, dati coerenti e segnali locali curati."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Contenuti da riempitivo",
      "desc": "Il blog parla di temi generici, copiati o scritti per sembrare attivo. Il cliente invece cerca risposte precise: separazione consensuale, successione, pratica edilizia, vendita immobile. Google legge la differenza. Punto."
    },
    {
      "icon": "ph-code",
      "title": "Markup tecnico assente",
      "desc": "Senza schema LegalService, AccountingService o dati strutturati coerenti, il sito dello studio comunica male a Google chi sei, dove lavori e quali servizi offri. Poi la colpa finisce al mercato. Fine della storia."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico serio",
      "description": "Controllo Core Web Vitals, crawlability, indexing, pagine duplicate, redirect, sitemap e struttura. Prima si capisce cosa blocca il sito, poi si interviene."
    },
    {
      "title": "Keyword per incarichi reali",
      "description": "Mappo ricerche legate a servizi concreti: divorzio, dichiarazioni, pratiche edilizie, atti notarili, compravendite. Niente lista keyword gonfiata per fare scena."
    },
    {
      "title": "SEO locale ordinata",
      "description": "Google Business, citation, NAP, categorie, foto, recensioni e coerenza dei dati. Perché nello studio professionale la zona pesa quanto la competenza percepita."
    },
    {
      "title": "Pagine on-page pulite",
      "description": "Titoli, meta, H1, sezioni, internal link e schema markup vengono sistemati intorno a ricerche vere, non intorno al gusto del plugin installato ieri."
    },
    {
      "title": "Monitoraggio mensile leggibile",
      "description": "Rank tracking, Search Console e GA4 letti insieme. Ti dico cosa sale, cosa scende, cosa va corretto e quali pagine stanno portando richieste concrete."
    }
  ],
  "faqs": [
    {
      "question": "Ha senso fare SEO se il mio studio lavora già con il passaparola?",
      "answer": "Sì, perché il passaparola oggi passa spesso da Google. Una persona riceve il tuo nome, poi controlla sito, recensioni, scheda locale e risultati collegati. Se trova poco, dati vecchi o contenuti deboli, il contatto si raffredda prima di scriverti."
    },
    {
      "question": "Serve per forza pubblicare articoli ogni settimana?",
      "answer": "No. Per uno studio professionale conta più pubblicare contenuti mirati che riempire il blog. Meglio una pagina ben fatta su separazione consensuale, successione o pratica edilizia nella tua zona che dieci articoli generici senza intento chiaro."
    },
    {
      "question": "Google Business è davvero così importante per uno studio?",
      "answer": "Sì. Per ricerche locali come commercialista vicino a me o architetto a Milano, Google Business incide molto. Categoria, descrizione, servizi, recensioni, foto e coerenza dell’indirizzo aiutano a capire se lo studio è pertinente e attivo."
    },
    {
      "question": "Quanto tempo serve per vedere segnali concreti?",
      "answer": "Dipende da stato del sito, concorrenza locale e storico del dominio. In genere prima si sistemano blocchi tecnici e pagine principali, poi si misura l’effetto su impression, posizioni e richieste. La SEO seria non è un interruttore."
    },
    {
      "question": "Potete lavorare su un sito già fatto da altri?",
      "answer": "Sì, se il sito è accessibile e modificabile. Prima verifico struttura, CMS, performance, tracciamenti e contenuti esistenti. Se è pieno di plug-in random o vincoli inutili, lo segnalo subito. Decidi tu."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "avvocato divorzista a"
},
  'casa-edilizia': {
  "description": "Per idraulici, elettricisti, imprese edili, fabbri e serramentisti la SEO non è teoria: è comparire quando qualcuno cerca un guasto, un intervento urgente o un lavoro già visto in foto. Se Google Business è vuoto e il sito è un template lento, il cliente chiama altri.",
  "microStory": "Un fabbro lavorava bene col passaparola ma non compariva per “fabbro urgente” nelle zone servite. Il sito aveva tre righe sui servizi e nessuna pagina per serrature, porte, cancelli o pronto intervento. La SEO ha mappato servizi e comuni, corretto title, schema locale, velocità mobile e profilo Google. Dopo 3 mesi le impression organiche sono passate da 420 a 3.100 mensili. Le chiamate da mobile sono cresciute soprattutto nelle fasce serali, quando il passaparola non risponde.",
  "caseStudyRef": undefined,
  "solutionTitle": "SEO per artigiani edili: basta brochure invisibili",
  "problems": [
    {
      "icon": "ph-clock",
      "title": "Urgenze non intercettate",
      "desc": "Chi cerca “idraulico urgente” o “elettricista festivo” non aspetta la terza pagina di Google. Se non hai pagine chiare per emergenze, zone servite e orari reali, il lavoro finisce a chi si è fatto trovare prima."
    },
    {
      "icon": "ph-storefront",
      "title": "Scheda Google debole",
      "desc": "Foto vecchie, categorie sbagliate, zone non compilate, poche recensioni: Google Business trattato come un biglietto da visita morto. Per un artigiano locale è spesso il primo contatto, non un dettaglio amministrativo."
    },
    {
      "icon": "ph-prohibit",
      "title": "Sito da agenzia generica",
      "desc": "Template copiato, plug-in random, testi tutti uguali e nessuna prova dei lavori fatti. La catena di fornitori produce pagine belle da riunione, ma inutili quando il cliente cerca un serramentista nel suo comune."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico SEO",
      "description": "Controllo Core Web Vitals, crawlability, indexing, errori tecnici e pagine bloccate. Prima si capisce cosa sta frenando il sito, poi si interviene. Punto."
    },
    {
      "title": "Keyword per interventi reali",
      "description": "Mappo ricerche come pronto intervento, sostituzione serrature, rifacimento bagno, quadri elettrici e infissi configurabili. Non parole astratte da report, ma query che portano richieste concrete."
    },
    {
      "title": "SEO locale completa",
      "description": "Ottimizzo Google Business, categorie, zone servite, foto lavori, recensioni e citation locali. Se lavori in comuni specifici, Google deve capirlo senza interpretazioni creative."
    },
    {
      "title": "Pagine servizio mirate",
      "description": "Creo o sistemo pagine per emergenze, servizi principali, quartieri e comuni serviti, con struttura leggibile, schema markup e contenuti basati su lavori veri, non frasi da catalogo."
    },
    {
      "title": "Monitoraggio mensile pulito",
      "description": "Rank tracking, Google Search Console e GA4 letti insieme. Niente PDF decorativi: si guarda cosa sale, cosa resta fermo e dove intervenire il mese dopo. Fine della storia."
    }
  ],
  "faqs": [
    {
      "question": "Mi serve davvero una pagina per ogni servizio edile?",
      "answer": "Non sempre, ma i servizi cercati in modo diverso meritano pagine diverse. “Riparazione perdita acqua”, “installazione caldaia” e “rifacimento bagno” hanno intenti distinti. Metterli tutti in una pagina generica confonde Google e anche chi deve decidere chi chiamare."
    },
    {
      "question": "Google Business può portare richieste senza rifare tutto il sito?",
      "answer": "Sì, soprattutto per ricerche locali e urgenti. Va però compilato bene: categorie, zone servite, foto recenti, servizi, recensioni e post coerenti. Se la scheda rimanda a un sito lento o povero, parte del lavoro viene sprecata."
    },
    {
      "question": "Le foto dei lavori aiutano la SEO?",
      "answer": "Aiutano molto, se usate con criterio. Un portfolio con bagni rifatti, quadri elettrici, serramenti montati o cancelli riparati dà prove concrete. Le immagini vanno nominate, compresse, inserite in pagine pertinenti e collegate ai servizi giusti."
    },
    {
      "question": "Ha senso puntare sulle emergenze notturne o festive?",
      "answer": "Solo se le gestisci davvero. Se fai pronto intervento, serve una pagina chiara con comuni coperti, casi trattati e modalità di contatto. Se non lo fai, meglio non attirare richieste sbagliate: fanno perdere tempo a tutti."
    },
    {
      "question": "Quanto tempo serve per vedere movimenti su Google?",
      "answer": "Dipende da concorrenza locale, stato tecnico del sito, storico del dominio e stato della scheda Google. Le correzioni tecniche possono incidere presto; contenuti e posizionamento locale richiedono monitoraggio. La SEO edile va trattata come cantiere: ordine, priorità, verifica."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "idraulico urgente a"
},
  'auto-mobilita': {
  "description": "Per officine, carrozzieri, gommisti, autoscuole e concessionarie, la ricerca nasce da urgenza, zona e fiducia: auto ferma, revisione, gomme, patente, usato. Se Google mostra il concorrente perché il sito è lento, la scheda è trascurata e le recensioni dormono, il lavoro finisce altrove. Punto.",
  "microStory": "Un’officina era presente su Google Maps, ma il sito non intercettava ricerche su tagliando, gomme e diagnosi. Le pagine erano tutte sotto “servizi”, senza contenuto utile. La SEO ha creato pagine per intervento, markup LocalBusiness, FAQ operative e collegamento tra scheda Google e sito. Dopo 12 settimane “tagliando auto + città” è passato dalla seconda pagina alla top 5. Le richieste con modello veicolo indicato sono diventate 19 al mese, prima arrivavano quasi solo telefonate confuse.",
  "caseStudyRef": undefined,
  "solutionTitle": "Auto ferma? Se non ti trovano, chiamano il vicino",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "Ricerche locali perse",
      "desc": "Chi cerca \"officina aperta sabato\", \"gommista vicino\" o \"carrozziere grandine\" non aspetta una campagna elegante. Apre Google, guarda mappa, recensioni e orari. Se lì sei debole, entra un altro."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Recensioni lasciate ferme",
      "desc": "Nel settore auto la fiducia passa da stelle, risposte e casi reali. Se le recensioni sono poche, vecchie o senza replica, Google e clienti leggono disordine. Non cattiveria: disordine."
    },
    {
      "icon": "ph-gear",
      "title": "Sito pieno di zavorra",
      "desc": "Template generici, plug-in messi a caso, pagine tutte uguali e nessun dato strutturato. Risultato: Google fatica a capire servizi, zone, marchi trattati, ricambi e urgenze. Fine della storia."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico secco",
      "description": "Controllo Core Web Vitals, indicizzazione, crawl, pagine morte, redirect sporchi, sitemap, mobile e dati tecnici. Niente report da vetrina: solo ciò che blocca traffico utile."
    },
    {
      "title": "Keyword per officina reale",
      "description": "Mappo ricerche legate a urgenze, città, quartieri, modelli auto, gomme stagionali, revisioni, sinistri, patente e usato. Ogni pagina deve avere un motivo preciso."
    },
    {
      "title": "SEO locale ordinata",
      "description": "Sistemo Google Business Profile, categorie, servizi, foto, post, citation, coerenza NAP e gestione recensioni. La mappa non premia chi urla: premia chi è chiaro e credibile."
    },
    {
      "title": "On-page senza fuffa",
      "description": "Titoli, testi, heading, link interni e schema markup per rendere leggibili servizi, zone, orari, recensioni e contatti. Pagine scritte per chi deve risolvere un problema adesso."
    },
    {
      "title": "Monitoraggio mensile pulito",
      "description": "Rank tracking, Google Search Console e GA4 letti insieme: chiamate, form, pagine che salgono, query perse, errori tecnici. Si guarda cosa cambia davvero. Decidi tu."
    }
  ],
  "faqs": [
    {
      "question": "La mia officina lavora già col passaparola: la SEO serve davvero?",
      "answer": "Il passaparola resta forte, ma quando l'auto si ferma fuori zona o serve un gommista sabato mattina, la ricerca parte da Google. La SEO locale ti rende presente in quel momento, con orari, servizi, recensioni e indicazioni coerenti."
    },
    {
      "question": "Le recensioni Google incidono sulle ricerche locali?",
      "answer": "Sì, soprattutto per officine, carrozzieri e gommisti. Non basta averne tante: contano frequenza, testo, risposte e coerenza con i servizi cercati. Un processo semplice per chiederle dopo il lavoro chiuso cambia molto più di una pagina piena di slogan."
    },
    {
      "question": "Ha senso creare pagine per marca o modello auto?",
      "answer": "Sì, se sono pagine utili e non copie svuotate. \"Tagliando Fiat Panda\", \"cambio gomme SUV\" o \"riparazione grandine utilitaria\" possono intercettare ricerche concrete. Vanno legate a competenze, zona, casi trattati e contenuti verificabili."
    },
    {
      "question": "Quanto tempo serve per vedere movimento su Google?",
      "answer": "Dipende da concorrenza locale, stato tecnico del sito, scheda Google e storico del dominio. Di solito prima si mettono in ordine errori, scheda e pagine chiave; poi si misura su query, chiamate e richieste reali, non su impression gonfiate."
    },
    {
      "question": "Devo rifare tutto il sito per fare SEO?",
      "answer": "Non per forza. Se il sito è recuperabile, si parte da struttura, velocità, pagine servizio, dati locali e contenuti mancanti. Se invece è un cumulo di template e plug-in fragili, continuare a rattoppare può costare più energia che ripartire puliti."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "officina aperta sabato"
},
  'food-hospitality': {
  "description": "Nel food e hospitality la ricerca parte dallo smartphone: menu, foto, orari, camere, tavoli liberi. Se Google trova profili incompleti, pagine lente e contenuti copiati, spinge portali e concorrenti. La SEO serve a riprendere controllo su ricerche locali, schede, recensioni e pagine che portano prenotazioni dirette.",
  "microStory": "Un agriturismo riceveva traffico dai portali ma quasi nulla dal sito. Google trovava pagine lente, menu in PDF e camere descritte in modo vago. La SEO ha corretto struttura, schema lodging, pagine camere, contenuti locali e Search Console. Non abbiamo combattuto Booking con slogan: abbiamo dato a Google pagine leggibili e al cliente risposte rapide. In 4 mesi le impression organiche sono cresciute da 1.200 a 8.900 mensili. Le richieste dirette dal sito sono passate da 5 a 26.",
  "caseStudyRef": undefined,
  "solutionTitle": "Se cercano dove mangiare o dormire, non devono trovare Booking prima di te",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "Google premia altri",
      "desc": "Il cliente cerca ristorante, pizzeria o B&B in zona e trova aggregatori, guide vecchie o concorrenti con schede curate. Non è destino: spesso è una catena di pagine deboli, menu invisibili e segnali locali lasciati al caso."
    },
    {
      "icon": "ph-storefront",
      "title": "Scheda lasciata sola",
      "desc": "Google Business senza menu, foto recenti, orari speciali e link corretti fa perdere fiducia prima del clic. Nel turismo e nella ristorazione la scelta è rapida: se la scheda sembra abbandonata, il tavolo va altrove."
    },
    {
      "icon": "ph-chart-line-down",
      "title": "Recensioni senza ritmo",
      "desc": "Le recensioni ferme fanno sembrare fermo anche il locale. Se non esiste un metodo pulito per chiederle, rispondere e valorizzarle, vincono le strutture che lavorano sui segnali pubblici ogni settimana. Punto."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico reale",
      "description": "Controllo Core Web Vitals, indicizzazione, crawlability, pagine lente, errori e blocchi tecnici. Niente report gonfiati: prima si capisce cosa impedisce a Google di leggere bene sito e contenuti."
    },
    {
      "title": "Keyword per prenotazioni",
      "description": "Mappatura delle ricerche locali: menu, cucina, camere, zona, servizi, eventi, intenti turistici. Da lì nasce un piano contenuti legato a tavoli, soggiorni e richieste concrete."
    },
    {
      "title": "SEO locale ordinata",
      "description": "Google Business, citation, NAP, categorie, foto, prodotti, menu, post e recensioni vengono sistemati con criterio. La scheda deve lavorare come punto di ingresso, non come vetrina dimenticata."
    },
    {
      "title": "On-page e schema",
      "description": "Titoli, testi, immagini, dati strutturati, pagine servizio, camere, menu e FAQ vengono ottimizzati per far capire a Google cosa offri, dove sei e perché mostrarti nella ricerca giusta."
    },
    {
      "title": "Monitoraggio mensile asciutto",
      "description": "Rank tracking, Search Console e GA4 servono per vedere query, clic, pagine che salgono e pagine ferme. Si taglia il rumore, si legge il dato, si decide il prossimo intervento."
    }
  ],
  "faqs": [
    {
      "question": "Il mio ristorante può posizionarsi senza dipendere da TripAdvisor?",
      "answer": "Sì, ma non copiando quattro testi generici sul sito. Servono pagine locali chiare, menu leggibile da Google, foto coerenti, scheda Business curata e recensioni fresche. I portali possono restare canali utili, ma non devono essere l’unico punto in cui il cliente capisce chi sei."
    },
    {
      "question": "Quanto conta Google Business per hotel, B&B e agriturismi?",
      "answer": "Conta moltissimo, soprattutto da smartphone. Orari, categorie, foto, link al sito, servizi, recensioni e risposte influenzano fiducia e clic. Una scheda incompleta crea attrito prima ancora che il cliente apra il sito. Prima si sistema quella, poi il resto respira meglio."
    },
    {
      "question": "Devo pubblicare articoli sul blog ogni settimana?",
      "answer": "Non per forza. Nel food e hospitality spesso servono prima pagine utili: cucina, menu, zona, camere, eventi, parcheggio, gruppi, cerimonie, esperienze locali. Il blog ha senso solo quando intercetta ricerche vere, non quando riempie il sito di testi scritti per fare volume."
    },
    {
      "question": "Le recensioni Google aiutano davvero la SEO locale?",
      "answer": "Sì, ma non basta accumularle. Contano frequenza, pertinenza, risposte e coerenza con ciò che il cliente cerca. Un metodo semplice di richiesta post-visita o post-soggiorno può riattivare segnali fermi senza forzature, coupon aggressivi o messaggi imbarazzanti."
    },
    {
      "question": "Se il sito è bello ma non arrivano prenotazioni, cosa guardi prima?",
      "answer": "Prima controllo se Google riesce a capirlo: velocità, indicizzazione, struttura, query, pagine più viste, scheda Business, menu, camere, form e tracciamenti. Il sito può essere gradevole e restare invisibile. La SEO serve a togliere quei blocchi, uno per uno. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "ristorante a"
},
  'retail-negozi': {
  "description": "Per un negozio fisico la SEO non deve sostituire il banco, la vetrina o il rapporto con chi entra. Deve farti trovare quando qualcuno cerca un prodotto nel quartiere, confronta alternative e decide dove passare oggi, prima che Google gli serva la solita catena.",
  "microStory": "Una gioielleria locale compariva dietro catene e marketplace anche per ricerche con nome città. Il sito mostrava prodotti, ma senza categorie leggibili, dati locali e contenuti sulle occasioni. La SEO ha ordinato collezioni, pagine regalo, schema LocalBusiness, foto, Google Business e link interni. Dopo 5 mesi, 9 ricerche locali sono entrate in top 5. Le richieste WhatsApp dal sito sono aumentate del 68%, soprattutto per anniversari, lauree e riparazioni, non per traffico generico da curiosi.",
  "caseStudyRef": undefined,
  "solutionTitle": "SEO per negozi che non vogliono sparire dietro le catene",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "La catena prende tutto",
      "desc": "Chi cerca scarpe, fiori, libri o gioielli vicino casa trova marketplace, franchising e directory gonfiate. Il tuo negozio resta sotto, anche quando sei più vicino, più specifico e più utile per quella ricerca."
    },
    {
      "icon": "ph-receipt",
      "title": "Descrizioni copiate dal fornitore",
      "desc": "Le schede prodotto uguali a quelle di cento altri negozi non danno a Google un motivo per mostrarti. Cataloghi importati, testi identici e categorie buttate lì trasformano il sito in un doppione anonimo."
    },
    {
      "icon": "ph-camera",
      "title": "Google Business vuoto",
      "desc": "Una scheda senza foto degli interni, prodotti, reparti, orari aggiornati e recensioni recenti sembra trascurata. Il problema non è estetico: è fiducia locale, clic sulle indicazioni e visite in negozio perse."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico concreto",
      "description": "Controllo Core Web Vitals, indicizzazione, crawlability, pagine inutili, errori Search Console e blocchi tecnici che tengono fuori categorie, prodotti e pagine locali."
    },
    {
      "title": "Keyword da negozio reale",
      "description": "Mappo ricerche legate a prodotti, quartieri, occasioni d'acquisto e bisogni concreti: non keyword da blog vuoto, ma query che possono portare persone in negozio."
    },
    {
      "title": "SEO locale curata",
      "description": "Sistemo Google Business, foto, categorie, prodotti, citation, recensioni e coerenza dei dati. La scheda deve raccontare un negozio vivo, non un segnaposto dimenticato."
    },
    {
      "title": "On-page senza stampino",
      "description": "Riscrivo title, testi, categorie e schede con struttura pulita, intenti chiari e schema markup. Basta pagine clonate dal fornitore con due righe buttate dentro."
    },
    {
      "title": "Monitoraggio mensile leggibile",
      "description": "Rank tracking, GSC e GA4 servono a capire cosa sale, cosa resta fermo e cosa va corretto. Niente report decorativi da agenzia a sei mani."
    }
  ],
  "faqs": [
    {
      "question": "La SEO serve anche se vendo soprattutto in negozio?",
      "answer": "Sì, proprio perché il negozio fisico resta centrale. Molte persone cercano prima online per capire chi ha quel prodotto, dove si trova, che orari fa e se vale la pena passare. La SEO lavora su quel momento: prima della visita, non al posto della visita."
    },
    {
      "question": "Devo avere un e-commerce per fare SEO?",
      "answer": "No. Per abbigliamento, fiorai, ferramenta, librerie o gioiellerie può bastare un sito con categorie, pagine prodotto selezionate, contenuti locali e una Google Business curata. L'obiettivo può essere portare richieste, telefonate, indicazioni stradali e passaggi in negozio."
    },
    {
      "question": "Le schede prodotto del fornitore vanno riscritte tutte?",
      "answer": "Non sempre tutte, e non subito. Si parte dalle categorie e dai prodotti che hanno più margine commerciale o più ricerche locali. Le descrizioni copiate vanno trattate come materiale grezzo: utili per dati tecnici, deboli per posizionarsi."
    },
    {
      "question": "Google Business quanto pesa per un negozio?",
      "answer": "Molto, soprattutto sulle ricerche con città, quartiere o “vicino a me”. Foto reali, prodotti, reparti, orari, post, recensioni e categorie corrette aiutano Google a capire cosa vendi e aiutano il cliente a scegliere se passare."
    },
    {
      "question": "Quanto tempo serve per vedere movimento?",
      "answer": "Dipende da sito, concorrenza locale e stato iniziale. Un profilo Google Business trascurato può muoversi prima di un sito tecnico pieno di problemi. Di solito conviene separare interventi rapidi, pulizia tecnica e lavoro sui contenuti, così ogni pezzo è misurabile."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gioielleria a"
},
  'creativita-eventi': {
  "description": "Portfolio su Instagram, video su Drive, case study sparsi e sito che Google legge male: per fotografi, videomaker, planner ed eventi questo significa perdere ricerche locali, nicchie profittevoli e lavori già caldi. La SEO qui mette ordine tecnico, contenuti e segnali locali.",
  "microStory": "Un videomaker aveva un portfolio forte ma dipendeva quasi solo da Instagram. Per “videomaker matrimonio + provincia” il sito era oltre posizione 30, perché mancavano pagine servizio, zone e dati strutturati. La SEO ha diviso matrimoni, eventi aziendali, backstage e location, con gallerie leggere e testi meno vaghi. Dopo 4 mesi la pagina matrimoni è entrata in top 6 su 3 comuni. Le richieste dal sito sono passate da 2 a 13 al mese, con date e luogo già indicati.",
  "caseStudyRef": undefined,
  "solutionTitle": "SEO per creativi che non vogliono sparire dietro Instagram",
  "problems": [
    {
      "icon": "ph-magnifying-glass",
      "title": "Ricerche rubate",
      "desc": "Chi cerca fotografo matrimonio in città finisce su portali, planner o directory. Non perché siano migliori: spesso hanno solo pagine più chiare, titoli meno confusi e segnali locali gestiti con metodo."
    },
    {
      "icon": "ph-instagram-logo",
      "title": "Portfolio disperso",
      "desc": "IG mostra il colpo d’occhio, Behance fa vetrina, Drive contiene il materiale vero. Google però non indicizza una cartella piena di lavori senza contesto, testi, servizi, luoghi e markup leggibile."
    },
    {
      "icon": "ph-code",
      "title": "Schema mancante",
      "desc": "Foto, video, eventi e servizi creativi vengono pubblicati come blocchi belli ma muti. Senza CreativeWork, Service, località e dati strutturati, il sito parla male ai motori di ricerca. Punto."
    }
  ],
  "features": [
    {
      "title": "Audit tecnico reale",
      "description": "Controllo Core Web Vitals, crawlability, indexing, errori canonici, sitemap, redirect e blocchi inutili. Niente report decorativi: solo ciò che impedisce alle pagine di essere lette e posizionate."
    },
    {
      "title": "Keyword per nicchie",
      "description": "Mappo ricerche come engagement, lifestyle, destination wedding, eventi corporate, corsi creativi e shooting locali. Ogni intento ha una pagina o un contenuto dedicato, non un calderone generico."
    },
    {
      "title": "SEO locale pulita",
      "description": "Google Business, citation, recensioni, categorie, aree servite e coerenza dei dati. Se lavori a Milano, Firenze o sul Lago di Como, Google deve capirlo senza interpretazioni creative."
    },
    {
      "title": "On-page e markup",
      "description": "Titoli, H1, testi, immagini, alt, internal link e schema CreativeWork o Service vengono sistemati per raccontare davvero cosa fai, dove lavori e per quale tipo di cliente."
    },
    {
      "title": "Monitoring mensile",
      "description": "Rank tracking, Search Console e GA4 servono a vedere cosa cresce, cosa resta fermo e quali pagine stanno portando richieste. La catena di plug-in random resta fuori dalla porta."
    }
  ],
  "faqs": [
    {
      "question": "Ho già Instagram: mi serve davvero la SEO?",
      "answer": "Instagram aiuta a mostrare stile e lavori recenti, ma non intercetta bene chi cerca un servizio specifico in una zona precisa. Se una coppia cerca un fotografo matrimonio a Verona o un video evento aziendale a Bologna, serve una pagina leggibile da Google."
    },
    {
      "question": "Devo creare una landing per ogni servizio?",
      "answer": "Non per ogni micro-variante, ma per le ricerche con intento diverso sì. Matrimonio, engagement, eventi corporate, lifestyle, corsi o viaggi fotografici non parlano allo stesso cliente. Mischiarli tutti in una pagina unica rende tutto più debole."
    },
    {
      "question": "Le immagini pesanti penalizzano il sito?",
      "answer": "Sì, se vengono caricate senza formati corretti, dimensioni ottimizzate e lazy loading ragionato. Nel settore creativo le immagini devono restare belle, ma non possono bloccare la pagina per dieci secondi."
    },
    {
      "question": "Google capisce il mio portfolio?",
      "answer": "Spesso no. Una galleria senza testo, luogo, servizio, contesto e dati strutturati è quasi muta. Ogni lavoro importante dovrebbe spiegare cosa mostra, per chi è stato fatto, in quale contesto e con quale servizio collegato."
    },
    {
      "question": "Quanto tempo serve per vedere movimento?",
      "answer": "Dipende dallo stato tecnico del sito, dalla concorrenza locale e da quante pagine utili esistono già. Prima si sistemano blocchi tecnici e pagine principali, poi si misura su query reali, non su impressioni vaghe. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "fotografo matrimonio a"
}
};
