// AUTO-GENERATED by scripts/generate-matrix-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate the relevant cell instead.
// Servizio: Sviluppo Web
// Categorie: beauty-wellness, sanita-salute, studi-professionali, casa-edilizia, auto-mobilita, food-hospitality, retail-negozi, creativita-eventi

import type { ServiceCategoryContent } from '../seo-service-content';

export const SVILUPPO_WEB_CONTENT: Record<string, ServiceCategoryContent> = {
  'beauty-wellness': {
  "description": "Nel beauty e wellness il sito non può essere una vetrina scollegata: appuntamenti, staff, trattamenti, abbonamenti e richieste da Instagram devono entrare nello stesso flusso. Se il salone lavora tra WhatsApp, quaderno e gestionale chiuso, ogni prenotazione diventa attrito.",
  "microStory": "Un salone con 5 operatori gestiva appuntamenti tra agenda cartacea, WhatsApp e note vocali. Il sito portava contatti, ma poi iniziava il caos: doppi slot, trattamenti segnati male, clienti richiamati due volte. Lo sviluppo web ha collegato richiesta online, calendario interno e notifiche, con ruoli separati per titolare e staff. Non abbiamo aggiunto l’ennesimo tool: abbiamo tolto 3 passaggi manuali. Dopo 6 settimane le sovrapposizioni sono scese da 14 a 2 al mese e il team vedeva gli stati in una sola dashboard.",
  "caseStudyRef": undefined,
  "solutionTitle": "Il salone non può girare con tre calendari e un sito finto",
  "problems": [
    {
      "icon": "ph-calendar-blank",
      "title": "Prenotazioni sparse ovunque",
      "desc": "Telefono, WhatsApp, DM Instagram e quaderno creano doppie prenotazioni, buchi in agenda e clienti richiamati a mano. Il problema non è lo staff: è un flusso digitale costruito a pezzi, senza un centro operativo chiaro."
    },
    {
      "icon": "ph-database",
      "title": "Gestionale isolato",
      "desc": "Il software del salone tiene clienti, tessere e appuntamenti, ma spesso non parla con sito, landing, campagne o social. Risultato: dati copiati a mano, errori banali e nessuna vista reale su cosa sta succedendo."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Calendario in guerra",
      "desc": "Quando quattro persone modificano turni, cabine, trattamenti e pause da strumenti diversi, il conflitto è garantito. Non serve altra confusione: serve una struttura con ruoli, permessi e regole chiare per ogni appuntamento."
    }
  ],
  "features": [
    {
      "title": "Booking aderente al lavoro",
      "description": "Prenotazioni online pensate per servizi beauty reali: durata trattamento, operatore, cabina, pausa tecnica, conferma cliente e regole diverse per taglio, colore, estetica o abbonamento palestra."
    },
    {
      "title": "Integrazioni gestionali",
      "description": "Collego sito, CRM, gestionale esistente, moduli contatto e automazioni dove ha senso farlo. Niente plug-in buttati dentro: API, flussi dati leggibili e controllo sugli errori."
    },
    {
      "title": "Area clienti riservata",
      "description": "Login per clienti, staff o iscritti con ruoli separati: appuntamenti, documenti, scadenze, pacchetti, storico trattamenti e comunicazioni senza mandare tutto in chat privata."
    },
    {
      "title": "Dashboard operative",
      "description": "Vista chiara su richieste, appuntamenti, clienti nuovi, no-show, trattamenti richiesti e canali che portano contatti. Il salone smette di lavorare alla cieca. Punto."
    },
    {
      "title": "Automazioni senza caos",
      "description": "Reminder, conferme, chatbot AI, follow-up e recupero richieste possono alleggerire lo staff, ma solo se rispettano agenda, tono del brand e tempi reali del centro."
    }
  ],
  "faqs": [
    {
      "question": "Possiamo mantenere il gestionale che usiamo già in salone?",
      "answer": "Sì, se il gestionale permette integrazioni, export o API utilizzabili. Prima si verifica cosa può comunicare e cosa no. Se è un sistema chiuso, si costruisce attorno senza fingere miracoli: moduli, sincronizzazioni controllate o procedure più pulite dove serve."
    },
    {
      "question": "Il sito può gestire appuntamenti con più operatori e cabine?",
      "answer": "Sì. Per un centro estetico o un salone non basta un calendario base: servono regole su durata, operatore, stanza, pause, servizi combinati e disponibilità reale. La logica va progettata prima, altrimenti il booking online crea solo altro lavoro allo staff."
    },
    {
      "question": "Si può collegare Instagram alle richieste di prenotazione?",
      "answer": "Instagram può portare traffico verso pagine, moduli o booking dedicati, ma non deve restare l’unico punto di raccolta. L’obiettivo è trasformare DM e clic in richieste tracciate, con nome, servizio, orario e stato chiaro per chi lavora in salone."
    },
    {
      "question": "Serve per forza rifare tutto il sito?",
      "answer": "Non sempre. Se il sito attuale è sano, si può intervenire su booking, area clienti, integrazioni o performance. Se invece è un template lento, pieno di plug-in e difficile da modificare, rattopparlo può costare più fatica che ricostruire bene."
    },
    {
      "question": "Le automazioni rischiano di sembrare fredde con i clienti?",
      "answer": "Solo se vengono scritte male e piazzate ovunque. Reminder, conferme e chatbot devono usare il linguaggio del centro, lasciare spazio al contatto umano e togliere lavoro ripetitivo, non sostituire la relazione con il cliente. Decidi tu."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "prenotare parrucchiere a"
},
  'sanita-salute': {
  "description": "Per uno studio sanitario, il sito non può essere una brochure staccata da agenda, consenso, ruoli e cartelle. Serve uno sviluppo web sobrio, conforme alle regole deontologiche e collegato ai flussi reali: disponibilità, richieste, accessi riservati, dati protetti e tempi di risposta chiari.",
  "microStory": "Uno studio fisioterapico riceveva richieste da sito, telefono e WhatsApp, poi la segreteria ricopiava tutto in un foglio. Ogni nuovo paziente richiedeva anamnesi, consenso, disponibilità e note terapista. Lo sviluppo web ha creato un’area richiesta con campi guidati, documenti caricati e stato pratica visibile allo staff. I dati entrano una volta sola e restano tracciati. In 2 mesi il tempo di apertura pratica è sceso da 12 a 4 minuti, senza toccare informazioni cliniche non necessarie.",
  "caseStudyRef": undefined,
  "solutionTitle": "Basta sito-vetrina: lo studio sanitario ha bisogno di codice serio",
  "problems": [
    {
      "icon": "ph-calendar-blank",
      "title": "Agenda fuori controllo",
      "desc": "Carta, Excel e telefonate continue creano doppi appuntamenti, buchi in agenda e segreteria sotto pressione. Il paziente vuole sapere quando può venire, non aspettare tre richiamate per una visita o una seduta."
    },
    {
      "icon": "ph-database",
      "title": "Dati scollegati ovunque",
      "desc": "Il sito dice una cosa, il gestionale ne contiene un'altra, le cartelle cliniche stanno in un terzo posto. Risultato: passaggi manuali, errori evitabili e nessuna vista chiara su richieste, accessi e storico paziente."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Template da agenzia",
      "desc": "Un dentista, uno psicologo o un fisioterapista non possono comunicare come una palestra qualsiasi. Template generici, plug-in random e copy urlato rischiano di stonare con fiducia, privacy e regole deontologiche."
    }
  ],
  "features": [
    {
      "title": "Agenda online integrata",
      "description": "Disponibilità, richieste e conferme entrano in un flusso controllato. La segreteria decide cosa automatizzare e cosa validare a mano, senza lasciare lo studio in balia del calendario pubblico."
    },
    {
      "title": "Area pazienti riservata",
      "description": "Login, ruoli e permessi per documenti, comunicazioni, referti o materiali post-visita. Ogni accesso viene pensato per ridurre chiamate inutili e proteggere dati sensibili."
    },
    {
      "title": "Integrazioni con gestionali",
      "description": "API verso CRM, ERP, software clinici o strumenti già presenti in studio. Niente doppio inserimento quando il dato può passare in modo ordinato tra sistemi."
    },
    {
      "title": "Automazioni senza caos",
      "description": "Reminder, messaggi pre-visita, chatbot AI e richieste ricorrenti possono essere gestiti con regole chiare. Automazione utile, non bot invadenti che trattano un paziente come lead qualunque."
    },
    {
      "title": "Performance da portale moderno",
      "description": "Caricamenti rapidi, interfacce pulite, codice mantenibile e monitoraggio degli errori. Un portale sanitario lento o fragile non sembra prudente. Punto."
    }
  ],
  "faqs": [
    {
      "question": "Posso collegare il sito al gestionale che uso già in studio?",
      "answer": "Sì, se il gestionale espone API, esportazioni o un punto di integrazione documentato. Prima si verifica cosa permette davvero il software, poi si progetta il flusso: appuntamenti, anagrafiche, richieste, documenti o notifiche. Niente promesse vaghe prima di vedere il sistema."
    },
    {
      "question": "Un portale pazienti è adatto anche a uno studio piccolo?",
      "answer": "Dipende dal carico operativo. Se i pazienti chiamano spesso per orari, documenti, indicazioni o richieste ripetitive, un portale può togliere rumore alla segreteria. Se invece il flusso è minimo, meglio partire da agenda e moduli ben fatti."
    },
    {
      "question": "Come si gestisce la privacy dei dati sanitari?",
      "answer": "Con accessi separati, permessi stretti, log dove servono, dati ridotti al necessario e testi chiari su consenso e trattamento. Lo sviluppo tecnico non sostituisce il consulente privacy, ma deve rispettare fin dall'inizio il tipo di dato trattato."
    },
    {
      "question": "Il sito può mostrare disponibilità senza aprire tutta l'agenda?",
      "answer": "Sì. Si possono esporre solo fasce, tipologie di visita o slot filtrati, lasciando allo studio il controllo finale. Per sanità e salute, l'automazione cieca è spesso un problema: meglio mostrare abbastanza per ridurre chiamate, non tutto."
    },
    {
      "question": "Si può evitare l'effetto sito sanitario finto e impersonale?",
      "answer": "Sì, lavorando su contenuti sobri, pagine per prestazione, percorsi chiari e microcopy rispettoso. Un paziente cerca fiducia, competenza leggibile e istruzioni concrete. Non slogan da agenzia, non grafiche mediche riciclate, non promesse fuori tono."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gestionale studio medico"
},
  'studi-professionali': {
  "description": "Per uno studio professionale, il sito non basta quando pratiche, documenti e richieste restano sparse tra email, telefonate e cartelle condivise. Lo sviluppo web serve a mettere ordine: area clienti, ruoli, upload, stato pratica, integrazioni con CRM o gestionali già in uso.",
  "microStory": "Uno studio di consulenza gestiva pratiche con email, cartelle Drive e un file Excel chiamato “aggiornato_finale”. I clienti chiedevano stato lavori ogni settimana perché non vedevano avanzamenti. Lo sviluppo web ha portato login cliente, checklist pratica, upload documenti e notifiche automatiche in un unico flusso. Ogni pratica ha responsabile, scadenza e stato. Dopo 90 giorni le email “a che punto siamo?” sono calate del 41% e il team ha smesso di cercare allegati in 4 posti diversi.",
  "caseStudyRef": undefined,
  "solutionTitle": "Basta studi professionali ostaggio di email e template",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Pratiche senza traccia",
      "desc": "Documenti inviati via email, versioni duplicate, allegati persi e nessuno storico chiaro. Per avvocati, commercialisti e notai diventa un archivio fragile, dove ogni controllo richiede tempo e memoria umana."
    },
    {
      "icon": "ph-clock",
      "title": "Telefonate di stato",
      "desc": "Il cliente chiama per sapere se manca un documento, se la pratica è ferma o se qualcuno ha letto la sua richiesta. Non è colpa sua: manca un punto unico dove vedere cosa sta succedendo."
    },
    {
      "icon": "ph-lock",
      "title": "Area clienti assente",
      "desc": "Senza login, ruoli e permessi, upload e download restano affidati a link, email e cartelle improvvisate. Il risultato è una catena di passaggi manuali che rallenta lo studio e aumenta il rischio di errore."
    }
  ],
  "features": [
    {
      "title": "Area clienti riservata",
      "description": "Portale con login, ruoli e permessi per clienti, collaboratori e segreteria. Ogni persona vede solo pratiche, documenti e azioni che le competono."
    },
    {
      "title": "Upload documenti tracciato",
      "description": "Caricamento file guidato, stato dei documenti, note interne e storico delle modifiche. Meno allegati in inbox, meno richieste ripetute, più controllo operativo."
    },
    {
      "title": "Dashboard per pratiche",
      "description": "Vista chiara su scadenze, avanzamento, documenti mancanti e attività aperte. Utile per studi legali, commercialisti, architetti e realtà immobiliari con molte pratiche attive."
    },
    {
      "title": "Integrazioni con gestionali",
      "description": "Collegamento con CRM, ERP, software di studio o strumenti già presenti. Niente doppio inserimento dati quando un flusso può parlare con l'altro via API."
    },
    {
      "title": "Automazioni e AI",
      "description": "Promemoria, notifiche, chatbot per richieste frequenti e raccolta dati preliminare. Non sostituisce lo studio: toglie dalla scrivania le domande ripetitive."
    }
  ],
  "faqs": [
    {
      "question": "Possiamo mantenere il gestionale che usiamo già in studio?",
      "answer": "Sì, se il gestionale espone API, esportazioni affidabili o modalità di integrazione documentate. Prima si controlla cosa permette davvero, poi si decide come collegarlo al portale. Forzare tutto dentro uno strumento nuovo spesso crea più caos di quello che risolve."
    },
    {
      "question": "L'area clienti può gestire documenti riservati?",
      "answer": "Sì, va progettata con login, ruoli, permessi, log e regole chiare su chi può vedere, caricare o scaricare ogni file. Per studi professionali non basta una pagina protetta da password: serve una struttura coerente con pratiche, clienti e responsabilità interne."
    },
    {
      "question": "Serve rifare anche il sito pubblico dello studio?",
      "answer": "Non sempre. Se il sito porta contatti e comunica bene lo studio, si può lavorare solo sul portale o sulla web app. Se invece è un template lento, confuso e scollegato dai flussi reali, conviene intervenire anche lì. Punto."
    },
    {
      "question": "Quanto tempo richiede un portale per clienti e pratiche?",
      "answer": "Dipende da ruoli, quantità di flussi, integrazioni e documenti da gestire. Un portale semplice è diverso da una web app con dashboard, notifiche, API e permessi granulari. Prima si mappa il lavoro dello studio, poi si definisce una roadmap sensata."
    },
    {
      "question": "I clienti sapranno usarlo senza chiamare lo studio?",
      "answer": "Se il portale è costruito sul modo in cui il cliente ragiona, sì. Stato pratica, documenti mancanti, upload e messaggi devono essere immediati. Se sembra un gestionale travestito da sito, torneranno a telefonare. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "studio legale a"
},
  'casa-edilizia': {
  "description": "Per idraulici, elettricisti, fabbri e imprese edili il sito vetrina non basta: servono portali, dashboard e automazioni che tengano insieme richieste urgenti, ordini, pratiche, foto cantiere e stato lavori. La catena agenzia-plugin-template qui fa solo rumore operativo.",
  "microStory": "Un’impresa edile seguiva cantieri con foto WhatsApp, preventivi in PDF e avanzamenti in chat. Quando serviva ricostruire una decisione, nessuno trovava il punto giusto. Lo sviluppo web ha creato un portale cantiere con foto per fase, note tecniche, documenti e stato lavori. Il cliente vede cosa è approvato, cosa manca e cosa è in attesa. In 3 mesi 18 cantieri sono stati spostati nel portale e le richieste di aggiornamento manuale sono scese da 60 a 21 al mese.",
  "caseStudyRef": undefined,
  "solutionTitle": "Edilizia senza portali improvvisati e plugin a caso",
  "problems": [
    {
      "icon": "ph-receipt",
      "title": "Documenti tutti diversi",
      "desc": "Word, PDF copiati, note sparse e versioni mandate in chat creano confusione prima ancora del cantiere. Ogni richiesta diventa una ricostruzione manuale: materiali, metrature, sopralluoghi, allegati, firme e condizioni cambiano formato a ogni giro."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Cantiere senza riferimento",
      "desc": "La squadra arriva sul posto e cerca ordini, foto, schede tecniche e pratiche tra messaggi vecchi. Il lavoro rallenta non per mancanza di mestiere, ma perché le informazioni operative sono finite in troppi posti. Punto."
    },
    {
      "icon": "ph-clock",
      "title": "Stato lavori al telefono",
      "desc": "Il cliente chiama per sapere se il serramento è arrivato, se l'impianto è stato chiuso o se manca un documento. Senza dashboard, ogni aggiornamento passa da una persona già occupata a gestire urgenze vere."
    }
  ],
  "features": [
    {
      "title": "Portale cantieri con ruoli",
      "description": "Accessi separati per ufficio, tecnici, squadra e cliente finale. Ognuno vede solo ordini, pratiche, foto, documenti e stati utili al proprio lavoro."
    },
    {
      "title": "Dashboard stato lavori",
      "description": "Avanzamento, attività aperte, allegati mancanti e note tecniche in un'unica vista. Meno chiamate di controllo, più informazioni verificabili."
    },
    {
      "title": "Documenti uniformi",
      "description": "Schede intervento, computi, ordini materiali e riepiloghi cliente generati da dati strutturati. Basta file clonati male e versioni non allineate."
    },
    {
      "title": "Integrazioni con gestionali",
      "description": "Collegamento con CRM, ERP o software già usati in ufficio, senza rifare tutto da zero. Le API servono a togliere doppio inserimento, non a fare scena."
    },
    {
      "title": "Automazioni per urgenze",
      "description": "Richieste tipo idraulico urgente, guasto elettrico o apertura porta possono entrare in flussi ordinati: triage, assegnazione, notifiche, storico e priorità."
    }
  ],
  "faqs": [
    {
      "question": "Possiamo tenere il gestionale che usiamo già in ufficio?",
      "answer": "Sì, se il gestionale espone API, esportazioni affidabili o un database raggiungibile in modo pulito. Prima si verifica come entrano e escono i dati: clienti, cantieri, ordini, materiali e stati. Poi si decide cosa collegare e cosa lasciare dov'è."
    },
    {
      "question": "Serve davvero un'area cliente per un'impresa edile?",
      "answer": "Serve quando il cliente continua a chiamare per chiedere documenti, foto, avanzamento, consegne o pratiche. Un'area riservata non sostituisce il rapporto umano: toglie dal telefono le domande ripetitive e lascia traccia di ciò che è stato condiviso."
    },
    {
      "question": "Le squadre in cantiere possono usarla dal telefono?",
      "answer": "Devono poterla usare dal telefono, altrimenti resta un giocattolo da ufficio. Interfacce rapide, pulsanti chiari, foto caricate dal posto, note vocali o campi essenziali. In cantiere non c'è tempo per pannelli pieni di fronzoli."
    },
    {
      "question": "Possiamo gestire richieste urgenti dal sito?",
      "answer": "Sì, ma vanno filtrate bene. Una richiesta urgente deve raccogliere zona, tipo di problema, foto, disponibilità e contatto, poi finire nel flusso giusto. Il modulo generico con tre campi è il modo migliore per perdere tempo."
    },
    {
      "question": "Cosa succede ai lavori già fatti e alle foto portfolio?",
      "answer": "Si possono organizzare per tipologia, comune, intervento, materiale e stato. Per un serramentista o un fabbro, il portfolio non è decorazione: è prova concreta. Va caricato in modo ordinato, veloce e riutilizzabile anche nelle pagine locali."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gestionale per idraulico"
},
  'auto-mobilita': {
  "description": "Officine, carrozzieri, gommisti, autoscuole e concessionarie perdono tempo quando appuntamenti, richiami, pratiche e storico interventi stanno tra carta, WhatsApp, Excel e gestionali chiusi. Il risultato: doppie prenotazioni, clienti non richiamati, accettazione lenta e zero controllo reale sui flussi.",
  "microStory": "Un’officina con revisione, gomme e carrozzeria aveva dati cliente sparsi tra gestionale, WhatsApp e fogli per appuntamenti. Ogni ritorno in officina ripartiva da domande già fatte. Lo sviluppo web ha creato una dashboard interna con veicolo, interventi, foto danno, ricambi e prossima scadenza. Non sostituisce il gestionale: lo affianca dove il gestionale non copre il processo reale. Dopo 8 settimane il tempo medio per preparare una pratica è sceso da 16 a 7 minuti.",
  "caseStudyRef": undefined,
  "solutionTitle": "Web app per officine senza agenzie a 6 mani",
  "problems": [
    {
      "icon": "ph-calendar-blank",
      "title": "Agenda fuori controllo",
      "desc": "Quando tagliandi, cambi gomme e revisioni passano da telefono, fogli e chat, basta una distrazione per creare due appuntamenti sulla stessa baia. Il cliente arriva, l’auto resta ferma, il banco accettazione assorbe il danno."
    },
    {
      "icon": "ph-database",
      "title": "Storico interventi sparso",
      "desc": "Schede cliente, ricambi montati, chilometraggio, foto danno e note del meccanico finiscono in posti diversi. Alla visita successiva nessuno ha il quadro intero e si ricomincia da domande già fatte."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Follow-up mai partiti",
      "desc": "Dopo tagliando, cambio gomme o diagnosi, il richiamo resta nella testa di qualcuno. Se quella persona è impegnata, il cliente non torna, la recensione non arriva e il lavoro successivo se lo prende chi lo intercetta prima."
    }
  ],
  "features": [
    {
      "title": "Gestionale web custom",
      "description": "Agenda officina, stato lavorazioni, schede veicolo e storico cliente in un’unica web app, costruita sul modo reale in cui lavori al banco e in reparto."
    },
    {
      "title": "Portale clienti riservato",
      "description": "Login per vedere appuntamenti, documenti, foto intervento, scadenze e comunicazioni. Utile per flotte, aziende, autoscuole e clienti ricorrenti che chiedono ordine."
    },
    {
      "title": "Integrazioni con sistemi esistenti",
      "description": "Collegamenti con CRM, ERP, software ricambi, fatturazione, calendari e strumenti già in uso. Niente doppio inserimento solo perché due piattaforme non si parlano."
    },
    {
      "title": "Automazioni post-intervento",
      "description": "Messaggi automatici per promemoria tagliando, cambio gomme stagionale, revisione, ritiro veicolo e richiesta recensione. Non serve ricordarsi tutto a mano."
    },
    {
      "title": "Dashboard operative rapide",
      "description": "Prenotazioni, tempi medi, lavorazioni aperte, richiami scaduti e clienti inattivi leggibili senza report inutili. Numeri chiari per decidere cosa sistemare prima."
    }
  ],
  "faqs": [
    {
      "question": "Posso collegare la web app al gestionale che uso già in officina?",
      "answer": "Dipende dal gestionale e dalle API disponibili. Prima si verifica cosa espone davvero: clienti, veicoli, interventi, fatture, magazzino o appuntamenti. Se l’integrazione diretta non è possibile, si può valutare import controllato, esportazioni programmate o una procedura ponte senza inventare castelli fragili."
    },
    {
      "question": "Serve una web app se ho già Google Calendar e WhatsApp?",
      "answer": "Calendar e WhatsApp reggono finché il volume è basso e tutti ricordano tutto. In un’officina con più postazioni, richiami, veicoli sostitutivi e clienti ricorrenti diventano presto un collo di bottiglia. Una web app serve quando vuoi tracciare processo, stato e storico senza inseguire messaggi."
    },
    {
      "question": "I clienti possono prenotare tagliando o cambio gomme online?",
      "answer": "Sì, ma va fatto con regole sensate: durata intervento, disponibilità ponte, priorità urgenze, fasce orarie, conferma manuale o automatica. Una prenotazione online libera tempo solo se non crea caos in accettazione. Altrimenti è solo un modulo vestito bene."
    },
    {
      "question": "Si possono gestire ruoli diversi per accettazione, meccanici e amministrazione?",
      "answer": "Sì. Ruoli e permessi servono proprio a evitare che tutti vedano o modifichino tutto. Il banco può gestire appuntamenti e clienti, il reparto aggiornare stato e note tecniche, l’amministrazione consultare documenti e flussi. Meno accessi inutili, meno errori."
    },
    {
      "question": "Quanto tempo richiede mettere ordine negli appuntamenti dell’officina?",
      "answer": "Prima si mappa il flusso reale: telefonata, accettazione, diagnosi, lavorazione, riconsegna, richiamo. Poi si costruisce per step, partendo dal punto che crea più attrito. Di solito non conviene rifare tutto insieme: meglio togliere subito carta, doppie prenotazioni e storico disperso. Punto."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gestionale officina auto"
},
  'food-hospitality': {
  "description": "Nel food e hospitality il sito non è una brochure: deve reggere menu, foto, disponibilità, prenotazioni, camere e richieste da smartphone. Quando resta scollegato da gestionale, POS, magazzino e CRM, arrivano doppie prenotazioni, email perse e dipendenza totale da portali esterni.",
  "microStory": "Un B&B con 9 camere riceveva richieste da sito, portali e telefono, poi aggiornava disponibilità a mano. Le doppie risposte e gli errori di data consumavano tempo. Lo sviluppo web ha collegato form diretto, regole di disponibilità, email automatiche e dashboard prenotazioni leggere. Non è stato creato un gestionale mastodontico: solo il pezzo che mancava. Nel primo mese le richieste duplicate sono scese da 23 a 5 e la reception ha risparmiato circa 6 ore di controllo manuale.",
  "caseStudyRef": undefined,
  "solutionTitle": "Siti e web app per ristoranti, hotel e B&B senza catene infinite",
  "problems": [
    {
      "icon": "ph-calendar-blank",
      "title": "Prenotazioni non allineate",
      "desc": "Il tavolo risulta libero sul sito, occupato nel gestionale e confermato via telefono. Il risultato è double booking, clienti irritati e staff costretto a controllare tre schermate prima di dire sì."
    },
    {
      "icon": "ph-database",
      "title": "Dati sparsi ovunque",
      "desc": "POS, magazzino, sito, booking engine e CRM parlano lingue diverse. Menu non aggiornati, camere gestite via email, scorte invisibili online: ogni modifica diventa un giro di messaggi tra fornitori."
    },
    {
      "icon": "ph-prohibit",
      "title": "Template da catalogo",
      "desc": "Ristorante, agriturismo e hotel finiscono dentro la stessa pagina preconfezionata, con plug-in messi a caso. Il cliente da smartphone cerca foto, disponibilità e prenotazione rapida; trova lentezza, popup e form inutili."
    }
  ],
  "features": [
    {
      "title": "Sito collegato al gestionale",
      "description": "Prenotazioni, camere, richieste e contatti entrano nello stesso flusso operativo. Meno copia-incolla, meno email disperse, più controllo su tavoli, stanze e richieste reali."
    },
    {
      "title": "Portali con login e ruoli",
      "description": "Area staff, direzione, reception o clienti con permessi separati. Ogni profilo vede solo ciò che serve: disponibilità, richieste, documenti, stato prenotazione o dati operativi."
    },
    {
      "title": "Integrazioni POS e CRM",
      "description": "Collego sito, CRM, gestionali esistenti, sistemi di cassa e strumenti di marketing già in uso. L’obiettivo è togliere passaggi manuali, non aggiungere l’ennesima piattaforma da controllare."
    },
    {
      "title": "Automazioni per richieste frequenti",
      "description": "Chatbot e flussi AI possono gestire domande su menu, allergeni, orari, disponibilità e servizi. Lo staff resta libero per richieste vere, non per rispondere cento volte alla stessa domanda."
    },
    {
      "title": "Performance da servizio moderno",
      "description": "Pagine veloci, prenotazione chiara, immagini ottimizzate e struttura tecnica pulita. Se il cliente decide dal telefono, ogni secondo perso regala traffico a Booking, TripAdvisor o al concorrente."
    }
  ],
  "faqs": [
    {
      "question": "Possiamo collegare il sito al gestionale prenotazioni che usiamo già?",
      "answer": "Sì, se il gestionale espone API, webhook, export affidabili o altri canali tecnici documentati. Prima si verifica cosa permette davvero, poi si decide se collegarlo, affiancarlo o sostituire solo i pezzi che creano attrito. Niente incastri ciechi."
    },
    {
      "question": "Per un ristorante serve davvero una web app custom?",
      "answer": "Non sempre. Se devi mostrare menu, foto e form semplice, può bastare un sito ben fatto. Se invece hai prenotazioni, sale, turni, eventi, asporto, CRM e magazzino, una web app evita fogli Excel, messaggi WhatsApp e controlli manuali continui."
    },
    {
      "question": "Un hotel può ridurre la dipendenza da Booking?",
      "answer": "Sì, ma non con una pagina vetrina lenta. Servono camere chiare, foto ordinate, richiesta diretta, tracciamento, CRM collegato e processo di risposta rapido. Booking resta un canale, non deve diventare l’unico modo per ricevere clienti."
    },
    {
      "question": "Cosa succede alle prenotazioni arrivate via email?",
      "answer": "Si può creare un flusso che le porta dentro CRM o dashboard, con stato, note, provenienza e assegnazione. Così reception e direzione non cercano conferme in caselle diverse mentre il cliente aspetta una risposta."
    },
    {
      "question": "Possiamo mantenere foto, menu e contenuti aggiornabili dallo staff?",
      "answer": "Sì. Si può prevedere un pannello semplice per modificare piatti, camere, servizi, immagini, allergeni, orari e contenuti stagionali. La parte critica è decidere chi può cambiare cosa, così il sito non diventa un archivio disordinato."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "ristorante a"
},
  'retail-negozi': {
  "description": "Per un negozio fisico, il web non deve fingere di sostituire il banco: deve mostrare cosa c’è, tenere allineati magazzino, POS e clienti, togliere Excel dal retrobottega e dare dati veri su fidelity, richieste e disponibilità prima che la persona entri in negozio.",
  "microStory": "Un negozio con cassa fisica e catalogo online aggiornava stock a fine giornata, quando molti prodotti erano già cambiati. I clienti chiedevano disponibilità e lo staff controllava a mano. Lo sviluppo web ha collegato database prodotti, disponibilità indicativa, richiesta ritiro e dashboard per aggiornamenti rapidi. Il sito non promette stock perfetto quando il dato non lo è: mostra informazioni utili e chiede conferma dove serve. Dopo 45 giorni le richieste senza dati prodotto sono calate del 52%.",
  "caseStudyRef": undefined,
  "solutionTitle": "Retail online senza circo di plug-in e agenzie a sei mani",
  "problems": [
    {
      "icon": "ph-receipt",
      "title": "Fidelity ancora cartacea",
      "desc": "Tessere timbrate, sconti segnati a mano, clienti persi tra cassa e quaderni. Così un negozio di abbigliamento non sa chi torna, cosa compra, quando ricontattarlo e quali promozioni stanno solo bruciando margine."
    },
    {
      "icon": "ph-database",
      "title": "Magazzino fuori controllo",
      "desc": "Excel dice una cosa, il POS un’altra, lo scaffale un’altra ancora. In una libreria o ferramenta questo diventa tempo perso al telefono, articoli promessi e poi mancanti, ordini doppi e personale costretto a rincorrere dati rotti."
    },
    {
      "icon": "ph-prohibit",
      "title": "Disponibilità invisibile online",
      "desc": "Il cliente cerca un modello, un mazzo, un anello o una lampada, ma prima di uscire non capisce se c’è davvero. Il sito-vetrina bello ma muto scarica tutto sul telefono e sul personale in negozio."
    }
  ],
  "features": [
    {
      "title": "Portale clienti con login",
      "description": "Area riservata per punti fidelity, storico acquisti, preferenze, richieste e notifiche. Non un account finto: uno spazio utile per chi compra spesso e per chi gestisce il rapporto dopo la vendita."
    },
    {
      "title": "Magazzino connesso al POS",
      "description": "Integrazione tra disponibilità, categorie, varianti, taglie, colori e stato reale degli articoli. Meno copia-incolla, meno file duplicati, meno risposte inventate al cliente che chiede se un prodotto è presente."
    },
    {
      "title": "Dashboard per il negozio",
      "description": "Pannello chiaro per leggere vendite, richieste online, prodotti più cercati, clienti ricorrenti e giacenze critiche. I numeri servono al banco, non a riempire report da riunione."
    },
    {
      "title": "API con gestionali esistenti",
      "description": "Collegamenti puliti con CRM, ERP, cassa, newsletter o cataloghi già in uso. Se un sistema esiste già e regge il lavoro, si integra. Non si butta tutto per moda tecnica."
    },
    {
      "title": "Automazioni senza fuffa",
      "description": "Chatbot e flussi AI per domande ripetitive: orari, disponibilità, ritiro in negozio, richiesta regalo, stato ordine. Devono alleggerire il personale, non diventare un distributore automatico di risposte vaghe."
    }
  ],
  "faqs": [
    {
      "question": "Posso mostrare online solo i prodotti disponibili in negozio?",
      "answer": "Sì, se il magazzino viene collegato a una fonte attendibile: POS, gestionale o database centrale. Per un negozio fisico ha senso mostrare disponibilità, varianti e ritiro in sede senza promettere ecommerce pieno quando non serve. Prima si mette ordine nel dato, poi si pubblica."
    },
    {
      "question": "Serve rifare il gestionale che uso già in negozio?",
      "answer": "Non per forza. Se il gestionale attuale lavora bene su cassa, articoli o clienti, si può collegare tramite API, esportazioni controllate o sincronizzazioni pianificate. Il punto è evitare doppio inserimento e dati discordanti, non cambiare software per principio."
    },
    {
      "question": "Una fidelity digitale è utile anche senza ecommerce?",
      "answer": "Sì. In un negozio fisico la fidelity digitale serve a capire ritorni, categorie acquistate, compleanni, preferenze e campagne locali. Non sostituisce il rapporto al banco: lo rende meno cieco. La carta timbrata non racconta niente. Punto."
    },
    {
      "question": "Il cliente può controllare taglie, colori o articoli prima di venire?",
      "answer": "Sì, con un catalogo collegato alle disponibilità reali o aggiornate a intervalli sensati. Per abbigliamento, gioielli, fiori o arredamento questo riduce telefonate inutili e viaggi a vuoto. Bisogna però dichiarare bene tempi di aggiornamento e regole di prenotazione."
    },
    {
      "question": "Posso partire da una singola parte, tipo magazzino o area clienti?",
      "answer": "Sì. Spesso conviene iniziare dal nodo che crea più caos: Excel, fidelity, disponibilità o richieste online. Si progetta una base tecnica che non blocchi gli step successivi. Niente castelli enormi, niente plug-in buttati lì. Decidi tu."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "disponibilità in negozio"
},
  'creativita-eventi': {
  "description": "Per fotografi, videomaker e organizzatori eventi, il sito non basta quando calendario, brief, materiali e consegne vivono tra Instagram, Drive, mail e chat. Lo sviluppo web serve a creare portali, dashboard e flussi privati che tengono insieme cliente, produzione e consegna senza agenzie a 6 mani.",
  "microStory": "Un organizzatore eventi gestiva fornitori, scalette e conferme in fogli separati. A 48 ore dall’evento arrivavano modifiche su chat diverse e qualcuno restava fuori dall’aggiornamento. Lo sviluppo web ha messo timeline, task, file tecnici, stato conferme e notifiche in una dashboard condivisa. Ogni ruolo vede solo ciò che serve. Su 12 eventi gestiti nel nuovo flusso, le modifiche non tracciate sono scese quasi a zero e il responsabile non ha più dovuto ricostruire decisioni dalle chat.",
  "caseStudyRef": undefined,
  "solutionTitle": "Web app per eventi senza fornitori in catena",
  "problems": [
    {
      "icon": "ph-calendar-blank",
      "title": "Calendari fuori controllo",
      "desc": "Disponibilità, sopralluoghi, shooting e call finiscono tra Google Calendar, messaggi e mail. Basta un cambio data per aprire una catena infinita di conferme, screenshot e promemoria manuali. Il problema non è il calendario: è il sistema attorno."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Brief dispersi in mail",
      "desc": "Il cliente manda moodboard, nomi, orari, location e referenze in momenti diversi. Tu ricostruisci tutto a mano prima dell’evento o del servizio fotografico. Ogni dettaglio non strutturato diventa un rischio operativo, soprattutto quando il team cresce."
    },
    {
      "icon": "ph-database",
      "title": "Gallerie senza identità",
      "desc": "Drive va bene per spostare file, non per presentare un lavoro visivo. Link anonimi, cartelle confuse, permessi da sistemare e nessun percorso chiaro per selezioni, revisioni o consegne finali. Il risultato sembra provvisorio anche quando il lavoro è curato."
    }
  ],
  "features": [
    {
      "title": "Area clienti con ruoli",
      "description": "Portale privato per cliente, staff e collaboratori, con accessi separati, materiali visibili solo a chi deve vederli, stato avanzamento e consegne ordinate per evento, shooting o progetto."
    },
    {
      "title": "Calendario disponibilità reale",
      "description": "Disponibilità, prenotazioni, sopralluoghi e appuntamenti raccolti in un flusso unico, collegabile a strumenti già usati. Meno incastri manuali, meno mail ripetute, più controllo sulle date critiche."
    },
    {
      "title": "Brief cliente strutturati",
      "description": "Questionari, moodboard, allegati, location, scalette e contatti raccolti dentro una procedura chiara. Il cliente compila una volta, tu lavori su dati ordinati invece che su messaggi sparsi."
    },
    {
      "title": "API per strumenti esistenti",
      "description": "Integrazioni con CRM, gestionali, newsletter, sistemi di pagamento o archivi interni. Non si butta via ciò che già usi: si collega solo quello che oggi ti costringe a fare copia e incolla."
    },
    {
      "title": "Automazioni operative AI",
      "description": "Chatbot, reminder, riepiloghi brief, smistamento richieste e notifiche interne. L’AI resta dove serve: nella parte ripetitiva, non nella direzione creativa del lavoro."
    }
  ],
  "faqs": [
    {
      "question": "Posso collegare il portale ai calendari che uso già?",
      "answer": "Sì, se gli strumenti espongono API o integrazioni utilizzabili. Prima si mappa come gestisci date, opzioni, conferme e blocchi temporanei. Poi si decide cosa sincronizzare e cosa tenere separato, così non trasformiamo il calendario in un’altra fonte di caos."
    },
    {
      "question": "Serve rifare anche il mio sito portfolio?",
      "answer": "Non per forza. Se il portfolio comunica bene, si può costruire un’area privata o una web app separata per clienti, brief e consegne. Se invece il sito è un template lento con sezioni inutili, conviene intervenire anche lì. Punto."
    },
    {
      "question": "Le gallerie private possono sostituire Drive?",
      "answer": "Possono sostituirlo nella parte visibile al cliente: selezioni, download, revisioni, preferiti, scadenze e materiali finali. Drive può restare come archivio tecnico interno, ma il cliente non deve per forza vedere cartelle anonime e permessi improvvisati."
    },
    {
      "question": "Come gestiamo brief diversi per matrimonio, video o corso?",
      "answer": "Si costruiscono flussi diversi per tipo di servizio: wedding, shooting corporate, evento live, corso o viaggio. Ogni flusso chiede solo le informazioni necessarie, con campi obbligatori, allegati e riepiloghi. Niente modulo unico gigante che nessuno compila bene."
    },
    {
      "question": "Posso partire da un processo piccolo e ampliarlo dopo?",
      "answer": "Sì. Ha senso iniziare dal punto che oggi brucia più tempo: calendario, brief, area clienti o consegne. Poi si aggiungono integrazioni, automazioni e ruoli quando il processo è chiaro. Prima ordine operativo, poi codice. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gestionale eventi per"
}
};
