// AUTO-GENERATED by scripts/generate-matrix-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate the relevant cell instead.
// Servizio: Web Design
// Categorie: beauty-wellness, sanita-salute, studi-professionali, casa-edilizia, auto-mobilita, food-hospitality, retail-negozi, creativita-eventi

import type { ServiceCategoryContent } from '../seo-service-content';

export const WEB_DESIGN_CONTENT: Record<string, ServiceCategoryContent> = {
  'beauty-wellness': {
  "description": "Nel beauty il sito non è una brochure: è il punto in cui una persona decide se fidarsi del salone, controllare i trattamenti e prenotare. Se sembra copiato, vive solo di feed Instagram o sparisce su Google, perdi appuntamenti prima ancora del primo messaggio.",
  "microStory": "Per un salone a Frosinone il vecchio sito chiedeva 3 minuti e 40 secondi per arrivare alla prenotazione: menu confuso, form nascosto, telefono solo nel footer. Nel nuovo web design abbiamo portato trattamento, prezzo indicativo, orario e WhatsApp nello stesso percorso mobile. Il tempo medio per contattare il salone è sceso sotto i 30 secondi. In 2 mesi le prenotazioni arrivate dal sito sono passate da 2 a 18 al mese, senza cambiare Instagram.",
  "caseStudyRef": undefined,
  "solutionTitle": "Sito beauty senza template, senza staffette, senza fumo",
  "problems": [
    {
      "icon": "ph-prohibit",
      "title": "Template da salone clone",
      "desc": "Il sito sembra uguale a quello del centro estetico accanto: stessi blocchi, stesse foto finte, stessa aria da pacchetto comprato. Il cliente non capisce perché scegliere te. Punto."
    },
    {
      "icon": "ph-instagram-logo",
      "title": "Instagram è affitto. Il sito è proprietà.",
      "desc": "L'algoritmo cambia ogni 6 mesi, l'account può essere sospeso senza preavviso, la reach decresce. Le foto dei lavori restano nel feed, ma il sito non racconta tagli, trattamenti, metodo, ambiente e prenotazione. Chi arriva da Google trova una vetrina povera e torna indietro."
    },
    {
      "icon": "ph-magnifying-glass",
      "title": "Google ti ignora",
      "desc": "Il sito esiste, ma non intercetta ricerche locali tipo estetista, barbiere o palestra in zona. Pagine leggere, titoli deboli, mappe assenti: la visibilità resta al concorrente meglio organizzato."
    }
  ],
  "features": [
    {
      "title": "Sito cucito sul brand",
      "description": "Struttura, testi e layout pensati per salone, centro estetico o palestra: niente blocchi riciclati, niente estetica da catalogo, niente catena di fornitori che sporca tutto."
    },
    {
      "title": "Pagine servizi chiare",
      "description": "Ogni trattamento o servizio ha spazio, ordine e parole comprensibili. Chi cerca colore, epilazione, barberia o corsi trova subito cosa fai e come contattarti."
    },
    {
      "title": "Galleria lavori sensata",
      "description": "Le foto migliori vengono organizzate per far capire stile, resa visiva e ambiente. Instagram resta utile, ma il sito smette di essere un parcheggio vuoto."
    },
    {
      "title": "SEO locale di base",
      "description": "Titoli, testi, struttura tecnica e Google Business Profile vengono messi in ordine per ricerche locali. Non magia: pulizia, coerenza e segnali giusti."
    },
    {
      "title": "Contatto senza attrito",
      "description": "Form, WhatsApp, mappa e informazioni essenziali sono dove servono. Il cliente non deve cacciare numero, indirizzo o orari in mezzo al caos."
    }
  ],
  "faqs": [
    {
      "question": "Per un salone serve davvero un sito se ho già Instagram?",
      "answer": "Sì. Instagram è affitto, il sito è proprietà. L'algoritmo cambia, l'account può essere sospeso, la reach decresce. Il sito è asset che capitalizzi: paghi una volta, lo possiedi, lo controlli. E lavora sulle ricerche intenzionali — parrucchiere vicino, centro estetico in zona, palestra con corsi — quindi su persone già più vicine alla scelta."
    },
    {
      "question": "Posso usare le foto che ho già pubblicato sui social?",
      "answer": "Sì. Il sito è dove le foto smettono di scrollare via dopo 48 ore. Vanno selezionate, ordinate e inserite in una pagina che racconta il lavoro, non buttate dentro una griglia casuale. Meglio poche immagini forti che cinquanta scatti confusi."
    },
    {
      "question": "Il sito può aiutare a ricevere più appuntamenti?",
      "answer": "Può ridurre gli ostacoli: servizi chiari, posizione visibile, pulsante WhatsApp, form semplice, pagine leggibili da telefono. Non forza nessuno a prenotare, ma evita che una persona interessata si perda prima di scriverti."
    },
    {
      "question": "Devo mettere tutti i trattamenti nel sito?",
      "answer": "Conviene dare spazio ai servizi più cercati e redditizi, poi organizzare il resto in modo leggibile. Un elenco infinito non aiuta. Una struttura chiara per categorie aiuta il cliente a capire e Google a leggere meglio."
    },
    {
      "question": "Quanto tempo serve per rifare il sito di un centro beauty?",
      "answer": "Dipende da materiali, numero di pagine, foto disponibili e ordine dei contenuti. Prima si chiariscono servizi, zone servite, contatti e immagini. Poi il lavoro procede senza rimbalzi inutili tra grafico, tecnico e copywriter."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "centro estetico a"
},
  'sanita-salute': {
  "description": "Uno studio sanitario non può presentarsi online con pagine vecchie, testi incomprensibili e moduli rotti. Il paziente cerca fiducia prima di chiamare: trattamenti chiari, regole deontologiche rispettate, mappa, contatto rapido e nessuna catena di fornitori che diluisce responsabilità.",
  "microStory": "Per uno studio dentistico in provincia il sito aveva 11 pagine quasi uguali e un modulo da 7 campi che da mobile sembrava un questionario. Abbiamo rifatto il web design intorno a tre azioni: capire le prestazioni, trovare lo studio, chiedere appuntamento. Ogni trattamento ha una pagina leggibile, senza promesse mediche fuori tono. Il form è sceso a 3 campi e la mappa è entrata sopra la piega mobile. Le richieste mensili dal sito sono passate da 6 a 24.",
  "caseStudyRef": undefined,
  "solutionTitle": "Siti sanitari chiari, senza template da ambulatorio qualunque",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Sito che respinge",
      "desc": "Un sito fermo a dieci anni fa fa sembrare lo studio meno curato di quanto sia davvero. Il problema non è l'estetica fine a sé stessa: è la fiducia che si perde prima della prima telefonata."
    },
    {
      "icon": "ph-calendar-blank",
      "title": "Appuntamenti poco fluidi",
      "desc": "Se il paziente deve cercare il numero, copiare l'indirizzo e aspettare una risposta vaga, spesso rimanda. Form, WhatsApp e mappa devono essere facili da trovare, anche da mobile, senza percorsi inutili."
    },
    {
      "icon": "ph-brain",
      "title": "Testi troppo clinici",
      "desc": "Le pagine sui trattamenti scritte solo in gergo medico non aiutano chi ha dolore, ansia o urgenza. Serve chiarezza: cosa trattate, quando ha senso chiamare, cosa aspettarsi. Punto."
    }
  ],
  "features": [
    {
      "title": "Design sanitario mirato",
      "description": "Struttura costruita sullo studio, sulle prestazioni e sul modo reale in cui i pazienti cercano informazioni. Niente tema riciclato da clinica anonima."
    },
    {
      "title": "Pagine trattamenti leggibili",
      "description": "Contenuti ordinati per sintomi, servizi e domande frequenti, con linguaggio comprensibile e attenzione alle regole deontologiche del settore sanitario."
    },
    {
      "title": "SEO tecnica base",
      "description": "Titoli, meta, struttura URL, performance e markup locale impostati per farsi leggere bene da Google quando il paziente cerca uno studio nella zona."
    },
    {
      "title": "Google Business e mappe",
      "description": "Profilo Google Business collegato al sito, indicazioni chiare, indirizzo coerente e mappa integrata per ridurre attriti tra ricerca, visita e contatto."
    },
    {
      "title": "GDPR e contatti puliti",
      "description": "Privacy, cookie, form contatto e pulsante WhatsApp impostati con criterio, senza plug-in random accumulati solo perché qualcuno li ha installati anni fa."
    }
  ],
  "faqs": [
    {
      "question": "Il sito di uno studio medico può parlare liberamente dei trattamenti?",
      "answer": "Può parlarne, ma con attenzione. I testi devono informare senza promettere risultati, senza toni sensazionalistici e senza forzature commerciali. Per dentisti, psicologi, fisioterapisti, veterinari e medici, il confine tra chiarezza e comunicazione scorretta va rispettato fin dalla scrittura delle pagine."
    },
    {
      "question": "Posso aggiungere la prenotazione online al sito?",
      "answer": "Sì, se il flusso è coerente con il modo in cui gestisci gli appuntamenti. Si può usare un form, un link a un gestionale esterno, WhatsApp o una richiesta guidata. L'importante è non creare un passaggio finto che poi richiede comunque mille conferme manuali."
    },
    {
      "question": "Le pagine dei trattamenti aiutano davvero su Google?",
      "answer": "Sì, quando rispondono a ricerche reali: sintomi, prestazioni, zona, dubbi prima della visita. Una pagina generica su tutto non serve molto. Meglio contenuti specifici, leggibili e strutturati, senza copia-incolla medico preso da brochure o siti concorrenti."
    },
    {
      "question": "Devo rifare anche il profilo Google Business?",
      "answer": "Spesso sì, almeno va controllato. Orari, categorie, foto, indirizzo, link al sito e recensioni incidono sul modo in cui il paziente ti trova. Se sito e scheda Google raccontano due cose diverse, il problema non è Google. È disordine."
    },
    {
      "question": "Meglio un sito semplice o molte pagine?",
      "answer": "Meglio un sito esteso solo dove serve. Uno psicologo può avere bisogni diversi da un poliambulatorio o da uno studio dentistico con più trattamenti. La struttura deve seguire le decisioni del paziente: capire, fidarsi, contattare. Il resto si taglia. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "dentista a"
},
  'studi-professionali': {
  "description": "Uno studio professionale non può sembrare un archivio polveroso online. Chi cerca un avvocato, un commercialista o un architetto a città vuole capire subito competenze, casi, zona servita e prossimo passo. Il sito deve togliere attrito, non nascondere tutto dietro testi legalese e menu confusi.",
  "microStory": "Uno studio legale a Cassino aveva un sito elegante solo in apparenza: 5 pagine, nessuna area di competenza chiara, contatto generico e testi da brochure. Il web design è stato ricostruito su casi tipici: lavoro, famiglia, recupero crediti, consulenza aziendale. Ogni pagina spiega quando chiamare e quali dati servono. Il form filtra materia e urgenza, così lo studio non riceve messaggi ciechi. Dopo 90 giorni le richieste qualificate sono diventate 9 al mese, prima erano quasi sempre passaparola.",
  "caseStudyRef": undefined,
  "solutionTitle": "Siti per studi professionali che non sembrano fotocopie",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Sito fermo al 2004",
      "desc": "Testi lunghi, font piccoli, pagine lente e nessuna gerarchia. Il cliente arriva da Google, vede un muro di frasi da albo professionale e se ne va prima di capire se può fidarsi. Il problema è il sito, non il tuo studio."
    },
    {
      "icon": "ph-prohibit",
      "title": "Servizi nascosti male",
      "desc": "Chi sei, cosa fai e per chi lavori finiscono in una pagina secondaria, sepolti tra menu vaghi e biografie interminabili. Un cliente che cerca assistenza legale, fiscale o immobiliare non deve fare archeologia. Deve trovare la strada. Punto."
    },
    {
      "icon": "ph-chart-line-down",
      "title": "Contatti senza metodo",
      "desc": "Modulo generico, nessuna domanda utile, nessuna richiesta consulenza strutturata, WhatsApp messo a caso. Così arrivano messaggi confusi oppure non arriva nulla. Il sito deve filtrare, orientare e portare contatti leggibili allo studio."
    }
  ],
  "features": [
    {
      "title": "Sito costruito sullo studio",
      "description": "Struttura pensata per studio, servizi, aree operative e città servite. Niente template riciclato da palestra, ristorante o consulente qualsiasi. Ogni sezione ha un motivo preciso."
    },
    {
      "title": "Pagine servizio chiare",
      "description": "Ogni servizio ha una pagina leggibile, con contesto, casi tipici, domande frequenti e invito al contatto. Il linguaggio resta professionale, ma non diventa una sentenza da decifrare."
    },
    {
      "title": "SEO tecnica base",
      "description": "Titoli, meta description, heading, URL, dati strutturati e performance sistemati per intercettare ricerche locali come professionista più città. Senza trucchi, senza pacchetti magici, senza fumo."
    },
    {
      "title": "Google Business integrato",
      "description": "Profilo Google Business collegato al sito, mappa coerente, dati di contatto allineati e percorso chiaro verso chiamata, form o WhatsApp. Il passaparola trova una conferma solida online."
    },
    {
      "title": "GDPR e contatti puliti",
      "description": "Privacy, cookie, form contatto e consensi impostati con attenzione. Il cliente può scrivere in modo ordinato, lo studio riceve richieste più leggibili, la catena di plug-in random resta fuori."
    }
  ],
  "faqs": [
    {
      "question": "Il sito può parlare in modo chiaro senza farci sembrare poco professionali?",
      "answer": "Sì. Chiarezza non significa banalizzare. Per uno studio professionale significa spiegare ambiti, casi tipici, metodo di contatto e limiti dell’intervento senza trasformare ogni pagina in un parere tecnico. Il tono resta serio, ma il cliente capisce cosa fare dopo."
    },
    {
      "question": "Serve una pagina per ogni servizio dello studio?",
      "answer": "Nella maggior parte dei casi sì, almeno per i servizi principali. Una pagina unica piena di tutto confonde Google e persone. Meglio distinguere, per esempio, consulenza fiscale, pratiche immobiliari o progettazione architettonica, così ogni ricerca trova una risposta precisa."
    },
    {
      "question": "Possiamo usare testi già presenti nel vecchio sito?",
      "answer": "Si possono recuperare dati, credenziali, aree di attività e informazioni istituzionali. I testi però vanno spesso riscritti: quelli vecchi tendono a nascondere il punto, ripetere formule da brochure e non guidare il cliente verso una richiesta concreta."
    },
    {
      "question": "Il sito può aiutarci con le ricerche locali su Google?",
      "answer": "Sì, se la struttura è costruita per le ricerche locali: città servite, pagine chiare, dati coerenti, Google Business Profile, mappa e contenuti pertinenti. Non basta scrivere il nome della città nel footer e sperare. Serve ordine."
    },
    {
      "question": "Come gestiamo form, WhatsApp e richieste di consulenza?",
      "answer": "Si decide prima che tipo di contatto vuoi ricevere. Un form per uno studio legale non deve chiedere le stesse cose di uno studio tecnico o di un’agenzia immobiliare. Campi, consenso, messaggio e canale vanno progettati per ridurre rumore."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "avvocato a"
},
  'casa-edilizia': {
  "description": "Per idraulici, elettricisti, fabbri, serramentisti e imprese edili, il sito non è una brochure: è il posto dove chi ha urgenza capisce se può chiamarti subito e vede lavori veri. Senza foto, mappa, servizi chiari e bottone telefono, il contatto finisce altrove.",
  "microStory": "Per un idraulico tra Frosinone e Ceccano il vecchio sito era una pagina unica con foto stock e numero piccolo. Chi aveva una perdita cercava da telefono e usciva dopo pochi secondi. Il nuovo web design ha separato pronto intervento, manutenzione caldaie, rifacimenti bagno e zone servite. Abbiamo messo chiamata, WhatsApp e foto lavori reali nei punti dove servono. In 8 settimane le chiamate tracciate dal sito sono passate da 5 a 23, con meno richieste fuori zona.",
  "caseStudyRef": undefined,
  "solutionTitle": "Siti per edilizia che tagliano fuori template e passaggi inutili",
  "problems": [
    {
      "icon": "ph-globe",
      "title": "Passaparola senza rete",
      "desc": "Il passaparola porta lavoro finché qualcuno ricorda il tuo numero. Quando cercano idraulico urgente o elettricista in zona, una scheda vuota e un sito assente lasciano spazio a chi compare prima."
    },
    {
      "icon": "ph-camera",
      "title": "Lavori non dimostrati",
      "desc": "Rifacimenti bagno, quadri elettrici, cancelli, serramenti e ristrutturazioni parlano meglio di qualunque slogan. Senza una galleria ordinata, il cliente vede solo parole e non ha prove per fidarsi."
    },
    {
      "icon": "ph-clock",
      "title": "Mobile senza chiamata",
      "desc": "Chi ha una perdita, un blackout o una porta bloccata non compila labirinti. Se da telefono non trova subito Chiama ora, WhatsApp e zona servita, passa al prossimo risultato. Punto."
    }
  ],
  "features": [
    {
      "title": "Sito cucito sul mestiere",
      "description": "Struttura costruita sui tuoi interventi reali: servizi, zone coperte, urgenze, lavori completati e contatti rapidi. Niente template da agenzia riciclato per dieci settori diversi."
    },
    {
      "title": "Portfolio lavori chiaro",
      "description": "Galleria con foto, categorie e contesto: prima, dopo, tipo di intervento, comune e dettagli utili. Il cliente vede prove, non promesse impacchettate da catalogo."
    },
    {
      "title": "Pagine servizi locali",
      "description": "Pagine leggibili per ricerche concrete: riparazioni, installazioni, manutenzioni, ristrutturazioni, serramenti, pronto intervento. Testi asciutti, tecnici quanto basta, pensati per Google e per chi deve chiamare."
    },
    {
      "title": "Mappa e scheda Google",
      "description": "Google Business Profile sistemato, indirizzo o area operativa coerenti, mappa integrata e contatti allineati. Basta dati sparsi tra vecchie pagine, portali e profili dimenticati."
    },
    {
      "title": "Contatto senza attrito",
      "description": "Telefono, WhatsApp e form messi dove servono, soprattutto da mobile. Privacy e cookie GDPR gestiti in modo ordinato, senza plug-in casuali infilati solo per tappare buchi."
    }
  ],
  "faqs": [
    {
      "question": "Mi serve davvero un sito se lavoro già col passaparola?",
      "answer": "Sì, se vuoi farti trovare quando il passaparola non arriva. Chi cerca un idraulico, un fabbro o un elettricista spesso ha fretta e controlla online. Il sito serve a mostrargli chi sei, dove lavori, cosa fai e come chiamarti subito."
    },
    {
      "question": "Le foto dei lavori sono così importanti?",
      "answer": "Nel settore casa ed edilizia sono decisive. Una ristrutturazione, un impianto ordinato o un serramento montato bene si capiscono guardando. Le foto riducono dubbi, fanno vedere il livello del lavoro e distinguono un artigiano vero da una pagina generica."
    },
    {
      "question": "Posso usare un template già pronto?",
      "answer": "Puoi, ma spesso ti ritrovi con la stessa pagina di un ristorante, un consulente e una palestra. Per edilizia e impianti servono servizi chiari, zone, urgenze, foto lavori, telefono evidente e contenuti scritti sul tuo mestiere. Fine della storia."
    },
    {
      "question": "Il sito può aiutare sulle ricerche locali?",
      "answer": "Sì, se pagine, testi, scheda Google, mappa e dati di contatto sono coerenti. Non basta scrivere una volta il nome della città. Serve spiegare interventi, comuni serviti, casi tipici e modalità di contatto in modo leggibile."
    },
    {
      "question": "Meglio form, telefono o WhatsApp?",
      "answer": "Per urgenze e lavori in casa servono tutti, ma con priorità diversa. Da mobile il telefono deve essere immediato. WhatsApp aiuta per foto e dettagli. Il form resta utile per richieste meno urgenti e lavori da programmare. Decidi tu."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "idraulico urgente a"
},
  'auto-mobilita': {
  "description": "Nel settore auto il sito deve rispondere prima del telefono: chi ha una gomma bucata, un paraurti rovinato o deve prenotare una guida cerca vicino, guarda recensioni, foto reali e capisce in pochi secondi se può fidarsi.",
  "microStory": "Un’officina locale riceveva molte telefonate ripetitive: orari, tagliando, gomme, revisione, preventivo carrozzeria. Il sito esisteva, ma non rispondeva a nulla. Abbiamo rifatto il web design con pagine servizio brevi, foto reali del reparto, CTA mobile e modulo che chiede veicolo, problema e urgenza. Il tempo medio sulla pagina tagliando è salito da 22 a 58 secondi. Le richieste da form e WhatsApp sono arrivate a 27 nel primo mese, contro 4 del mese precedente.",
  "caseStudyRef": undefined,
  "solutionTitle": "Sito per officine e mobilità: meno caos, più richieste chiare",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Listino sempre nascosto",
      "desc": "Chi cerca tagliando, gomme, carrozzeria o lezioni di guida non vuole inseguire informazioni. Se il sito mostra solo frasi vaghe, la richiesta si sposta dal concorrente con pagine più chiare. Punto."
    },
    {
      "icon": "ph-camera",
      "title": "Foto finte ovunque",
      "desc": "Le immagini da catalogo ammazzano la fiducia. Un carrozziere senza lavori prima e dopo, un gommista senza reparto visibile o una concessionaria senza auto reali sembrano intercambiabili. Il web non perdona il fumo."
    },
    {
      "icon": "ph-clock",
      "title": "Telefono sempre occupato",
      "desc": "Quando l’auto si ferma, il cliente non aspetta. Se il telefono squilla a vuoto, il sito deve raccogliere richiesta, urgenza, modello, zona e contatto. Altrimenti la chiamata persa diventa lavoro perso."
    }
  ],
  "features": [
    {
      "title": "Sito cucito sul mestiere",
      "description": "Pagine costruite su officina, carrozzeria, gomme, scuola guida o vendita auto. Niente template riciclato con tre icone e testo buono per chiunque."
    },
    {
      "title": "Servizi spiegati bene",
      "description": "Ogni intervento ha una pagina chiara: cosa fai, per chi, quando serve, come prenotare. Meno telefonate inutili, più richieste già ordinate."
    },
    {
      "title": "Galleria lavori reali",
      "description": "Foto vere di riparazioni, cambi gomme, mezzi in sede, aula, parco auto o attrezzatura. La fiducia nasce da prove visive, non da immagini lucide senza officina."
    },
    {
      "title": "Google Business e mappe",
      "description": "Scheda Google allineata, indirizzo coerente, mappa integrata e collegamenti rapidi. Per chi cerca vicino casa o vicino al lavoro, la prossimità decide molto."
    },
    {
      "title": "Contatto senza attrito",
      "description": "Form, WhatsApp e chiamata rapida raccolgono richieste anche mentre sei sotto un ponte, in cabina verniciatura o con un cliente al banco."
    }
  ],
  "faqs": [
    {
      "question": "Ha senso fare un sito se ho già Google Business?",
      "answer": "Sì, perché Google Business intercetta la ricerca locale, ma il sito spiega meglio servizi, lavori, foto, orari, zone servite e modalità di contatto. La scheda porta traffico, il sito mette ordine e riduce le domande ripetute."
    },
    {
      "question": "Devo inserire tutto il listino sul sito?",
      "answer": "Non per forza. Per officine, carrozzieri e autoscuole spesso bastano pagine chiare con tipologie di intervento, condizioni, tempi indicativi e cosa serve per richiedere informazioni corrette. L’obiettivo è evitare chiamate confuse, non trasformare tutto in catalogo."
    },
    {
      "question": "Posso usare foto scattate in officina con il telefono?",
      "answer": "Sì, se sono pulite, leggibili e autorizzate quando compaiono targhe o persone. Meglio una foto vera di un lavoro fatto bene che una macchina perfetta presa da archivio. Il cliente vuole capire se lì dentro succede lavoro reale."
    },
    {
      "question": "Il sito può aiutare quando non riesco a rispondere al telefono?",
      "answer": "Sì. Un modulo fatto bene può chiedere veicolo, problema, urgenza, zona e preferenza di contatto. Il pulsante WhatsApp aiuta per foto del danno o della gomma. Così non perdi richieste solo perché sei occupato."
    },
    {
      "question": "Per una concessionaria servono schede auto complete?",
      "answer": "Dipende dal flusso di vendita. Se il parco cambia spesso, conviene mostrare almeno modelli, foto reali, disponibilità e contatto rapido. Se aggiornarle diventa ingestibile, meglio una struttura leggera ma precisa. Il caos in vetrina online si vede subito."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "officina vicino"
},
  'food-hospitality': {
  "description": "Food, hospitality e turismo vivono su smartphone: menu leggibile, foto credibili, mappa, prenotazione. Se il sito è un template lento o un PDF fotografato, il cliente torna su Booking, TripAdvisor o Instagram e decide lì. Il tuo dominio resta fuori dalla scelta.",
  "microStory": "Per una trattoria con camere il sito era fermo a un PDF menu fotografato e una gallery pesante. Da mobile servivano troppi zoom e Booking diventava il canale più comodo. Il web design è stato ripulito: menu HTML leggibile, camere con servizi essenziali, mappa, orari e prenotazione diretta. Le immagini sono state ridotte senza massacrarle. In 60 giorni le richieste dirette sono passate da 6 a 31, e il personale ha smesso di mandare il menu a mano su WhatsApp.",
  "caseStudyRef": undefined,
  "solutionTitle": "Siti per ristoranti, hotel e locali che non sembrano clonati",
  "problems": [
    {
      "icon": "ph-warning-circle",
      "title": "Menu illeggibile da mobile",
      "desc": "Il cliente apre il sito durante una scelta veloce: vuole piatti, camere, orari, posizione. Se trova un PDF fotografato, zooma due volte, si stanca e cerca altrove. Non serve teatro: serve chiarezza sul telefono."
    },
    {
      "icon": "ph-calendar-blank",
      "title": "Prenotazioni gestite male",
      "desc": "Senza un percorso chiaro, arrivano telefonate nel mezzo del servizio, messaggi sparsi su WhatsApp e richieste perse. Il sito deve portare alla prenotazione giusta, non aggiungere un altro passaggio inutile alla sala o alla reception."
    },
    {
      "icon": "ph-camera",
      "title": "Foto senza identità",
      "desc": "Foto scure da smartphone, copertine casuali e gallery messe lì da un template fanno sembrare uguali ristoranti, b-b, pizzerie e agriturismi. Il problema non è essere piccoli: è sembrare intercambiabili."
    }
  ],
  "features": [
    {
      "title": "Sito per locale reale",
      "description": "Struttura pensata per locale, camere, tavoli, menu, eventi o degustazioni. Niente template riciclato con testi finti e blocchi messi in fila da un’agenzia a sei mani."
    },
    {
      "title": "Menu e contenuti leggibili",
      "description": "Menu, camere, servizi, orari e contatti organizzati per lettura rapida da smartphone. Se il cliente deve pizzicare lo schermo per capire, il sito sta già perdendo."
    },
    {
      "title": "Prenotazione e WhatsApp",
      "description": "Pulsanti chiari per chiamata, messaggio, form o sistema di prenotazione già usato dal locale. L’obiettivo è ridurre attrito, non creare un altro pannello da controllare."
    },
    {
      "title": "Mappa e Google Business",
      "description": "Profilo Google Business allineato, mappe integrate e dati coerenti tra sito, scheda e ricerche locali. Indirizzo, orari e contatti non possono raccontare tre versioni diverse."
    },
    {
      "title": "GDPR e base tecnica",
      "description": "Privacy, cookie, SEO tecnica base, performance e pagine essenziali messe in ordine. Meno plug-in random, meno dipendenze inutili, più controllo sul tuo dominio. Punto."
    }
  ],
  "faqs": [
    {
      "question": "Possiamo mettere il menu senza caricare ogni volta un PDF?",
      "answer": "Sì. Il menu può essere costruito come pagina leggibile da smartphone, con sezioni, allergeni, piatti stagionali e aggiornamenti gestibili. Il PDF può restare come download, ma non deve essere l’unico modo per capire cosa servite."
    },
    {
      "question": "Il sito può collegarsi al nostro sistema di prenotazione?",
      "answer": "Di solito sì, se il sistema offre link, widget o integrazioni pulite. Prima si controlla cosa usate davvero in sala o reception, poi si decide come inserirlo senza rompere il flusso di lavoro esistente."
    },
    {
      "question": "Serve per forza rifare anche le foto?",
      "answer": "Non sempre, ma le foto contano molto nel food e nell’hospitality. Se quelle attuali sono buie, storte o incoerenti, il sito può solo limitarne i danni. Meglio poche immagini buone che una gallery piena di materiale debole."
    },
    {
      "question": "TripAdvisor e Booking bastano già?",
      "answer": "Sono utili, ma non sono casa tua. Lì competi dentro una griglia con recensioni, filtri e commissioni. Il sito serve a dare una versione controllata del locale, far capire subito chi siete e portare il cliente al contatto diretto."
    },
    {
      "question": "Possiamo aggiornare orari, eventi e chiusure senza chiamarti ogni volta?",
      "answer": "Sì, se ha senso per la gestione quotidiana. Si può prevedere una parte modificabile per eventi, menu, chiusure e comunicazioni. Va progettata semplice, perché un pannello complicato finisce abbandonato dopo due settimane. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "ristorante a"
},
  'retail-negozi': {
  "description": "Per un negozio fisico il sito non deve sostituire il banco, la prova in camerino o il consiglio dal vivo. Deve far capire cosa vendi, dove sei, quando sei aperto e come contattarti subito, senza catene di fornitori e pagine copia-incolla.",
  "microStory": "Un fioraio con buon passaparola non compariva quando qualcuno cercava composizioni per lauree o consegne in zona. Il vecchio sito mostrava tre foto vecchie e orari non aggiornati. Il nuovo web design ha messo categorie, occasioni, WhatsApp visibile e una galleria stagionale facile da aggiornare. Il negozio non è diventato un e-commerce forzato: ha iniziato a ricevere richieste più precise. In 45 giorni i messaggi da sito sono passati da 8 a 42, con molte meno domande sugli orari.",
  "caseStudyRef": undefined,
  "solutionTitle": "Una vetrina digitale che non svende il negozio",
  "problems": [
    {
      "icon": "ph-storefront",
      "title": "Prodotti invisibili online",
      "desc": "Se online non si vede nulla, il cliente non sa se vale la pena passare. Una gioielleria, un fioraio o una libreria hanno bisogno di mostrare assortimento, stile e disponibilità percepita prima della visita."
    },
    {
      "icon": "ph-clock",
      "title": "Orari introvabili",
      "desc": "Quando indirizzo, mappa e orari sono nascosti, il cliente chiude e cerca altrove. Per un negozio fisico questa è perdita secca: la visita parte da Google, non dalla serranda."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Contatto sepolto male",
      "desc": "WhatsApp in fondo alla pagina contatti è attrito inutile. Chi vuole chiedere una taglia, una composizione floreale o la disponibilità di un libro deve arrivarci in un gesto. Punto."
    }
  ],
  "features": [
    {
      "title": "Sito vetrina governato",
      "description": "Struttura pensata attorno al negozio reale: reparti, prodotti, servizi, posizione e tono commerciale. Niente template riempiti con testi neutri e foto buttate dentro."
    },
    {
      "title": "Gallerie ordinate",
      "description": "Immagini organizzate per far capire subito cosa tratti: abiti, arredi, gioielli, fiori, libri o articoli tecnici. La vetrina digitale deve aiutare la visita, non fare confusione."
    },
    {
      "title": "SEO tecnica base",
      "description": "Pagine pulite, titoli sensati, dati locali e struttura leggibile da Google. Serve a farti trovare quando qualcuno cerca un negozio vicino, non a gonfiare promesse da agenzia."
    },
    {
      "title": "Google Business e mappe",
      "description": "Scheda Google Business allineata, mappa integrata, indirizzo chiaro e contatti coerenti. Se il cliente vuole arrivare in negozio, non deve fare archeologia digitale."
    },
    {
      "title": "Privacy e contatto diretto",
      "description": "Cookie, privacy e form impostati con criterio, più pulsante WhatsApp visibile dove serve. Meno plug-in random, meno passaggi inutili, più richieste gestibili dal negozio."
    }
  ],
  "faqs": [
    {
      "question": "Devo per forza vendere online?",
      "answer": "No. Per molti negozi il sito serve prima come vetrina: mostra assortimento, stile, servizi, orari, indirizzo e contatti. L’e-commerce ha senso solo se logistica, catalogo e gestione ordini sono pronti. Altrimenti diventa un altro lavoro fatto male."
    },
    {
      "question": "Posso mostrare prodotti senza avere il catalogo intero?",
      "answer": "Sì. Si può costruire una galleria selezionata: categorie, pezzi rappresentativi, collezioni, lavori recenti o prodotti stagionali. Un fioraio può mostrare composizioni, una gioielleria linee e materiali, una libreria novità e consigli. Non serve caricare ogni articolo."
    },
    {
      "question": "WhatsApp può essere più visibile?",
      "answer": "Deve esserlo. Nel retail il contatto rapido è spesso decisivo: taglie, disponibilità, prenotazioni, orari speciali, ordini da ritirare. Il pulsante va messo nei punti giusti, non nascosto come se fosse un dettaglio tecnico."
    },
    {
      "question": "La scheda Google Business basta da sola?",
      "answer": "Aiuta, ma non basta sempre. La scheda dà posizione, recensioni e orari; il sito spiega meglio cosa vendi, cosa ti distingue sul territorio, quali servizi offri e perché vale la visita. Insieme lavorano meglio, separati lasciano buchi."
    },
    {
      "question": "Se cambio spesso prodotti o vetrina?",
      "answer": "Il sito va pensato per aggiornamenti semplici: gallerie snelle, sezioni stagionali, pagine modificabili e testi non rigidi. Così puoi cambiare collezione, mostrare nuovi arrivi o promuovere un servizio senza chiamare tre fornitori ogni volta. Fine della storia."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "gioielleria a"
},
  'creativita-eventi': {
  "description": "Nel mondo eventi e contenuti visivi, il sito non può essere un album buttato online. Deve raccogliere portfolio, servizi, metodo di lavoro, aree servite e contatti in un posto solo, senza catene di fornitori, pagine lente e foto massacrate dal mobile.",
  "microStory": "Un fotografo eventi aveva lavori sparsi tra Instagram, Drive e un portfolio lento da 9 secondi. Chi chiedeva un matrimonio riceveva link diversi e ricominciava ogni volta da zero. Il nuovo web design ha ordinato servizi, gallerie, zone, tempi di consegna e form richiesta. Le immagini sono state divise per evento e caricate in modo più leggero. Il portfolio principale scende sotto 2,3 secondi su mobile. In 2 mesi le richieste dal sito sono passate da 3 a 16.",
  "caseStudyRef": undefined,
  "solutionTitle": "Basta portfolio dispersi: il tuo sito deve vendere ordine",
  "problems": [
    {
      "icon": "ph-instagram-logo",
      "title": "Portfolio sparso ovunque",
      "desc": "Instagram mostra l'ultimo post, Behance solo una parte, Drive sembra una cartella interna. Chi cerca un fotografo, un videomaker o un wedding planner non trova un percorso chiaro. Trova pezzi. Punto."
    },
    {
      "icon": "ph-warning-circle",
      "title": "Tutto passa dai DM",
      "desc": "Se pacchetti, tempi, metodo e domande frequenti vivono solo in chat, ogni contatto riparte da zero. Il sito deve filtrare richieste confuse, spiegare come lavori e far arrivare persone già orientate."
    },
    {
      "icon": "ph-clock",
      "title": "Immagini lente su mobile",
      "desc": "Foto enormi caricate senza criterio, gallerie pesanti, plug-in messi lì perché qualcuno li ha consigliati. Risultato: su telefono il portfolio si apre tardi, proprio quando il cliente sta decidendo se scriverti."
    }
  ],
  "features": [
    {
      "title": "Sito senza template",
      "description": "Struttura cucita sul tuo lavoro visivo: portfolio, pagine servizio, bio essenziale, aree servite e contatti. Niente layout copiato da mille creativi con foto diverse."
    },
    {
      "title": "Gallerie leggibili",
      "description": "Selezione lavori ordinata per tipologia, evento, luogo o stile. Le immagini vengono preparate per mobile, desktop e caricamento rapido, senza distruggere resa e dettagli."
    },
    {
      "title": "Metodo e pacchetti chiari",
      "description": "Spiego cosa succede prima, durante e dopo il servizio: sopralluoghi, shooting, consegne, revisioni, tempistiche e confini. Meno messaggi ripetuti, contatti più consapevoli."
    },
    {
      "title": "SEO tecnica base",
      "description": "Titoli, testi, URL, metadata, performance, sitemap e dati locali impostati con criterio. Serve a farti trovare per ricerche reali, non per riempire pagine di parole vuote."
    },
    {
      "title": "Contatti senza attrito",
      "description": "Form, WhatsApp, Google Business profile, mappe, privacy e cookie GDPR sistemati nello stesso flusso. Il cliente vede, capisce, contatta. Fine della storia."
    }
  ],
  "faqs": [
    {
      "question": "Ho già Instagram: mi serve davvero un sito?",
      "answer": "Instagram è affitto. Il sito è proprietà. L'algoritmo decide cosa mostrare, l'account può sparire dopo una segnalazione, la reach decresce di anno in anno. Il sito raccoglie lavori selezionati, servizi, metodo, zone coperte e contatti in modo stabile — paghi una volta, lo possiedi, lo controlli. Per un fotografo o un organizzatore eventi, serve a trasformare contenuti sparsi in un catalogo consultabile, non a sperare che il post di ieri rientri nel feed di oggi."
    },
    {
      "question": "Posso usare le foto che ho già nel portfolio?",
      "answer": "Sì, ma vanno scelte e preparate. Non tutte le foto belle aiutano a vendere un servizio. Si costruisce una selezione per categoria, ritmo visivo e contesto: matrimonio, evento corporate, backstage, viaggio, scuola o corso. Meno caos, più direzione."
    },
    {
      "question": "Il sito può spiegare i miei pacchetti senza sembrare rigido?",
      "answer": "Sì. Si possono descrivere fasce di servizio, opzioni, tempi e casi tipici senza chiuderti in schemi finti. L'obiettivo è far capire come lavori prima della chiamata, non trasformare il tuo mestiere in un menù da fast food."
    },
    {
      "question": "Quanto conta la velocità per un sito fotografico?",
      "answer": "Conta molto, perché il traffico arriva spesso da mobile. Se una galleria pesa troppo, il cliente esce prima di vedere il lavoro migliore. Le immagini vanno compresse, ridimensionate e caricate con criterio, mantenendo resa sufficiente per scegliere."
    },
    {
      "question": "Si può integrare Google Business e le mappe?",
      "answer": "Sì. Per chi lavora su territorio, location, eventi e matrimoni, Google Business aiuta a collegare ricerca locale, recensioni, mappe e contatti. Il sito può rafforzare questo percorso con pagine dedicate alle zone servite e link chiari."
    }
  ],
  "ctaText": "Sentiamoci e mettiamo ordine",
  "searchExamplePrefix": "fotografo matrimonio a"
}
};
