-- Workflow Templates v3 — 5 workflow aggiuntivi

-- 15. Dominio 30gg → avvisa cliente via email + WA
INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges) VALUES (
  'Dominio 30gg → Avvisa Cliente',
  'Avvisa il cliente 30 giorni prima della scadenza del dominio via email e WhatsApp.',
  'draft', 'cron', '{"interval_hours":24,"time":"09:00"}',
  '[{"id":"t1","type":"trigger_cron","position":{"x":50,"y":200},"data":{"label":"Ogni giorno ore 9"}},{"id":"q1","type":"tool_db_query","position":{"x":300,"y":200},"data":{"label":"Domini 30gg","query":"SELECT d.domain_name || ''.'' || d.tld as dominio, d.expiration_date, d.auto_renew, c.contact_name, c.email, c.phone FROM domains d LEFT JOIN customers c ON c.id = d.customer_id WHERE d.expiration_date BETWEEN CURRENT_DATE + INTERVAL ''28 days'' AND CURRENT_DATE + INTERVAL ''32 days''"}},{"id":"l1","type":"logic_loop","position":{"x":500,"y":200},"data":{"label":"Per ogni dominio","array_field":"rows"}},{"id":"a1","type":"llm_chat","position":{"x":700,"y":200},"data":{"label":"Genera messaggio","prompt":"Scrivi un messaggio breve e professionale per {{contact_name}} per avvisare che il dominio {{dominio}} scade il {{expiration_date}}. Rinnovo: {{auto_renew}}. Se auto_renew=true rassicura, se false chiedi conferma rinnovo. Max 4 righe. Firma: Federico.","provider":"auto","task":"chat_fast"}},{"id":"c1","type":"logic_condition","position":{"x":950,"y":200},"data":{"label":"Ha telefono?","condition":"input.phone && input.phone.length > 5","subtype":"condition"}},{"id":"w1","type":"tool_send_whatsapp","position":{"x":1200,"y":130},"data":{"label":"WA al cliente","phone":"{{phone}}","message":"{{text}}"}},{"id":"e1","type":"tool_send_email","position":{"x":1200,"y":300},"data":{"label":"Email al cliente","to":"{{email}}","subject":"Scadenza dominio {{dominio}}","body":"{{text}}"}},{"id":"n1","type":"tool_send_telegram","position":{"x":1450,"y":200},"data":{"label":"Log Telegram","message":"🌐 Avvisato {{contact_name}} per scadenza {{dominio}}"}}]',
  '[{"id":"e1","source":"t1","target":"q1"},{"id":"e2","source":"q1","target":"l1"},{"id":"e3","source":"l1","target":"a1"},{"id":"e4","source":"a1","target":"c1"},{"id":"e5","source":"c1","target":"w1","sourceHandle":"handle-true"},{"id":"e6","source":"c1","target":"e1","sourceHandle":"handle-false"},{"id":"e7","source":"w1","target":"n1"},{"id":"e8","source":"e1","target":"n1"}]'
);

-- 16. Dominio 7gg → sollecito urgente cliente
INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges) VALUES (
  'Dominio 7gg → Sollecito Urgente',
  'Sollecito urgente al cliente 7 giorni prima se rinnovo manuale e non ancora rinnovato.',
  'draft', 'cron', '{"interval_hours":24,"time":"08:00"}',
  '[{"id":"t1","type":"trigger_cron","position":{"x":50,"y":200},"data":{"label":"Ogni giorno ore 8"}},{"id":"q1","type":"tool_db_query","position":{"x":300,"y":200},"data":{"label":"Domini urgenti","query":"SELECT d.domain_name || ''.'' || d.tld as dominio, d.expiration_date, c.contact_name, c.email, c.phone FROM domains d LEFT JOIN customers c ON c.id = d.customer_id WHERE d.expiration_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL ''7 days'' AND d.auto_renew = false"}},{"id":"l1","type":"logic_loop","position":{"x":500,"y":200},"data":{"label":"Per ognuno","array_field":"rows"}},{"id":"a1","type":"llm_chat","position":{"x":700,"y":200},"data":{"label":"Messaggio urgente","prompt":"Scrivi un messaggio URGENTE per {{contact_name}}: il dominio {{dominio}} scade tra pochi giorni ({{expiration_date}}) e ha rinnovo MANUALE. Se non viene rinnovato il sito andrà offline. Tono urgente ma professionale. Max 5 righe. Firma: Federico.","provider":"auto","task":"chat_fast"}},{"id":"w1","type":"tool_send_whatsapp","position":{"x":950,"y":130},"data":{"label":"WA urgente","phone":"{{phone}}","message":"⚠️ {{text}}"}},{"id":"m1","type":"tool_send_email","position":{"x":950,"y":300},"data":{"label":"Email urgente","to":"{{email}}","subject":"⚠️ URGENTE: Dominio {{dominio}} in scadenza!","body":"{{text}}"}},{"id":"n1","type":"tool_send_telegram","position":{"x":1200,"y":200},"data":{"label":"Alert me","message":"🚨 Sollecito urgente inviato a {{contact_name}} per {{dominio}}"}}]',
  '[{"id":"e1","source":"t1","target":"q1"},{"id":"e2","source":"q1","target":"l1"},{"id":"e3","source":"l1","target":"a1"},{"id":"e4","source":"a1","target":"w1"},{"id":"e5","source":"a1","target":"m1"},{"id":"e6","source":"w1","target":"n1"},{"id":"e7","source":"m1","target":"n1"}]'
);

-- 17. Anniversario progetto → proponi manutenzione
INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges) VALUES (
  'Anniversario Progetto → Proponi Manutenzione',
  'Un anno dopo il completamento di un progetto, proponi pacchetto manutenzione al cliente.',
  'draft', 'cron', '{"interval_hours":168,"time":"10:00"}',
  '[{"id":"t1","type":"trigger_cron","position":{"x":50,"y":200},"data":{"label":"Settimanale"}},{"id":"q1","type":"tool_db_query","position":{"x":300,"y":200},"data":{"label":"Progetti 1 anno fa","query":"SELECT cp.name, cp.actual_end_date, c.contact_name, c.email, c.phone, c.company_name FROM client_projects cp LEFT JOIN customers c ON c.id = cp.customer_id WHERE cp.status = ''completed'' AND cp.actual_end_date BETWEEN CURRENT_DATE - INTERVAL ''370 days'' AND CURRENT_DATE - INTERVAL ''360 days''"}},{"id":"l1","type":"logic_loop","position":{"x":500,"y":200},"data":{"label":"Per ognuno","array_field":"rows"}},{"id":"a1","type":"llm_chat","position":{"x":700,"y":200},"data":{"label":"Proposta manutenzione","prompt":"Scrivi un''email cordiale a {{contact_name}} ({{company_name}}). Il progetto \\\"{{name}}\\\" è stato completato circa un anno fa. Proponi un check-up del sito + pacchetto manutenzione annuale. Tono amichevole. Firma: Federico Calicchia.","provider":"auto"}},{"id":"n1","type":"tool_send_telegram","position":{"x":950,"y":200},"data":{"label":"Notifica","message":"🔄 Anniversario progetto \\\"{{name}}\\\" per {{contact_name}}\\n\\nBozza proposta:\\n{{text}}"}}]',
  '[{"id":"e1","source":"t1","target":"q1"},{"id":"e2","source":"q1","target":"l1"},{"id":"e3","source":"l1","target":"a1"},{"id":"e4","source":"a1","target":"n1"}]'
);

-- 18. Nuovo booking → prepara brief pre-meeting
INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges) VALUES (
  'Nuovo Booking → Prepara Brief',
  'Quando arriva un booking Cal.com, AI cerca info sul cliente e prepara un brief per il meeting.',
  'draft', 'event', '{"event_type":"booking_creato"}',
  '[{"id":"t1","type":"trigger_event","position":{"x":50,"y":200},"data":{"label":"Nuovo booking","event_type":"booking_creato"}},{"id":"r1","type":"llm_chat","position":{"x":300,"y":200},"data":{"label":"Cerca info","prompt":"Cerca informazioni su questa persona: {{attendee_name}} ({{attendee_email}}). Chi è, azienda, settore, cosa potrebbe aver bisogno da un web designer. Se non trovi info, dillo. Max 200 parole.","provider":"auto","task":"blog_research"}},{"id":"a1","type":"llm_chat","position":{"x":600,"y":200},"data":{"label":"Genera brief","prompt":"Prepara un brief pre-meeting per Federico basandoti su queste info:\\n{{text}}\\n\\nIncludi: 1) Chi è il cliente 2) Possibili esigenze 3) Domande da fare 4) Servizi da proporre. Formato lista puntata, conciso.","provider":"auto"}},{"id":"n1","type":"tool_send_telegram","position":{"x":900,"y":200},"data":{"label":"Brief Telegram","message":"📋 Brief pre-meeting\\nCliente: {{attendee_name}}\\n\\n{{text}}"}},{"id":"b1","type":"output_brain_fact","position":{"x":900,"y":350},"data":{"label":"Ricorda","entity_type":"customer","fact":"Meeting con {{attendee_name}} ({{attendee_email}}). Brief: {{text}}"}}]',
  '[{"id":"e1","source":"t1","target":"r1"},{"id":"e2","source":"r1","target":"a1"},{"id":"e3","source":"a1","target":"n1"},{"id":"e4","source":"a1","target":"b1"}]'
);

-- 19. Lead da form → risposta immediata
INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges) VALUES (
  'Lead da Form → Risposta Immediata',
  'Appena arriva un contatto dal sito, invia email di conferma + WhatsApp di benvenuto.',
  'draft', 'event', '{"event_type":"nuovo_lead"}',
  '[{"id":"t1","type":"trigger_event","position":{"x":50,"y":200},"data":{"label":"Nuovo lead","event_type":"nuovo_lead"}},{"id":"a1","type":"llm_chat","position":{"x":300,"y":200},"data":{"label":"Email conferma","prompt":"Scrivi un''email di conferma ricezione per {{name}} ({{company}}). Ringrazia per il contatto, di'' che risponderai entro 24h con una proposta. Tono professionale e caloroso. Max 5 righe. Firma: Federico Calicchia, Web Designer.","provider":"auto","task":"chat_fast"}},{"id":"m1","type":"tool_send_email","position":{"x":550,"y":130},"data":{"label":"Email conferma","to":"{{email}}","subject":"Grazie per avermi contattato!","body":"{{text}}"}},{"id":"c1","type":"logic_condition","position":{"x":550,"y":300},"data":{"label":"Ha telefono?","condition":"input.phone && input.phone.length > 5","subtype":"condition"}},{"id":"w1","type":"tool_send_whatsapp","position":{"x":800,"y":300},"data":{"label":"WA benvenuto","phone":"{{phone}}","message":"Ciao {{name}}! 👋 Ho ricevuto la tua richiesta. Ti risponderò con una proposta entro 24 ore. A presto! — Federico"}},{"id":"n1","type":"tool_send_telegram","position":{"x":800,"y":130},"data":{"label":"Notifica","message":"📨 Risposta automatica inviata a {{name}} ({{email}})"}}]',
  '[{"id":"e1","source":"t1","target":"a1"},{"id":"e2","source":"a1","target":"m1"},{"id":"e3","source":"a1","target":"c1"},{"id":"e4","source":"c1","target":"w1","sourceHandle":"handle-true"},{"id":"e5","source":"m1","target":"n1"},{"id":"e6","source":"w1","target":"n1"}]'
);
