// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';
import { PROCESS_STEPS_IT } from './_shared/process';

export const ASSISTENZA_WORDPRESS_SERVICE: ServiceDetail = {
  "slug": "assistenza-wordpress",
  "title": "Assistenza WordPress",
  "icon": "ph-shield-check",
  "description": "Ripristino, hardening e performance per WordPress sotto attacco, lento o rotto dai plugin.",
  "longDescription": "Quando WordPress finisce in mano a troppi fornitori, il problema non è più solo tecnico: è una catena di responsabilità scaricate.\nUn plugin aggiornato male, hosting condiviso tirato al limite, tema pieno di patch, backup mai verificati.\n\nIntervengo sul punto preciso: malware, redirect, crash dell’admin, conflitti, lentezza, SSL, permessi, database.\nPrima si isola il danno, poi si ripristina, si chiude la falla e si lascia una traccia leggibile di quello che è stato fatto.\n\nNiente teatro da agenzia.\nNiente riunioni a sei mani. Diagnosi, intervento, controllo finale.\nPunto.",
  "features": [
    {
      "title": "Pulizia malware tracciata",
      "description": "Rimozione di file infetti, redirect malevoli, utenti sospetti, backdoor e codice inserito nei punti peggiori.\nIl sito viene ripristinato partendo da evidenze, non da tentativi alla cieca."
    },
    {
      "title": "Hardening sicurezza serio",
      "description": "Firewall, 2FA, permessi file, blocco editor, limitazioni login e controlli sulle aree sensibili.\nWordPress non diventa invincibile, ma smette di restare spalancato."
    },
    {
      "title": "Conflitti plugin isolati",
      "description": "Analisi di plugin, tema, log PHP e console browser per capire chi rompe cosa.\nSi interviene sul conflitto reale, senza disattivare mezzo sito sperando che passi."
    },
    {
      "title": "Performance tuning reale",
      "description": "Cache, query lente, autoload pesante, tabelle sporche, cron fuori controllo e asset caricati male.\nLa lentezza non si copre con un plugin in più: si misura e si corregge."
    },
    {
      "title": "Audit sicurezza leggibile",
      "description": "Controllo di accessi, plugin, tema, permessi, configurazione server, HTTPS, backup e segnali di compromissione.\nIl report dice cosa è critico, cosa è fragile e cosa va fatto."
    },
    {
      "title": "Migrazione SSL pulita",
      "description": "Passaggio a HTTPS con verifica di mixed content, redirect, canonical, immagini, form e chiamate esterne.\nNiente lucchetto rotto, niente pagine che perdono risorse per strada."
    }
  ],
  "benefits": [
    "Admin di nuovo accessibile senza caccia al colpevole tra plugin e tema.",
    "Sito ripulito da redirect, payload e account sospetti nascosti.",
    "Caricamenti più rapidi con cache, query e database sotto controllo.",
    "Meno rischio di ricadute dopo aggiornamenti o interventi improvvisati.",
    "Report chiaro per decidere cosa tenere, cambiare o rimuovere."
  ],
  "process": PROCESS_STEPS_IT,
  "faqs": [
    {
      "question": "Il mio sito WordPress mostra redirect strani: cosa devo fare subito?",
      "answer": "Prima cosa: non aggiornare plugin a caso e non installare altri plugin di sicurezza nel panico.\nServe bloccare l’accesso non necessario, verificare file, database, utenti admin, cron, .htaccess e tema.\nSe il sito manda traffico verso pagine sospette, va trattato come compromesso finché non si dimostra il contrario."
    },
    {
      "question": "Puoi recuperare un sito WordPress hackerato senza rifarlo da zero?",
      "answer": "Spesso sì, ma dipende dallo stato reale dei file, dal database e dai backup disponibili.\nRifare tutto è l’ultima scelta, non la prima.\nPrima si cerca la compromissione, si rimuovono backdoor e account falsi, si ripristinano i file corretti e si chiudono gli accessi deboli."
    },
    {
      "question": "Un plugin ha rotto admin o front-end: come si interviene?",
      "answer": "Si parte da log, modalità debug, versione PHP, tema attivo e lista plugin.\nPoi si isola il conflitto senza smontare tutto il sito davanti ai clienti.\nIl punto non è trovare un colpevole comodo, ma capire quale combinazione crea l’errore e come correggerla."
    },
    {
      "question": "Il sito è lento anche con un plugin cache: perché?",
      "answer": "Perché la cache non cura query lente, database gonfio, hosting debole, cron impazziti, immagini fuori scala o plugin che caricano asset ovunque.\nSe il TTFB è alto, il problema è spesso prima del browser. Va misurato lato server, database e WordPress, non mascherato."
    },
    {
      "question": "L’audit di sicurezza cosa controlla davvero?",
      "answer": "Controlla utenti, ruoli, plugin, tema, permessi file, configurazione WordPress, HTTPS, backup, intestazioni di sicurezza, endpoint esposti e segnali di compromissione.\nNon è una lista decorativa. Serve a capire dove il sito è fragile e quali interventi hanno priorità tecnica."
    },
    {
      "question": "Dopo l’intervento il sito resta protetto per sempre?",
      "answer": "No.\nChi promette protezione eterna su WordPress sta vendendo aria.\nDopo l’intervento il sito è più chiuso, pulito e controllabile, ma resta un sistema vivo: plugin, tema, PHP, hosting e accessi cambiano.\nServe manutenzione sensata e meno improvvisazione."
    }
  ],
  "awareness": {
    "title": "WordPress non si rompe da solo",
    "subtitle": "Di solito lo rompono passaggi di mano, plugin accumulati e hosting scelti per inerzia.",
    "problems": [
      {
        "icon": "ph-warning-circle",
        "title": "Redirect malevoli",
        "desc": "Il sito sembra online, ma porta utenti e motori di ricerca su contenuti sospetti.\nIntanto Google segnala problemi, la reputazione cala e nessuno sa da dove parta l’infezione."
      },
      {
        "icon": "ph-prohibit",
        "title": "Plugin fuori controllo",
        "desc": "Page builder, addon, plugin cache, plugin sicurezza, plugin per correggere altri plugin.\nA un certo punto basta un aggiornamento e salta admin, front-end o checkout."
      },
      {
        "icon": "ph-clock",
        "title": "Lentezza cronica",
        "desc": "TTFB oltre tre secondi, pagine che superano cinque secondi, database sporco e query pesanti.\nNon è colpa del visitatore. È WordPress lasciato crescere senza controllo."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "DOPO L’INTERVENTO",
    "title": "WordPress va chiuso, non solo rimesso online",
    "body": "Rimettere online un WordPress bucato è la parte facile. La parte utile è impedire che torni identico al punto di partenza: stessi plugin lasciati lì, stesso hosting condiviso saturo, stessi account admin dimenticati, stessi permessi scritti male.\n\nDopo pulizia, recovery o tuning, il lavoro si allarga dove serve: hardening, controllo backup, revisione plugin, HTTPS, database, log, cache e accessi.\n\nSe ci sono più fornitori coinvolti, si taglia il rumore: chi gestisce hosting, chi gestisce dominio, chi tocca WordPress, chi ha le credenziali.\nLe catene a sei mani producono scaricabarile tecnico. Io lascio un sito più leggibile, più chiuso e con priorità chiare per il dopo. Decidi tu."
  }
};
