// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';

export const E_COMMERCE_SERVICE: ServiceDetail = {
  "slug": "e-commerce",
  "title": "E-Commerce",
  "icon": "ph-shopping-cart",
  "description": "E-commerce con catalogo, checkout, pagamenti, spedizioni ed email sotto controllo.\nNiente plugin buttati lì.",
  "longDescription": "Un negozio fisico lavora quando la serranda è alzata.\nOnline, i concorrenti vendono mentre tu stai chiudendo cassa.\n\nIl problema non è “fare un sito con carrello”: è evitare la catena di fornitori che mette un tema pesante, tre plugin random, hosting condiviso e checkout fragile.\n\nQui si costruisce un e-commerce con struttura chiara: catalogo, varianti, magazzino, pagamenti, spedizioni, email transazionali e recupero carrello.\nWooCommerce quando ha senso, headless quando il caso lo richiede.\n\nIn un catalogo con 180 SKU basta una regola spedizione sbagliata per bruciare ordini ogni settimana.\nMeno passaggi di mano, più controllo sui punti che bloccano le vendite.\nPunto.",
  "features": [
    {
      "title": "Catalogo sotto controllo",
      "description": "Prodotti, categorie, varianti, attributi e magazzino vengono impostati con logica commerciale, non caricati a blocchi senza criterio.\nTaglie, colori, disponibilità e SKU devono essere leggibili per chi compra e gestibili da chi vende."
    },
    {
      "title": "Checkout senza attriti",
      "description": "Il checkout viene tenuto pulito: dati necessari, metodi di pagamento chiari, errori comprensibili, nessun passaggio inutile.\nSe servono 9 campi per comprare un prodotto semplice, il carrello sta già perdendo persone."
    },
    {
      "title": "Spedizioni multi-corriere",
      "description": "Zone, soglie, classi di spedizione, corrieri e regole operative vengono messi in ordine prima del lancio.\nSe la spedizione è confusa, il carrello muore lì. Fine della storia."
    },
    {
      "title": "Email che arrivano",
      "description": "Conferme ordine, pagamenti, spedizioni, reset password e recupero carrello non possono dipendere dal caso.\nSi imposta un flusso email serio, con mittenti corretti, template leggibili e tracciamento degli eventi critici."
    },
    {
      "title": "Schema per Shopping",
      "description": "Product, Offer, prezzo, disponibilità, marca e identificativi vengono preparati per Google Shopping e ricerca organica.\nIl catalogo deve essere capito anche dalle piattaforme, non solo visto nel browser."
    },
    {
      "title": "Stack senza casino",
      "description": "Niente tema gonfio, plugin installati perché “magari servono” e hosting da quattro soldi.\nSi sceglie la piattaforma sul caso: WooCommerce per gestione editoriale rapida, headless quando servono performance e integrazioni più spinte."
    }
  ],
  "benefits": [
    "Vendi anche quando il negozio fisico è chiuso.",
    "Porti i clienti sul tuo canale, non solo sui marketplace.",
    "Gestisci catalogo, ordini e disponibilità senza fogli sparsi.",
    "Riduci carrelli persi per checkout lento o confuso.",
    "Prepari il catalogo per Google Shopping e campagne mirate."
  ],
  "process": [
    {
      "step": 1,
      "title": "Analisi catalogo",
      "description": "Si parte da prodotti, varianti, margini, spedizioni e modalità di vendita.\nIl carrello viene progettato intorno al lavoro reale, non intorno al tema più comodo."
    },
    {
      "step": 2,
      "title": "Scelta stack",
      "description": "WooCommerce o headless si decide sul caso: numero prodotti, integrazioni, gestione interna, performance e margine di crescita.\nNessuna piattaforma scelta per moda."
    },
    {
      "step": 3,
      "title": "Setup vendita",
      "description": "Si configurano catalogo, gateway pagamento, spedizioni, tasse, email transazionali e recupero carrello.\nOgni punto critico viene provato prima di andare online."
    },
    {
      "step": 4,
      "title": "Test ordini",
      "description": "Si simulano almeno 12 scenari: acquisti, errori, pagamenti falliti, varianti esaurite, coupon, notifiche e ordini da mobile.\nSe un cliente può bloccarsi, lo scopriamo prima del lancio."
    },
    {
      "step": 5,
      "title": "Lancio controllato",
      "description": "Dopo il go-live si monitorano checkout, email, carrelli, feed e tracciamenti.\nL’e-commerce non viene abbandonato nel momento più delicato."
    }
  ],
  "faqs": [
    {
      "question": "Meglio WooCommerce o un e-commerce headless?",
      "answer": "Dipende da catalogo, gestione interna e integrazioni.\nWooCommerce va bene quando serve autonomia editoriale, gestione rapida dei prodotti e un pannello conosciuto.\nHeadless ha senso quando performance, frontend dedicato e collegamenti con sistemi esterni pesano di più.\nLa scelta si fa sul lavoro reale, non sulla moda del momento."
    },
    {
      "question": "Posso vendere online se ho già un negozio fisico?",
      "answer": "Sì, ed è spesso il caso più sensato.\nIl negozio fisico resta il punto forte, ma l’online copre chi non passa dalla tua zona, chi compra fuori orario e chi ti cerca dopo averti visto sui social o su Google.\nVendere solo a chi entra dalla porta è un limite tecnico, non una legge."
    },
    {
      "question": "Si possono importare prodotti già presenti in un gestionale?",
      "answer": "Sì, se il gestionale espone dati puliti o esportazioni affidabili.\nPrima si controllano campi, codici, varianti, stock, immagini e categorie.\nImportare male un catalogo crea caos: prodotti duplicati, disponibilità sbagliate, filtri inutili.\nMeglio sistemare la struttura prima, poi automatizzare."
    },
    {
      "question": "Come vengono gestiti pagamenti e sicurezza?",
      "answer": "Stripe, PayPal, bonifico e contrassegno si configurano secondo il flusso aziendale.\nI dati di pagamento non devono passare in modo improvvisato: si usano gateway seri, HTTPS, ruoli corretti, aggiornamenti controllati e accessi limitati.\nIl checkout è il punto dove il dilettantismo costa ordini persi."
    },
    {
      "question": "Il recupero carrello serve davvero?",
      "answer": "Serve quando è impostato bene.\nNon basta mandare una mail generica a chi abbandona.\nBisogna distinguere cliente registrato, carrello reale, consenso, tempi di invio e contenuto utile.\nIl recupero carrello non salva un checkout pessimo, ma recupera vendite che altrimenti spariscono."
    },
    {
      "question": "Cosa succede dopo il lancio?",
      "answer": "Dopo il lancio si guarda cosa accade davvero: ordini, errori pagamento, email non recapitate, prodotti più visti, carrelli abbandonati, feed per Shopping e pagine lente.\nUn e-commerce non finisce quando va online.\nInizia quando arrivano traffico, domande e ordini veri."
    }
  ],
  "awareness": {
    "title": "Il marketplace prende clienti che potevano essere tuoi",
    "subtitle": "Se non hai un canale diretto, qualcun altro intercetta la domanda al posto tuo.",
    "problems": [
      {
        "icon": "ph-storefront",
        "title": "Serranda contro 24/7",
        "desc": "Il negozio fisico vende quando è aperto.\nOnline, i concorrenti incassano anche la sera, nei festivi e mentre tu stai facendo magazzino."
      },
      {
        "icon": "ph-shopping-cart",
        "title": "Clienti regalati ai marketplace",
        "desc": "Amazon e piattaforme generiche non aspettano.\nSe il tuo catalogo non è acquistabile direttamente, prendono traffico, dati cliente e relazione commerciale."
      },
      {
        "icon": "ph-warning-circle",
        "title": "Plugin senza controllo",
        "desc": "Tema pesante, hosting condiviso, plugin scelti a caso, checkout lento.\nLa classica catena a sei mani dove nessuno possiede davvero il problema."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "DOPO LANCIO",
    "title": "Il negozio online va tenuto sotto pressione",
    "body": "Il lancio non è il traguardo.\nÈ il primo momento in cui il negozio incontra ordini veri, carte rifiutate, clienti indecisi, spedizioni fuori zona, email finite in spam e prodotti che Google interpreta male.\n\nQui si guarda la parte sporca dell’e-commerce: feed Shopping, schema Product e Offer, carrelli abbandonati, performance checkout, log degli errori, aggiornamenti WooCommerce, compatibilità plugin, magazzino e flussi email.\n\nLa catena di fornitori è il veleno: uno gestisce il tema, uno il server, uno il tracking, uno i pagamenti, e quando qualcosa si rompe parte il giro delle colpe.\nMeglio avere una regia tecnica chiara e interventi mirati sui punti che bloccano ordini e gestione.\nDecidi tu."
  }
};
