// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';
import { PROCESS_STEPS_IT } from './_shared/process';

export const MANUTENZIONE_SITI_SERVICE: ServiceDetail = {
  "slug": "manutenzione-siti",
  "title": "Manutenzione siti",
  "icon": "ph-wrench",
  "description": "Il sito non deve sparire mentre qualcuno cerca il backup giusto.\nMonitoring, update, fix e sicurezza sotto controllo.",
  "longDescription": "Un sito lasciato in mano alla catena agenzia-hosting-freelance-plugin diventa un punto cieco: si rompe, nessuno lo vede, poi parte la caccia al colpevole.\nLa manutenzione serve a togliere quel caos dal tavolo.\n\nBackup giornalieri, monitoring uptime, update controllati, patch di sicurezza, WAF base e fix urgenti entro 24h lavorative.\nSe un form resta rotto per 6 giorni, non è un dettaglio tecnico: sono richieste perse.\n\nNon è teatro tecnico, è presidio operativo.\nSai chi interviene, cosa è stato fatto e dove sono i ripristini.\nIl sito resta governato anche dopo il lancio, senza aspettare che siano i clienti a segnalare il disastro.\nPunto.",
  "features": [
    {
      "title": "Backup e ripristino",
      "description": "Backup automatici giornalieri del sito e del database, con ripristino on-demand quando serve tornare indietro.\nNiente caccia a file sparsi, zip vecchi o copie mezze rotte salvate da qualche parte."
    },
    {
      "title": "Monitoring uptime continuo",
      "description": "Controllo uptime 24/7 con alert quando il sito non risponde.\nIl problema viene visto prima che diventi una telefonata arrabbiata di un cliente o una giornata persa a capire cosa sia successo."
    },
    {
      "title": "Update senza caos",
      "description": "Aggiornamenti CMS, plugin e dipendenze gestiti con criterio, non cliccati a caso in produzione.\nPrima si guarda cosa cambia, poi si interviene.\nI plugin random lasciati indietro diventano debito tecnico, non destino."
    },
    {
      "title": "Fix urgenti tracciati",
      "description": "Per guasti bloccanti, intervento entro 24h lavorative con priorità chiara.\nForm rotti, pagine bianche, errori server, checkout fermo: si diagnostica, si corregge, si documenta.\nFine della storia."
    },
    {
      "title": "Patch e WAF base",
      "description": "Patch di sicurezza applicate quando escono vulnerabilità note, con WAF base per filtrare traffico sporco e tentativi banali.\nNon rende il sito invincibile, ma taglia molte porte lasciate aperte per incuria."
    },
    {
      "title": "Report mensile leggibile",
      "description": "Ogni mese ricevi un report comprensibile: uptime, backup, update, anomalie, interventi e punti da tenere d’occhio.\nNiente gergo per coprire il vuoto. Solo stato tecnico reale e prossime priorità."
    }
  ],
  "benefits": [
    "Scopri i problemi prima che li segnalino i clienti.",
    "Hai backup ripristinabili, non promesse perse in chat.",
    "Riduci vulnerabilità note da plugin e dipendenze vecchie.",
    "Sai chi interviene quando il sito si rompe.",
    "Ricevi un quadro tecnico mensile chiaro e leggibile."
  ],
  "process": PROCESS_STEPS_IT,
  "faqs": [
    {
      "question": "Cosa succede se il sito va offline?",
      "answer": "Il monitoring invia un alert quando il sito non risponde.\nDa lì si verifica se il problema è hosting, DNS, CMS, plugin, database o certificato SSL.\nSe rientra nel perimetro tecnico gestito, si interviene entro 24h lavorative.\nIl punto è evitare che il primo allarme arrivi da un cliente irritato."
    },
    {
      "question": "Gestisci anche siti WordPress già esistenti?",
      "answer": "Sì, dopo un controllo iniziale.\nPrima servono accessi, stato dei plugin, tema, hosting, backup, dominio e SSL.\nSe il sito è pieno di componenti abbandonati o codice modificato male, viene segnalato subito.\nLa manutenzione non deve coprire una bomba tecnica con una mano di vernice."
    },
    {
      "question": "Gli aggiornamenti possono rompere il sito?",
      "answer": "Sì, possono.\nPer questo non vanno fatti a raffica cliccando “aggiorna tutto”.\nPrima si controllano versioni, compatibilità, plugin critici e stato dei backup.\nSe qualcosa non torna, si procede con cautela o si segnala il rischio.\nAggiornare senza criterio è una roulette, non manutenzione."
    },
    {
      "question": "Cosa include il report mensile?",
      "answer": "Il report include uptime, backup eseguiti, update applicati, anomalie rilevate, interventi fatti, patch di sicurezza e note sui rinnovi.\nÈ scritto per essere capito da chi gestisce l’azienda, non solo da chi legge log server.\nDeve chiarire lo stato del sito, non riempire pagine."
    },
    {
      "question": "Puoi occuparti di dominio e SSL?",
      "answer": "Sì, se gli accessi sono disponibili e il registrar lo consente.\nSi monitorano scadenze, rinnovi e certificati SSL, così non diventano emergenze improvvise.\nDominio scaduto e SSL rotto sono problemi banali, ma quando nessuno li presidia bloccano tutto.\nDecidi tu se lasciarli al caso."
    },
    {
      "question": "Se il sito è stato fatto da un’altra agenzia?",
      "answer": "Si può gestire, ma prima va letto lo stato reale del progetto.\nAlcune agenzie consegnano siti ordinati, altre lasciano plugin duplicati, hosting condiviso saturo e accessi incompleti.\nL’audit serve proprio a capire cosa si può presidiare subito e cosa va sistemato prima."
    }
  ],
  "awareness": {
    "title": "Il sito non si mantiene da solo",
    "subtitle": "Dopo il lancio iniziano update, scadenze, bug, vulnerabilità e responsabilità tecniche lasciate spesso nel vuoto.",
    "problems": [
      {
        "icon": "ph-warning-circle",
        "title": "Offline invisibile",
        "desc": "Il sito cade e nessuno lo sa finché non chiama un cliente.\nA quel punto non è più un problema tecnico: è reputazione, vendite perse e rincorsa affannata."
      },
      {
        "icon": "ph-shield-check",
        "title": "Plugin vulnerabili",
        "desc": "Plugin WordPress non aggiornati, temi vecchi e dipendenze ferme aprono falle note.\nGli attacchi automatici non aspettano la riunione con l’agenzia o il ticket al provider."
      },
      {
        "icon": "ph-clock",
        "title": "Nessun responsabile",
        "desc": "Quando serve ripristinare un backup, parte il giro: hosting, agenzia, sviluppatore, account manager.\nIntanto il sito resta rotto e nessuno prende in mano il problema."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "POST LANCIO",
    "title": "La manutenzione è dove finisce il teatro",
    "body": "Il lancio del sito è solo il giorno zero.\nDopo arrivano update CMS, plugin che cambiano comportamento, certificati SSL in scadenza, hosting condivisi che rallentano, vulnerabilità pubbliche, form che smettono di inviare email e backup che nessuno ha mai provato a ripristinare.\n\nLa catena di fornitori è il problema: chi ha fatto il tema non gestisce il server, chi gestisce il server non tocca WordPress, chi ha venduto il progetto risponde con tre persone in copia.\nNel frattempo il sito è tuo, il danno è tuo, la fretta è tua.\n\nLa manutenzione mensile o annuale mette un presidio tecnico continuo: controllo, update, backup, patch, alert, fix urgenti e report leggibile.\nNon promette magia. Toglie improvvisazione. Punto."
  }
};
