// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';

export const SEO_SERVICE: ServiceDetail = {
  "slug": "seo",
  "title": "SEO & Visibilità",
  "icon": "ph-magnifying-glass",
  "description": "Se Google non porta traffico, non serve altro fumo:\nserve capire cosa blocca scansione, contenuti e fiducia locale.",
  "longDescription": "Un sito può essere online, bello da vedere e completamente invisibile.\nSuccede quando SEO tecnica, contenuti e presenza locale vengono spezzati tra agenzie, plugin casuali, hosting condivisi e report pieni di grafici inutili.\n\nQui si parte dai fatti: Core Web Vitals, crawlability, indexing, Search Console, contenuti, Google Business Profile, citation e recensioni.\nPoi si mette ordine: pagine leggibili da Google, schema markup corretto, piano editoriale settoriale e monitoraggio mensile che dice cosa sale, cosa resta fermo e perché.\n\nNessuna promessa da televendita sulla prima pagina.\nSolo lavoro tracciabile su ciò che impedisce al sito di essere trovato.\nPunto.",
  "features": [
    {
      "title": "Audit tecnico SEO",
      "description": "Analisi di Core Web Vitals, crawl, indexing, sitemap, robots, redirect, canonical, errori server e template lenti.\nPrima si scopre dove Google si incastra, poi si decide cosa sistemare."
    },
    {
      "title": "Keyword e contenuti",
      "description": "Ricerca keyword legata al settore, non alla fantasia del mese.\nSi costruisce un content plan con priorità chiare: pagine servizio, articoli, intenti di ricerca, cannibalizzazioni e opportunità realmente difendibili."
    },
    {
      "title": "SEO locale concreta",
      "description": "Google Business Profile, citation NAP, categorie, descrizioni, foto, servizi, recensioni e coerenza tra directory.\nSe l’attività lavora su territorio, la scheda locale non può restare abbandonata."
    },
    {
      "title": "On-page e schema",
      "description": "Titoli, heading, meta, internal linking, contenuti, dati strutturati e markup schema vengono sistemati pagina per pagina.\nNiente plugin lasciati a generare codice a caso senza controllo."
    },
    {
      "title": "Link building white-hat",
      "description": "Acquisizione link pulita, coerente con settore e reputazione.\nNiente pacchetti tossici, domini riciclati o scorciatoie che oggi sembrano furbe e domani diventano un problema."
    },
    {
      "title": "Monitoring mensile leggibile",
      "description": "Rank tracking, Google Search Console, GA4 e report mensili comprensibili.\nSi guarda cosa cambia, quali query entrano, quali pagine crescono e quali interventi hanno senso dopo."
    }
  ],
  "benefits": [
    "Un sito invisibile non serve a niente.",
    "Riduci sprechi su report SEO pieni di fumo.",
    "Metti ordine tra sito, contenuti e presenza locale.",
    "Vedi metriche leggibili, non screenshot senza contesto.",
    "Costruisci visibilità organica senza promesse da agenzia teatrale."
  ],
  "process": [
    {
      "step": 1,
      "title": "Analisi iniziale",
      "description": "Raccolgo accessi, dati GSC, GA4, CMS, hosting e Google Business.\nSe mancano dati, lo si dice subito. Il primo problema è spesso il disordine."
    },
    {
      "step": 2,
      "title": "Audit tecnico",
      "description": "Controllo performance, crawl, indexing, errori, template, contenuti duplicati, schema e configurazioni.\nOgni criticità viene ordinata per impatto reale, non per scenografia."
    },
    {
      "step": 3,
      "title": "Mappa keyword",
      "description": "Costruisco la mappa keyword in base a servizi, territorio, concorrenza e intenti di ricerca.\nOgni pagina deve avere un ruolo, altrimenti diventa rumore."
    },
    {
      "step": 4,
      "title": "Interventi mirati",
      "description": "Si sistemano pagine, markup, contenuti, internal linking, Google Business e citation.\nNiente riti SEO: solo interventi verificabili su ciò che blocca traffico e conversioni."
    },
    {
      "step": 5,
      "title": "Controllo mensile",
      "description": "Ogni mese si leggono ranking, query, clic, impression, conversioni e anomalie.\nSe una scelta non muove nulla, si cambia strada. Fine della storia."
    }
  ],
  "faqs": [
    {
      "question": "Mi garantisci la prima pagina su Google?",
      "answer": "No.\nChi promette la prima pagina sta vendendo una frase comoda, non un controllo reale su Google.\nSi può lavorare su tecnica, contenuti, autorevolezza, local SEO e misurazione.\nSi può aumentare la probabilità di posizionarsi bene su query sensate.\nMa promettere una posizione precisa è teatro da agenzia, non SEO seria."
    },
    {
      "question": "Il mio sito è online ma non riceve traffico organico. Da dove si parte?",
      "answer": "Si parte da Search Console, crawl, indexing, performance, struttura delle pagine e contenuti.\nSpesso il sito non viene trovato perché Google scansiona male, indicizza pagine sbagliate, trova contenuti deboli o riceve segnali locali incoerenti.\nPrima si misura il blocco, poi si interviene. Saltare questa fase significa lavorare al buio."
    },
    {
      "question": "Serve pubblicare articoli ogni settimana?",
      "answer": "Non per forza.\nPubblicare tanto non compensa una strategia sbagliata.\nPrima servono pagine servizio solide, keyword chiare, struttura interna pulita e contenuti che rispondano a ricerche reali.\nPoi si decide se il blog ha senso, con quali temi e con quale frequenza.\nIl calendario editoriale non deve diventare una fabbrica di riempitivi."
    },
    {
      "question": "Google Business Profile conta davvero per la SEO locale?",
      "answer": "Sì, soprattutto se lavori su una zona geografica precisa.\nUna scheda incompleta, recensioni ferme, categorie sbagliate e NAP incoerente tra directory mandano segnali deboli.\nGoogle Business non è una vetrina da aprire e dimenticare: va tenuta ordinata, aggiornata e coerente con sito, servizi e territorio."
    },
    {
      "question": "Cosa succede se ho già un’agenzia SEO?",
      "answer": "Si guarda cosa è stato fatto, cosa è misurabile e cosa resta fermo.\nSe ci sono report mensili senza accesso ai dati, attività vaghe o promesse non verificabili, il problema non è personale: è operativo.\nUna SEO seria lascia tracce controllabili in GSC, GA4, ranking, pagine ottimizzate e decisioni documentate."
    },
    {
      "question": "Quanto tempo serve per vedere risultati?",
      "answer": "Dipende da stato tecnico, concorrenza, autorità del dominio, storico del sito e solidità dei contenuti.\nLa SEO non è un interruttore.\nAlcuni problemi tecnici producono effetti rapidi dopo la correzione, altre attività richiedono continuità.\nL’importante è leggere i segnali giusti: query, impression, clic, posizioni e conversioni. Decidi tu."
    }
  ],
  "awareness": {
    "title": "Il traffico organico non sparisce per caso",
    "subtitle": "Di solito viene soffocato da tecnica trascurata, contenuti deboli e presenza locale lasciata a metà.",
    "problems": [
      {
        "icon": "ph-warning-circle",
        "title": "Sito invisibile",
        "desc": "Il sito esiste, ma Google lo legge male o non lo considera rilevante.\nPagine lente, struttura confusa, contenuti copiati e indexing sporco bloccano traffico prima ancora delle keyword."
      },
      {
        "icon": "ph-chart-line-down",
        "title": "Report senza prove",
        "desc": "Grafici colorati, parole inglesi e nessuna decisione chiara.\nSe il report non collega attività, dati e impatto, non sta guidando la SEO: sta riempiendo una riunione."
      },
      {
        "icon": "ph-storefront",
        "title": "Locale abbandonato",
        "desc": "Google Business non aggiornato, recensioni ferme, indirizzi scritti in modi diversi e directory lasciate al caso.\nPer chi lavora sul territorio, questa incuria costa visibilità ogni giorno."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "DOPO LANCIO",
    "title": "La SEO non finisce quando pubblichi",
    "body": "Il problema della SEO spezzettata è sempre lo stesso: uno tocca il sito, uno scrive testi, uno installa plugin, uno guarda Google Business ogni tanto e nessuno risponde dei risultati.\n\nDopo il lancio si tiene tutto nello stesso quadro: performance, scansione, pagine indicizzate, keyword, contenuti, schema markup, link, scheda locale, citation e recensioni.\nOgni mese si controlla cosa Google vede, cosa premia, cosa ignora e cosa sta peggiorando.\n\nSe l’hosting condiviso rallenta tutto, si segnala.\nSe un plugin sporca il markup, si rimuove o si sostituisce.\nSe il content plan produce pagine inutili, si taglia.\nLa SEO non ha bisogno di teatro: ha bisogno di responsabilità tecnica, criterio editoriale e continuità. Punto."
  }
};
