// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';

export const SVILUPPO_WEB_SERVICE: ServiceDetail = {
  "slug": "sviluppo-web",
  "title": "Sviluppo Web",
  "icon": "ph-code",
  "description": "Web app, dashboard e automazioni per togliere processi da Excel, email e WhatsApp.\nPunto.",
  "longDescription": "Quando un processo vive tra Excel, email, WhatsApp e tre tool SaaS che non si parlano, ogni crescita diventa attrito.\nIl cliente chiama per sapere lo stato, il team copia dati a mano, qualcuno rincorre password, export e notifiche perse.\n\nLo sviluppo web serio parte da lì: mappare il flusso reale, tagliare i passaggi inutili, costruire una web app con login, ruoli, dashboard, API e automazioni.\nIn una pratica interna passata da 7 passaggi manuali a 3, il guadagno non era estetico: era operativo.\n\nCodice pulito, database sensato, performance da SaaS moderno, niente plugin incollati perché “era più veloce”.\nIl risultato è un sistema operativo per il lavoro quotidiano: meno rincorse, meno errori, più controllo.\nFine della storia.",
  "features": [
    {
      "title": "Web app custom",
      "description": "Applicazioni web costruite sul processo reale, non su un tema riadattato.\nArea operativa, gestione dati, flussi interni, notifiche, ruoli e permessi: tutto progettato per ridurre passaggi manuali e punti ciechi."
    },
    {
      "title": "API e integrazioni",
      "description": "Collego CRM, ERP, gestionali, gateway, email provider e piattaforme esterne con API REST o GraphQL.\nNiente copia-incolla tra pannelli diversi: i dati entrano, escono e restano coerenti."
    },
    {
      "title": "Aree clienti private",
      "description": "Login, ruoli, permessi, documenti, pratiche, ordini e stato avanzamento in un’area riservata.\nIl cliente vede quello che deve vedere, il team smette di rispondere sempre alle stesse richieste."
    },
    {
      "title": "Dashboard operative live",
      "description": "Dashboard con metriche, attività, code, stati e dati real-time operativi.\nNon 14 grafici decorativi, ma pannelli per decidere cosa fare adesso."
    },
    {
      "title": "Automazioni e AI",
      "description": "Automazioni per notifiche, follow-up, generazione documenti, smistamento richieste e chatbot AI collegati ai dati aziendali.\nL’obiettivo è togliere lavoro ripetitivo, non aggiungere un altro giocattolo da mantenere."
    },
    {
      "title": "Architettura scalabile",
      "description": "Stack moderno con Next.js, Node, Postgres e servizi scelti con criterio.\nCodice leggibile, struttura modulare, deploy controllato, log e basi tecniche che non crollano appena aumentano utenti e dati."
    }
  ],
  "benefits": [
    "Meno lavoro manuale tra fogli, email e chat sparse.",
    "Clienti aggiornati senza telefonate continue allo staff operativo.",
    "Dati coerenti tra CRM, ERP, dashboard e strumenti esterni.",
    "Processi interni più rapidi, misurabili e facili da correggere.",
    "Codice mantenibile senza dipendere da plugin casuali."
  ],
  "process": [
    {
      "step": 1,
      "title": "Mappa processi",
      "description": "Parto dai flussi reali: chi fa cosa, dove si perdono dati, quali passaggi vengono ripetuti a mano e quali tool stanno creando attrito."
    },
    {
      "step": 2,
      "title": "Disegno tecnico",
      "description": "Definisco architettura, database, ruoli, integrazioni, API e priorità.\nPrima si chiarisce il sistema, poi si scrive codice. Non il contrario."
    },
    {
      "step": 3,
      "title": "Sviluppo modulare",
      "description": "Costruisco per blocchi verificabili: login, dashboard, workflow, integrazioni, automazioni.\nOgni parte viene testata sul caso d’uso reale, non su una demo pulita."
    },
    {
      "step": 4,
      "title": "Test operativi",
      "description": "Simulo dati, errori, utenti, permessi e casi limite: richieste doppie, connessioni lente, input sbagliati, ruoli non autorizzati.\nUna web app deve reggere il lavoro sporco, non solo una demo pulita."
    },
    {
      "step": 5,
      "title": "Deploy controllato",
      "description": "Pubblicazione, monitoraggio, backup, log e passaggio operativo.\nDopo il lancio non sparisce nessuno: si misura, si corregge, si mantiene il sistema sotto controllo."
    }
  ],
  "faqs": [
    {
      "question": "Quando serve una web app custom invece di un SaaS già pronto?",
      "answer": "Serve quando il lavoro reale non entra più dentro tool generici.\nSe usi Calendly, fogli, CRM, email, WhatsApp e un gestionale separato per completare un solo processo, il problema non è la voglia di ordine: è l’architettura.\nUna web app custom ha senso quando vuoi un flusso unico, controllabile e collegato ai tuoi dati."
    },
    {
      "question": "Possiamo integrare strumenti che usiamo già?",
      "answer": "Sì, se espongono API, webhook, export affidabili o un modo tecnico decente per dialogare.\nCRM, ERP, pagamenti, email, calendari, piattaforme logistiche e database esterni si possono collegare.\nPrima però va verificato cosa permette davvero ogni sistema, perché molti tool promettono integrazioni e poi lasciano solo mezze porte aperte."
    },
    {
      "question": "Si può creare un’area clienti con stato pratiche o ordini?",
      "answer": "Sì. È uno dei casi più sensati: il cliente accede, vede documenti, avanzamento, scadenze, ordini, richieste aperte e notifiche.\nIl team interno aggiorna una sola volta e l’informazione diventa visibile dove serve.\nMeno telefonate, meno email duplicate, meno “mi fate sapere a che punto siamo?”."
    },
    {
      "question": "Che differenza c’è rispetto a un sito WordPress con plugin?",
      "answer": "Un sito con plugin può andare bene per contenuti semplici.\nQuando però servono ruoli, permessi, dati strutturati, automazioni, API e dashboard operative, i plugin diventano una pila fragile.\nOgni aggiornamento può rompere qualcosa, ogni estensione aggiunge dipendenze, ogni workaround diventa debito tecnico.\nQui si costruisce il sistema, non si impila roba."
    },
    {
      "question": "Come gestite sicurezza, login e permessi?",
      "answer": "Ruoli, permessi, sessioni, validazioni, log, protezione degli endpoint e separazione dei dati devono stare nell’architettura.\nNon sono controlli aggiunti alla fine.\nUn’area privata non è solo una schermata con password: è un confine tecnico chiaro tra utenti, dati e azioni consentite."
    },
    {
      "question": "Cosa succede dopo il lancio?",
      "answer": "Dopo il lancio si guarda il sistema mentre lavora: log, errori, tempi di risposta, passaggi bloccati, richieste degli utenti interni, dati sporchi.\nPoi si corregge per priorità.\nUna web app aziendale non è una vetrina da consegnare e salutare: è uno strumento operativo che va mantenuto lucido."
    }
  ],
  "awareness": {
    "title": "Il problema non è digitale, è operativo",
    "subtitle": "Se ogni dato passa da tre persone e quattro tool, il collo di bottiglia non sparisce da solo.",
    "problems": [
      {
        "icon": "ph-warning-circle",
        "title": "Processi sparsi",
        "desc": "Excel, email e WhatsApp reggono finché il volume è basso.\nPoi arrivano duplicati, versioni diverse, allegati persi e decisioni prese su dati vecchi.\nPunto."
      },
      {
        "icon": "ph-credit-card",
        "title": "SaaS che non parlano",
        "desc": "Paghi più piattaforme per fare pezzi dello stesso lavoro.\nUna prenota, una manda email, una archivia, una misura.\nIl team diventa il connettore umano tra strumenti scollegati."
      },
      {
        "icon": "ph-clock",
        "title": "Clienti in attesa",
        "desc": "Quando il cliente deve chiamare per sapere stato pratiche, ordini o documenti, il sistema sta già mostrando il suo limite.\nL’informazione esiste, ma resta chiusa nel posto sbagliato."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "POST LANCIO",
    "title": "Il codice deve reggere il lavoro vero",
    "body": "Una web app custom non finisce quando va online.\nFinisce quando il team la usa senza tornare a Excel dopo due settimane.\nPer questo il post-lancio conta: log chiari, monitoraggio, backup, correzione dei flussi, nuove integrazioni quando il processo cambia.\n\nIl nemico è la catena di fornitori: chi ha fatto il design, chi ha montato il plugin, chi gestisce hosting condiviso, chi risponde solo aprendo ticket.\nTroppi passaggi, troppe mani, nessuno che possiede davvero il sistema.\n\nQui il perimetro tecnico resta leggibile: codice, API, database, automazioni, deploy e manutenzione parlano la stessa lingua.\nSe serve aggiungere una dashboard, collegare un CRM, automatizzare un documento o esporre un endpoint, non si riparte da zero.\nSi estende una base pensata per crescere.\nDecidi tu."
  }
};
