// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';
import { PROCESS_STEPS_IT } from './_shared/process';

export const WEB_DESIGN_SERVICE: ServiceDetail = {
  "slug": "web-design",
  "title": "Web Design",
  "icon": "ph-globe",
  "description": "Web design veloce, chiaro, governabile.\nBasta template riciclati, plugin a caso e sparizioni dopo il lancio.",
  "longDescription": "Un sito vecchio non è un cimelio: è un attrito commerciale.\nSe non porta contatti, se sembra uguale al concorrente o se dipende da plugin messi lì per tappare buchi, il problema non è “rifare la grafica”.\nIl problema è rimettere ordine.\n\nProgetto siti vetrina, istituzionali e portfolio con struttura chiara, web design riconoscibile e sviluppo pulito, in WordPress quando ha senso o custom con Astro e Next.js quando serve controllo.\nDentro ci sono SEO tecnica base, GDPR, Google Business, Analytics e Search Console.\n\nIn un rifacimento locale il tempo per arrivare al form è sceso da 6 tocchi a 2: non magia, solo architettura dell’informazione fatta bene.\nDopo il lancio non sparisco: un anno di assistenza è incluso.\nPunto.",
  "features": [
    {
      "title": "Design senza template",
      "description": "Niente tema comprato, cambiato nei colori e consegnato come progetto.\nIl layout parte dai contenuti, dal tipo di cliente che deve capire cosa fai e dalle azioni che il sito deve rendere facili."
    },
    {
      "title": "Sviluppo mobile-first",
      "description": "Il sito viene costruito prima per schermi reali, non per screenshot da desktop.\nNavigazione, testi, form, immagini e pulsanti vengono controllati su mobile, tablet e desktop prima della messa online."
    },
    {
      "title": "WordPress o custom",
      "description": "WordPress se ti serve autonomia sui contenuti e una gestione semplice.\nAstro o Next.js se servono performance, controllo tecnico e meno dipendenze.\nLa scelta non la decide la moda del momento."
    },
    {
      "title": "SEO tecnica base",
      "description": "Imposto sitemap, robots, metadati, schema essenziale, redirect necessari e struttura leggibile.\nNon prometto magie su Google: tolgo gli errori tecnici che impediscono al sito di essere letto bene."
    },
    {
      "title": "GDPR e tracciamenti",
      "description": "Cookie, privacy, Analytics e Search Console vengono configurati con criterio.\nNiente banner copiati male, script incollati ovunque o tracciamenti attivi prima del consenso quando non devono esserlo."
    },
    {
      "title": "Assistenza per un anno",
      "description": "Dopo il lancio resti coperto per interventi tecnici, piccoli aggiustamenti, controlli e problemi ordinari.\nNon finisci nel classico vuoto tra designer, hosting, sviluppatore e qualcuno che non risponde più."
    }
  ],
  "benefits": [
    "Un sito riconoscibile, non il clone del concorrente.",
    "Meno plugin inutili, meno dipendenze, meno rotture future.",
    "Contatti più semplici da generare e da misurare.",
    "Asset tecnici impostati bene fin dal lancio.",
    "Un riferimento unico anche dopo la pubblicazione."
  ],
  "process": PROCESS_STEPS_IT,
  "faqs": [
    {
      "question": "Il mio sito è vecchio: conviene rifarlo o sistemarlo?",
      "answer": "Dipende da cosa c’è sotto.\nSe il sito ha struttura chiara, contenuti recuperabili e una base tecnica decente, si può intervenire senza buttare tutto.\nSe invece è un tema pieno di plugin, lento, fragile e non tracciato, rifarlo è spesso più pulito.\nPrima si valuta lo stato reale, non l’età anagrafica."
    },
    {
      "question": "Meglio WordPress o sviluppo custom?",
      "answer": "WordPress è adatto quando vuoi aggiornare pagine, articoli e contenuti in autonomia con una gestione familiare.\nLo sviluppo custom ha senso quando vuoi più velocità, meno componenti inutili e maggiore controllo tecnico.\nNon esiste una scelta universale: esiste il contesto giusto.\nIl resto è religione da riunione."
    },
    {
      "question": "Il sito sarà modificabile dopo la consegna?",
      "answer": "Sì, ma con un criterio diverso in base alla tecnologia scelta.\nIn WordPress puoi gestire contenuti e sezioni previste.\nIn un sito custom le modifiche passano da una struttura più controllata, spesso più stabile.\nL’obiettivo è evitare il caos: ogni libertà totale, senza regole, diventa debito tecnico."
    },
    {
      "question": "Vi occupate anche di dominio, hosting e email?",
      "answer": "Posso coordinare dominio, hosting, DNS e aspetti tecnici collegati al sito.\nSe la situazione attuale è un mosaico di fornitori, accessi persi e pannelli mai visti, si rimette ordine prima del lancio.\nHosting condiviso lento e configurazioni opache non sono dettagli: sono problemi che tornano sempre."
    },
    {
      "question": "La SEO è inclusa nel lavoro sul sito?",
      "answer": "È inclusa la parte tecnica base: struttura corretta, metadati, sitemap, robots, schema essenziale, performance e collegamento a Search Console.\nNon è una campagna SEO continuativa e non promette posizioni garantite.\nServe a mettere il sito nelle condizioni corrette per essere letto, indicizzato e monitorato."
    },
    {
      "question": "Cosa succede dopo che il sito va online?",
      "answer": "Dopo il lancio controllo form, tracciamenti, indicizzazione, errori tecnici e dettagli che spesso emergono solo online.\nÈ incluso un anno di assistenza tecnica per evitare il classico abbandono post-pubblicazione.\nIl sito non viene lanciato e lasciato lì come un file zip dimenticato.\nFine della storia."
    }
  ],
  "awareness": {
    "title": "Il problema non è solo il sito brutto",
    "subtitle": "È la catena tecnica fragile che lo rende lento, anonimo e impossibile da gestire.",
    "problems": [
      {
        "icon": "ph-chart-line-down",
        "title": "Zero contatti reali",
        "desc": "Il sito esiste, ma non produce richieste.\nPagine vaghe, form nascosti, testi intercambiabili e nessun tracciamento serio.\nCosì non sai nemmeno dove si rompe il percorso."
      },
      {
        "icon": "ph-palette",
        "title": "Template già visto",
        "desc": "Stessa struttura, stesse icone, stesso tono del concorrente.\nCambia il logo, resta l’effetto copia.\nUn’attività seria non può presentarsi con una maschera presa dallo scaffale."
      },
      {
        "icon": "ph-warning-circle",
        "title": "Agenzia sparita",
        "desc": "Al lancio tutti presenti.\nDopo, nessuno risponde.\nIl sito resta appeso tra hosting, plugin, aggiornamenti, credenziali e responsabilità vaghe.\nQuando qualcosa si rompe, inizia il giro dei rimbalzi."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "DOPO LANCIO",
    "title": "Il sito non finisce quando va online",
    "body": "La parte più ignorata del web design è quella che arriva dopo la pubblicazione.\nÈ lì che si vede se il progetto è stato costruito bene o se era solo una consegna impacchettata.\n\nForm che non inviano, cookie configurati male, Search Console mai aperta, Analytics messo a metà, plugin che chiedono aggiornamenti ogni settimana, hosting condiviso che rallenta tutto appena arrivano visite.\nLa catena di fornitori moltiplica il problema: chi ha fatto il design non tocca il server, chi gestisce il server non sa del form, chi ha installato i plugin non risponde.\n\nQui il perimetro è chiaro: sito, setup tecnico, GDPR, strumenti Google e assistenza per un anno.\nUn referente, meno passaggi, meno scuse.\nDecidi tu."
  }
};
