// AUTO-GENERATED by scripts/generate-services-copy.mjs — refactor 2026-05.
// Do not edit by hand; regenerate via the script for full coherence.

import type { ServiceDetail } from '../services-detail';

export const WORDPRESS_MIGRAZIONE_SERVICE: ServiceDetail = {
  "slug": "wordpress-migrazione",
  "title": "Migrazione & Hosting WordPress",
  "icon": "ph-cloud-arrow-up",
  "description": "Porto WordPress su hosting serio senza spegnere il sito,\nrompere link o lasciare DNS al caso.",
  "longDescription": "Un WordPress lento non è quasi mai colpa del tema soltanto.\nSpesso è una catena sporca: hosting condiviso saturo, plugin cache messi a caso, DNS gestiti da qualcuno che non risponde, SSL dimenticato.\n\nLa migrazione serve a togliere il sito da quel pantano senza farlo sparire online.\nSi lavora su staging, si prepara il nuovo hosting, si replica il sito, si controllano link, immagini, redirect, certificati, cache e CDN prima del cambio definitivo.\n\nPoi si monitora il passaggio, non si lancia e si scappa.\nIl risultato è un WordPress più rapido, più stabile e con meno fornitori che si rimpallano la colpa. Punto.",
  "features": [
    {
      "title": "Migrazione senza buio",
      "description": "Il sito viene copiato e testato su staging prima del cambio.\nIl passaggio avviene quando hosting, database, file, redirect e SSL sono pronti, così il pubblico non trova pagine rotte o schermate bianche."
    },
    {
      "title": "Hosting WordPress tuned",
      "description": "Scelgo e configuro un ambiente adatto al sito: WP Engine, SiteGround o hosting ottimizzato.\nNiente server condivisi pieni di siti sconosciuti che rallentano ogni richiesta e fanno perdere tempo a chi visita."
    },
    {
      "title": "DNS e SSL gestiti",
      "description": "Il cambio DNS viene pianificato con TTL, record corretti e certificati SSL attivi.\nNon resta un dominio appeso tra vecchio e nuovo host mentre ognuno dice che dipende da qualcun altro."
    },
    {
      "title": "CDN e cache pulite",
      "description": "Configuro Cloudflare, WP Rocket o stack equivalente senza accumulare plugin random.\nCache pagina, browser, immagini e regole di esclusione vengono impostate in modo leggibile, così non rompono carrelli, form o aree riservate."
    },
    {
      "title": "Redirect sotto controllo",
      "description": "Controllo URL, media, permalink e redirect dopo la migrazione.\nIl cambio host non deve bruciare pagine indicizzate, immagini, tracciamenti o collegamenti interni perché qualcuno ha spostato file a mano."
    },
    {
      "title": "Documentazione finale chiara",
      "description": "Alla fine restano credenziali, accessi, hosting, DNS, CDN e note tecniche in un documento ordinato.\nChi gestisce il sito dopo non deve scavare tra email vecchie e chat di fornitori spariti."
    }
  ],
  "benefits": [
    "Sito trasferito senza finestre offline visibili ai clienti.",
    "Caricamenti più rapidi su hosting adatto a WordPress.",
    "DNS, SSL e CDN documentati in un unico posto.",
    "Redirect e link controllati prima che Google trovi errori.",
    "Meno passaggi di mano tra hosting, agenzia e tecnico."
  ],
  "process": [
    {
      "step": 1,
      "title": "Audit tecnico",
      "description": "Controllo hosting attuale, peso del sito, plugin, DNS, SSL, redirect e criticità SEO.\nPrima si capisce dove il sistema perde tempo, poi si tocca produzione."
    },
    {
      "step": 2,
      "title": "Staging verificato",
      "description": "Creo una copia su ambiente separato con file, database, media e configurazioni.\nQui si fanno prove, correzioni e misure senza mettere a rischio il sito live o perdere ordini durante il cambio."
    },
    {
      "step": 3,
      "title": "Hosting nuovo",
      "description": "Preparo server, PHP, database, cache, backup, SSL e regole principali.\nIl sito arriva su una base già pronta, non su un pannello lasciato a metà."
    },
    {
      "step": 4,
      "title": "Cambio controllato",
      "description": "Eseguo sincronizzazione finale, blocco modifiche critiche, aggiorno DNS e verifico propagazione.\nIl passaggio viene seguito mentre accade, non letto il giorno dopo."
    },
    {
      "step": 5,
      "title": "Test finali",
      "description": "Controllo pagine, immagini, form, redirect, velocità, cache e certificati.\nPoi consegno note tecniche e accessi ordinati. Fine della storia."
    }
  ],
  "faqs": [
    {
      "question": "Il sito resta online durante la migrazione?",
      "answer": "Sì, l’obiettivo è evitare downtime visibile.\nSi lavora su staging, si prepara il nuovo hosting e si fa il cambio DNS solo quando la copia è pronta.\nPossono esserci pochi minuti di assestamento tecnico durante la propagazione, ma non si spegne il sito per ore come succede nei passaggi improvvisati."
    },
    {
      "question": "Cosa succede se il sito ha molte immagini o plugin pesanti?",
      "answer": "Si analizza prima il peso reale: media, database, plugin, backup vecchi, cache e cartelle inutili.\nLa migrazione non deve portare spazzatura da un server all’altro senza guardarla.\nLe parti critiche vengono copiate, testate e, quando serve, alleggerite prima del rilascio."
    },
    {
      "question": "Gestisci anche dominio, DNS e certificato SSL?",
      "answer": "Sì.\nDNS e SSL sono spesso il punto in cui il sito finisce offline perché nessuno li considera propri.\nRecord, TTL, certificato, redirect HTTPS e CDN vengono trattati come parte del lavoro, non come dettaglio laterale da scaricare sull’hosting."
    },
    {
      "question": "La migrazione può danneggiare la SEO?",
      "answer": "Può succedere se link, redirect, media o permalink vengono rotti.\nPer questo controllo URL principali, redirect esistenti, immagini, canonical e risposte HTTP dopo il passaggio.\nCambiare host non deve significare far trovare a Google una pila di errori."
    },
    {
      "question": "Posso scegliere io il nuovo hosting?",
      "answer": "Sì, se l’hosting è adatto al sito e non crea problemi tecnici prevedibili.\nSe invece il piano è troppo debole, troppo chiuso o pieno di limiti, te lo dico prima.\nMeglio chiarirlo subito che migrare su un altro collo di bottiglia."
    },
    {
      "question": "Dopo la migrazione chi tiene gli accessi?",
      "answer": "Gli accessi restano tuoi.\nConsegno una documentazione ordinata con hosting, dominio, DNS, CDN, WordPress e note tecniche importanti.\nBasta caccia al tesoro tra account personali, agenzie passate e pannelli che nessuno sa più aprire. Decidi tu."
    }
  ],
  "awareness": {
    "title": "Il problema non è WordPress, è la catena",
    "subtitle": "Quando hosting, DNS, cache e plugin sono gestiti a pezzi, ogni rallentamento diventa una caccia al colpevole.",
    "problems": [
      {
        "icon": "ph-clock",
        "title": "Hosting condiviso lento",
        "desc": "Il sito carica in otto o dieci secondi perché vive su un server pieno, con risorse contese e cache casuale.\nPoi qualcuno dice che WordPress è pesante. Comodo."
      },
      {
        "icon": "ph-warning-circle",
        "title": "Migrazione fatta male",
        "desc": "Un cambio host senza staging può rompere immagini, permalink, redirect e tracciamenti.\nIl sito torna online, ma con pagine morte e traffico organico ferito."
      },
      {
        "icon": "ph-lock",
        "title": "SSL e DNS ignorati",
        "desc": "Quando certificati, record e dominio non hanno un responsabile chiaro, basta una scadenza o un cambio sbagliato per mandare tutto offline."
      }
    ]
  },
  "expandedScope": {
    "eyebrow": "DOPO LIVE",
    "title": "Il lavoro serio inizia dopo il cambio DNS",
    "body": "Una migrazione WordPress non finisce quando il dominio punta al nuovo server. Quello è solo il momento in cui i problemi nascosti provano a uscire: cache che serve pagine vecchie, CDN che blocca file, SSL non allineato, redirect mancanti, immagini con percorso assoluto, plugin che scrivono ancora sul vecchio host.\n\nPer questo il post-migrazione conta quanto il trasferimento.\nControllo risposta delle pagine, risorse statiche, form, login, pannello admin, sitemap, redirect e velocità reale.\n\nSe serve, si ritocca la cache, si pulisce il database, si sistema Cloudflare e si mette ordine negli accessi.\n\nNiente passaggi a sei mani tra agenzia, hosting, tecnico DNS e plugin lasciato lì a fatturare canone. Un responsabile tecnico, una lista di controlli, un sito che resta in piedi. Punto."
  }
};
