import { useQuery } from '@tanstack/react-query';
import { CheckCircle2, XCircle, Info, ExternalLink } from 'lucide-react';
import { apiFetch } from '@/lib/api';

interface GeoCheck {
  id: string;
  label: string;
  passed: boolean | null;
  weight: number;
  detail: string;
  anchor: string;
}
interface AdminAction {
  title: string;
  priority: string;
  why: string;
  how: string;
}
interface GeoAudit {
  id: string;
  url: string;
  score: number;
  checks: GeoCheck[];
  aiActions: { userSummary: string; adminActions: AdminAction[] } | null;
  wantsIntervention: boolean | null;
}

function scoreColor(score: number): string {
  if (score >= 75) return 'text-green-600';
  if (score >= 50) return 'text-amber-600';
  return 'text-red-600';
}

/**
 * Shows the GEO Audit attached to a lead (if any). Returns null when the lead
 * was not generated by the GEO Audit tool, so it can be rendered unconditionally.
 */
export function GeoAuditPanel({ leadId }: { leadId: string }) {
  const { data } = useQuery<{ audit: GeoAudit | null }>({
    queryKey: ['geo-audit', leadId],
    queryFn: () => apiFetch(`/api/geo-audit/by-lead/${leadId}`),
  });

  const audit = data?.audit;
  if (!audit) return null;

  const failed = audit.checks.filter((c) => c.passed === false);

  return (
    <div className="space-y-3 pt-2 border-t">
      <div className="flex items-center justify-between">
        <span className="text-sm font-medium">GEO Audit</span>
        <span className={`text-lg font-bold ${scoreColor(audit.score)}`}>{audit.score}/100</span>
      </div>

      <a
        href={audit.url}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:underline break-all"
      >
        {audit.url} <ExternalLink className="h-3 w-3 shrink-0" />
      </a>

      {audit.wantsIntervention !== null && (
        <p className="text-xs">
          {audit.wantsIntervention
            ? '🟢 Vuole che te ne occupi tu'
            : '⚪ Preferisce risolvere da solo'}
        </p>
      )}

      {/* Checks */}
      <ul className="space-y-1.5">
        {audit.checks.map((c) => (
          <li key={c.id} className="flex items-start gap-2 text-xs">
            {c.passed === null ? (
              <Info className="h-3.5 w-3.5 text-muted-foreground shrink-0 mt-0.5" />
            ) : c.passed ? (
              <CheckCircle2 className="h-3.5 w-3.5 text-green-600 shrink-0 mt-0.5" />
            ) : (
              <XCircle className="h-3.5 w-3.5 text-red-600 shrink-0 mt-0.5" />
            )}
            <span className={c.passed === false ? 'text-foreground' : 'text-muted-foreground'}>
              <span className="font-medium">{c.label}</span> — {c.detail}
            </span>
          </li>
        ))}
      </ul>

      {/* Actions to propose */}
      {audit.aiActions?.adminActions?.length ? (
        <div className="space-y-2">
          <p className="text-xs font-medium">Azioni da proporre</p>
          <ol className="space-y-2">
            {audit.aiActions.adminActions.map((a, i) => (
              <li key={i} className="text-xs">
                <p className="font-medium">
                  <span className="uppercase text-[10px] mr-1.5 text-muted-foreground">{a.priority}</span>
                  {a.title}
                </p>
                <p className="text-muted-foreground">{a.why}</p>
                <p>{a.how}</p>
              </li>
            ))}
          </ol>
        </div>
      ) : null}

      {failed.length === 0 && (
        <p className="text-xs text-green-600">Nessun criterio critico fallito.</p>
      )}
    </div>
  );
}
