-- 110_whatsapp_workflow.sql
-- Phase 3 of the WhatsApp inbox overhaul: turn each conversation into a
-- workable ticket. Adds pin / mute / status / internal note / per-conv AI
-- instructions / last-read marker, plus a free-form tag table and a
-- scheduled-message queue consumed by the cron engine.
--
-- All ALTERs are idempotent (IF NOT EXISTS). Append-only per CLAUDE.md
-- §architecture invariant 7 — do not edit this file once shipped.

ALTER TABLE public.whatsapp_conversations
  ADD COLUMN IF NOT EXISTS pinned          BOOLEAN     NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS muted_until     TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS status          TEXT        NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS internal_note   TEXT        NULL,
  ADD COLUMN IF NOT EXISTS ai_instructions TEXT        NULL,
  ADD COLUMN IF NOT EXISTS last_read_at    TIMESTAMPTZ NULL;

-- status is a soft enum — keep it as TEXT but constrain at the column level
-- so writers can't drift. The CHECK is added separately because ALTER TABLE
-- ADD CHECK on an existing populated column wants every row to satisfy it,
-- which is fine here (default is 'open').
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'whatsapp_conversations_status_chk'
  ) THEN
    ALTER TABLE public.whatsapp_conversations
      ADD CONSTRAINT whatsapp_conversations_status_chk
      CHECK (status IN ('open','waiting','resolved'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_wa_conv_pinned
  ON public.whatsapp_conversations (pinned)
  WHERE pinned = TRUE;

CREATE INDEX IF NOT EXISTS idx_wa_conv_status
  ON public.whatsapp_conversations (status);

CREATE INDEX IF NOT EXISTS idx_wa_conv_muted
  ON public.whatsapp_conversations (muted_until)
  WHERE muted_until IS NOT NULL;

-- Tags. A side table keeps the chip-style UX honest: one row per tag, with
-- a partial unique on (conversation_id, lower(tag)) so case-insensitive
-- duplicates are rejected at the DB layer.
CREATE TABLE IF NOT EXISTS public.whatsapp_conversation_tags (
  conversation_id UUID NOT NULL REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
  tag             TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, tag)
);

CREATE INDEX IF NOT EXISTS idx_wa_conv_tag_tag
  ON public.whatsapp_conversation_tags (tag);

CREATE INDEX IF NOT EXISTS idx_wa_conv_tag_conv
  ON public.whatsapp_conversation_tags (conversation_id);

-- Scheduled messages queue. The whatsapp-scheduled cron job (apps/api/src/cron)
-- polls rows where send_at <= now() AND sent_at IS NULL AND error IS NULL,
-- fires them, then either fills sent_at OR sets error + leaves sent_at NULL.
-- We deliberately don't auto-retry on error: the admin sees the failure in
-- the list and decides whether to reschedule.
CREATE TABLE IF NOT EXISTS public.whatsapp_scheduled_messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.whatsapp_conversations(id) ON DELETE CASCADE,
  body            TEXT NOT NULL,
  media_path      TEXT NULL,
  media_mime      TEXT NULL,
  category        TEXT NOT NULL DEFAULT 'operational'
                  CHECK (category IN ('transactional','operational','marketing')),
  send_at         TIMESTAMPTZ NOT NULL,
  created_by      UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at         TIMESTAMPTZ NULL,
  sent_message_id UUID NULL REFERENCES public.whatsapp_messages(id) ON DELETE SET NULL,
  error           TEXT NULL,
  attempts        INTEGER NOT NULL DEFAULT 0
);

-- Cron worker reads this index every minute; partial keeps it tiny.
CREATE INDEX IF NOT EXISTS idx_wa_sched_due
  ON public.whatsapp_scheduled_messages (send_at)
  WHERE sent_at IS NULL AND error IS NULL;

CREATE INDEX IF NOT EXISTS idx_wa_sched_conv
  ON public.whatsapp_scheduled_messages (conversation_id, send_at);

COMMENT ON TABLE public.whatsapp_conversation_tags IS
  'Free-form labels per WhatsApp conversation. UI renders as chips.';
COMMENT ON TABLE public.whatsapp_scheduled_messages IS
  'Queue of future-dated outbound WhatsApp messages. Drained by cron whatsapp-scheduled.';
