-- Seed iniziale per le tabelle CMS introdotte in 120–123.
--
-- Le tabelle erano nate vuote: /admin/cms/* mostrava empty state e il sito
-- ricadeva sui costanti file `apps/sito-v3/src/data/*.ts` (fallback OR-empty
-- in `apps/sito-v3/src/lib/cms.ts`). Questa migrazione popola i record con
-- gli stessi contenuti dei file `data/*.ts` così l'admin vede subito qualcosa
-- e il sito legge dal DB (preservando comunque il fallback file in caso di
-- API offline).
--
-- Idempotenza:
--   - site_glossario / site_seo_cities / site_services hanno UNIQUE su slug
--     (o slug+locale) → ON CONFLICT DO NOTHING.
--   - site_faqs / site_team non hanno UNIQUE → guardia WHERE NOT EXISTS
--     sul flag source='seed'. La migrazione è comunque single-shot perché
--     tracciata da schema_migrations: non sovrascrive mai l'admin.

-- ─────────────────────────────────────────────────────────────────
-- 1) site_faqs — 7 FAQ generiche da apps/sito-v3/src/data/faqs.ts
-- ─────────────────────────────────────────────────────────────────
INSERT INTO public.site_faqs (locale, question, answer, sort_order, source)
SELECT v.locale, v.question, v.answer, v.sort_order, 'seed'
FROM (VALUES
  ('it', 'Quali servizi offri?',
   E'Quattro core verticali nella matrice: web design, e-commerce, sviluppo web (gestionali, web app, integrazioni) e SEO.\nIn più, fuori matrice, branding, manutenzione siti e assistenza WordPress (security, performance, migrazioni).\nUn solo contatto, niente catena di fornitori.',
   0),
  ('it', 'Come si determina il prezzo del progetto?',
   E'Ogni progetto è cucito sul caso reale — niente listino preconfezionato.\nDopo una chiacchierata gratuita di 30 minuti capisco cosa ti serve, ti scrivo nero su bianco cosa ottieni, in quanto tempo, con quale impegno economico.\nPossibilità di pagamento dilazionato. Niente sorprese a fine lavoro.',
   1),
  ('it', 'Quanto tempo ci vuole per realizzare un progetto?',
   E'I tempi variano in base alla complessità: un sito One Page richiede circa 10 giorni lavorativi, un Multipagina fino a 30 giorni, un e-commerce fino a 90 giorni.\nFornisco tempistiche chiare e aggiornamenti costanti ad ogni fase.',
   2),
  ('it', 'Posso gestire i contenuti del sito da solo?',
   E'Assolutamente sì.\nIncludo formazione completa e documentazione per permetterti di gestire i contenuti in totale autonomia.\nChe sia WordPress o un CMS custom, ti metto nelle condizioni di essere indipendente.',
   3),
  ('it', 'Il SEO è incluso nel sito web?',
   E'Ogni sito include SEO tecnico di base: meta tag, sitemap, robots.txt, ottimizzazione velocità e configurazione Google Search Console.\nPer strategie SEO avanzate con content strategy e link building, offro pacchetti dedicati su misura.',
   4),
  ('it', 'Offri assistenza dopo il lancio?',
   E'Sì, ogni progetto include assistenza gratuita post-lancio.\nSuccessivamente offro piani di manutenzione mensile che includono backup, aggiornamenti, monitoraggio e supporto tecnico — per tenere il sito sicuro e veloce nel tempo.',
   5),
  ('it', 'Come iniziamo a lavorare insieme?',
   E'È semplice: contattami tramite il sito o prenota una consulenza gratuita di 30 minuti.\nDiscuteremo i tuoi obiettivi, le tue esigenze e il budget.\nPoi ti invierò una proposta dettagliata con timeline e costi. Nessun impegno, nessuna pressione.',
   6)
) AS v(locale, question, answer, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.site_faqs WHERE source = 'seed');
-- La colonna `section` viene aggiunta in mig 126 con default 'general':
-- i record qui inseriti diventeranno tutti section='general' al momento
-- dell'ALTER, separati dal seed dei perchi-faqs (section='perche').

-- ─────────────────────────────────────────────────────────────────
-- 2) site_team — 2 membri da apps/sito-v3/src/data/team.ts
-- ─────────────────────────────────────────────────────────────────
INSERT INTO public.site_team (locale, name, role, avatar_url, socials, sort_order, source)
SELECT v.locale, v.name, v.role, v.avatar_url, v.socials::jsonb, v.sort_order, 'seed'
FROM (VALUES
  ('it', 'Paolo Campione', 'Digital Marketing & Comunicazione',
   '/img/team/paolo-campione-3pcomunication.webp',
   '[{"label":"Sito web","url":"https://3pcomunication.it/"},{"label":"Instagram","url":"https://www.instagram.com/3pcomunication/"},{"label":"Facebook","url":"https://www.facebook.com/3pcomunication"}]',
   0),
  ('it', 'Davide Massa', 'Graphic Design & Comunicazione visiva',
   '/img/team/davide-massa-dmgraphic.webp',
   '[{"label":"Sito web","url":"https://www.dmgraphic.com/"},{"label":"Instagram","url":"https://www.instagram.com/d.mgraphic/"},{"label":"Facebook","url":"https://www.facebook.com/dmgraphicgrafico"}]',
   1)
) AS v(locale, name, role, avatar_url, socials, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.site_team WHERE source = 'seed');

-- ─────────────────────────────────────────────────────────────────
-- 3) site_glossario — 30 termini IT da apps/sito-v3/src/data/glossario.ts
-- ─────────────────────────────────────────────────────────────────
INSERT INTO public.site_glossario (locale, slug, term, full_name, letter, what_it_is, why_you_care, what_to_demand, sort_order, source)
VALUES
  ('it', 'accessibility', 'Accessibility', 'Accessibilità web (WCAG)', 'A',
   E'Insieme di criteri (WCAG 2.2) che rendono un sito usabile da chiunque:\nchi non vede, chi non sente, chi naviga solo da tastiera.',
   E'Un sito non accessibile esclude clienti.\nDal 2025 in Europa diventa illegale per le aziende sopra una certa soglia.\nTi espone anche a risarcimenti se ti fanno causa.',
   E'Chiedi un report di audit accessibilità prima del lancio.\nSe il fornitore ti guarda come un alieno quando dici ''WCAG'', cambia fornitore.',
   0, 'seed'),
  ('it', 'alt-text', 'Alt text', NULL, 'A',
   E'La descrizione testuale che si associa a un''immagine.\nLetta dagli screen reader e usata da Google per capire cosa raffigura.',
   E'Senza alt text le tue immagini non posizionano in Google Immagini.\nI tuoi clienti ipovedenti non possono usare correttamente il sito.',
   E'Pretendi alt text descrittivo su tutte le immagini di contenuto.\nLe immagini decorative possono avere alt vuoto, ma non essere assenti.',
   1, 'seed'),
  ('it', 'anchor-text', 'Anchor text', NULL, 'A',
   E'Il testo cliccabile di un link.\n''Clicca qui'' è anchor text. Il testo che precede è contesto.',
   E'Google usa l''anchor text per capire di cosa parla la pagina linkata.\n''Clicca qui'' non gli dice niente. Una keyword sì.',
   E'I link interni del tuo sito devono avere anchor descrittive (''servizi di web design'').\nEvita termini generici come ''clicca qui'' o ''leggi di più''.',
   2, 'seed'),
  ('it', 'backlink', 'Backlink', NULL, 'B',
   E'Un link da un altro sito al tuo.\nPer Google è come un voto di fiducia: più siti autorevoli ti linkano, più ranki.',
   E'Senza backlink di qualità, anche il sito tecnicamente perfetto non rankerà su keyword competitive.\nÈ il pilastro dell''autorità esterna.',
   E'Diffida di chi vende ''1.000 backlink a 99€''. Sono link spam che Google penalizza.\nVuoi pochi link, ma da siti reali e autorevoli del tuo settore.',
   3, 'seed'),
  ('it', 'breadcrumb', 'Breadcrumb', NULL, 'B',
   E'La ''briciolina'' di navigazione — Home › Servizi › Web Design — che mostra dove sei nel sito e come ci sei arrivato.',
   E'Aiuta gli utenti a orientarsi e Google a capire la struttura del sito.\nSenza, la navigazione confonde e il SEO peggiora.',
   E'I breadcrumb devono essere presenti su tutte le pagine interne.\nDevono includere lo schema JSON-LD BreadcrumbList per Google.',
   4, 'seed'),
  ('it', 'canonical', 'Canonical', 'Canonical URL', 'C',
   E'Il tag `<link rel=''canonical''>` che dice a Google qual è la versione ''ufficiale'' di una pagina.\nIndispensabile quando ne esistono varianti (es. parametri tracking).',
   E'Senza canonical Google vede contenuto duplicato, divide il ranking tra le copie, e la pagina principale ne soffre.',
   E'Ogni pagina deve avere un canonical esplicito che punta alla URL pulita.\nSe il tuo sito ha versioni mobile/desktop separate, il canonical lo dichiara.',
   5, 'seed'),
  ('it', 'cdn', 'CDN', 'Content Delivery Network', 'C',
   E'Una rete di server distribuiti nel mondo che consegna i tuoi contenuti dal nodo più vicino al visitatore.\nIl sito apre più veloce ovunque.',
   E'Se vendi a Milano e il tuo server è ad Amsterdam, ogni clic perde 100ms.\nIl CDN abbatte la latenza e migliora le Core Web Vitals.',
   E'Hosting moderno (Vercel, Cloudflare Pages) include CDN.\nSu WordPress chiedi Cloudflare in front.\nCosto: spesso zero.',
   6, 'seed'),
  ('it', 'cls', 'CLS', 'Cumulative Layout Shift', 'C',
   E'Quanto la pagina ''salta'' mentre si carica.\nSuccede quando clicchi un bottone e all''ultimo si sposta perché un''immagine ha caricato.',
   E'Un CLS alto fa rabbia all''utente, e Google ti penalizza nel ranking.\nSotto 0,1 sei a posto, sopra 0,25 sei nei guai.',
   E'Tutte le immagini devono avere width/height esplicite.\nNiente font che caricano in ritardo cambiando il layout.\nMisurato con Lighthouse, non a occhio.',
   7, 'seed'),
  ('it', 'cms', 'CMS', 'Content Management System', 'C',
   E'Il pannello con cui modifichi i contenuti del sito senza saper programmare.\nWordPress è il più famoso, ma ce ne sono di più moderni (Payload, Sanity).',
   E'Senza CMS dipendi dal fornitore per ogni virgola da cambiare.\nCon il CMS giusto sei autonomo.\nCon quello sbagliato è peggio del nulla.',
   E'Non accettare ''siti statici a mano'' a meno che non ti serva.\nVuoi un CMS che capisci e che dura nel tempo.\nFormazione sempre inclusa.',
   8, 'seed'),
  ('it', 'core-web-vitals', 'Core Web Vitals', NULL, 'C',
   E'I tre numeri (LCP, CLS, INP) con cui Google misura l''esperienza tecnica del sito.\nSe non passi, perdi posizioni.',
   E'Sono fattori di ranking ufficiali dal 2021.\nUn sito lento o instabile non posiziona, indipendentemente dalla qualità dei contenuti.',
   E'Pretendi un report PageSpeed Insights con tutti tre i numeri in verde.\nSe il fornitore ti dice ''è normale che sia rosso'', non è il tuo fornitore.',
   9, 'seed'),
  ('it', 'dominio', 'Dominio', NULL, 'D',
   E'L''indirizzo del tuo sito — calicchia.design, miosito.it.\nÈ il nome che digiti per arrivare alla tua casa online.',
   E'Il dominio deve essere TUO, registrato a nome tuo.\nNon del web designer, non dell''agenzia.\nSe sparisce il fornitore, non deve sparire il tuo business.',
   E'Pretendi le credenziali del registrar con il dominio intestato a te.\nSe fanno resistenza, è un segnale di allarme.',
   10, 'seed'),
  ('it', 'fid', 'FID', 'First Input Delay (deprecato 2024)', 'F',
   E'Tempo tra il primo clic dell''utente e la risposta del browser.\nDa marzo 2024 sostituito da INP, ma lo trovi ancora in vecchi report.',
   E'Storicamente Core Web Vital — oggi guarda INP.\nSe il tuo fornitore parla ancora di FID, è fermo a tecniche di 3 anni fa.',
   E'Report che misuri INP, non solo FID.\nSe vedi solo FID nel report, chiedi un aggiornamento tecnico.',
   11, 'seed'),
  ('it', 'hosting', 'Hosting', NULL, 'H',
   E'Lo spazio server dove vive il sito.\nSe il sito è una casa, l''hosting è il terreno su cui poggia.',
   E'Hosting scadente = sito lento, downtime, attacchi informatici.\nSpendere 30€/anno per risparmiare 100€ ti costa clienti ogni giorno.',
   E'Performance reali, backup automatici giornalieri, supporto 24/7.\nIl prezzo vero è quello che ti garantisce la continuità del business.',
   12, 'seed'),
  ('it', 'hreflang', 'Hreflang', NULL, 'H',
   E'Tag che dice a Google che la stessa pagina esiste in più lingue.\nEsempio: ''/it/contatti'' e ''/en/contact'' vanno collegati tra loro.',
   E'Senza hreflang Google può mostrare la versione sbagliata al visitatore.\nO peggio: pensare che siano contenuti duplicati e penalizzarti.',
   E'In un sito multilingua, ogni versione deve dichiarare hreflang verso le altre.\nLa sitemap XML deve includerli automaticamente.',
   13, 'seed'),
  ('it', 'https', 'HTTPS', 'HTTPS / SSL', 'H',
   E'Il lucchetto verde nel browser.\nSignifica che il traffico tra utente e sito è cifrato.\nSenza, è tutto in chiaro.',
   E'HTTPS è fattore di ranking.\nI browser marchiano ''Non sicuro'' i siti senza.\nNessuno compra da un sito ''Non sicuro''.',
   E'Certificato SSL incluso nell''hosting (Let''s Encrypt è gratis e perfetto).\nRedirect automatico da HTTP a HTTPS.\nNiente eccezioni.',
   14, 'seed'),
  ('it', 'inp', 'INP', 'Interaction to Next Paint', 'I',
   E'Quanto tempo passa tra un clic e il momento in cui il browser mostra il risultato.\nSostituisce definitivamente il FID dal 2024.',
   E'Un sito che ''non risponde'' subito al clic frustra l''utente.\nSotto 200ms sei ottimo, sopra 500ms sei rotto.\nGoogle lo usa per pesare il tuo ranking.',
   E'Misurato in PageSpeed Insights.\nDeve essere sotto i 200ms su mobile reale, non solo su test sintetici.',
   15, 'seed'),
  ('it', 'lazy-loading', 'Lazy loading', NULL, 'L',
   E'Tecnica che carica le immagini solo quando l''utente sta per vederle.\nRiduce drasticamente il peso iniziale della pagina.',
   E'Un sito senza lazy loading carica tutto subito: è lento, brucia dati mobili.\nCon il lazy loading apre istantaneo e consuma meno banda.',
   E'Tutte le immagini sotto la prima schermata devono essere lazy.\nQuelle sopra (LCP) no: caricarle lazy peggiorerebbe le prestazioni.',
   16, 'seed'),
  ('it', 'lcp', 'LCP', 'Largest Contentful Paint', 'L',
   E'Il tempo che impiega l''elemento più grande della pagina (immagine hero, video o testo) ad apparire al visitatore.',
   E'Sotto i 2,5 secondi sei a posto.\nSopra i 4 secondi Google ti penalizza e i visitatori chiudono la scheda annoiati.',
   E'Chiedi l''LCP esatto misurato — non un generico ''va veloce''.\nDeve essere testato su mobile reale (rete 4G), non su connessione ufficio.',
   17, 'seed'),
  ('it', 'meta-description', 'Meta description', NULL, 'M',
   E'Il riassunto di 150-160 caratteri che appare sotto al titolo blu nei risultati di Google.',
   E'Non è fattore di ranking diretto, ma incide sul click-through rate (CTR).\nUna description debole e nessuno clicca, anche se sei primo.',
   E'Ogni pagina deve avere una meta description unica e scritta a mano.\nDeve includere keyword, value prop e un invito all''azione chiaro.',
   18, 'seed'),
  ('it', 'mobile-first', 'Mobile first', NULL, 'M',
   E'Approccio di design che parte dal mobile e poi adatta al desktop.\nRiflette come naviga oggi oltre il 70% degli utenti reali.',
   E'Google indicizza mobile-first dal 2019.\nSe il tuo sito ''si adatta'' ma non è progettato per il pollice, perdi ranking e clienti.',
   E'Pretendi il mockup mobile PRIMA del desktop.\nSe il fornitore parte dal monitor grande, sta lavorando con una mentalità vecchia.',
   19, 'seed'),
  ('it', 'open-graph', 'Open Graph', NULL, 'O',
   E'Tag che controllano come appare il tuo sito quando viene condiviso sui social (Facebook, LinkedIn, WhatsApp).\nTitolo, descrizione e immagine.',
   E'Senza Open Graph, una condivisione su LinkedIn mostra un quadrato bianco o una URL nuda.\nSembra amatoriale e nessuno ci clicca.',
   E'Ogni pagina deve avere og:title, og:description e og:image (1200×630).\nL''immagine deve essere curata, non uno screenshot casuale.',
   20, 'seed'),
  ('it', 'page-speed', 'Page speed', NULL, 'P',
   E'La velocità complessiva di caricamento.\nNon un singolo numero, ma l''unione di LCP, CLS, INP e TTFB.',
   E'Ogni secondo in più di attesa = -7% di conversioni.\nLa velocità non è un dettaglio tecnico, è l''efficienza del tuo business online.',
   E'PageSpeed Insights almeno 90/100 su mobile reale.\nSe il fornitore minimizza lo score, sta proteggendo la sua incapacità tecnica.',
   21, 'seed'),
  ('it', 'redirect', 'Redirect', NULL, 'R',
   E'Reindirizzamento da una URL vecchia a una nuova.\nQuando rifai il sito, il redirect 301 dice a Google: ''la pagina si è spostata qui''.',
   E'Senza redirect, i link che puntavano al vecchio sito diventano 404.\nPerdi traffico, perdi autorità e anni di SEO faticosa.',
   E'Mappa dei redirect 301 di TUTTE le URL vecchie verso le nuove.\nPretendila scritta e verificabile PRIMA del lancio del nuovo sito.',
   22, 'seed'),
  ('it', 'responsive', 'Responsive design', NULL, 'R',
   E'Design che si adatta a ogni dimensione di schermo: mobile, tablet, desktop.\nUna sola codebase che risponde a ogni viewport.',
   E'Un sito ''solo desktop'' nel 2026 è un asset morto.\nGoogle lo penalizza, gli utenti lo abbandonano, è inutile sul telefono.',
   E'Verifica il sito su un iPhone e un Android reali prima del lancio.\nNon fidarti degli emulatori del browser, prova il tocco reale.',
   23, 'seed'),
  ('it', 'robots', 'Robots.txt', NULL, 'R',
   E'File di testo che dice ai bot dei motori di ricerca cosa scansionare e cosa ignorare.\nEs: blocco dell''area admin o dei file privati.',
   E'Un robots.txt sbagliato può far sparire l''intero sito da Google.\nO esporre pagine sensibili che dovrebbero restare nascoste.',
   E' robots.txt esplicito che blocchi solo i path privati.\nTutto il resto deve essere libero per la scansione dei bot.',
   24, 'seed'),
  ('it', 'schema-markup', 'Schema markup', 'Schema markup (JSON-LD)', 'S',
   E'Codice strutturato (formato JSON-LD) che spiega a Google cosa sono i contenuti — un articolo, un prodotto, una FAQ, un evento.',
   E'Lo schema sblocca i ''rich result'': stelle nei risultati, FAQ espandibili, prezzi visibili.\nPiù visibilità in SERP a parità di posizione.',
   E'Schema Article, FAQPage, BreadcrumbList, LocalBusiness validati con Google Rich Results Test.\nSenza non sei competitivo.',
   25, 'seed'),
  ('it', 'sitemap', 'Sitemap', 'Sitemap XML', 'S',
   E'L''indice del sito in formato XML.\nLa mappa che Google legge per scoprire e indicizzare tutte le tue pagine velocemente.',
   E'Senza sitemap Google trova le pagine ''a caso'' seguendo i link.\nLe pagine nuove possono impiegare settimane a comparire nei risultati.',
   E'Sitemap XML auto-aggiornante, registrata in Search Console.\nDeve contenere tutte (e sole) le URL pubbliche e indicizzabili.',
   26, 'seed'),
  ('it', 'ssl', 'SSL', 'Secure Sockets Layer (oggi TLS)', 'S',
   E'Il certificato che cifra il traffico tra browser e server.\nÈ quello che abilita l''icona del lucchetto e il protocollo sicuro HTTPS.',
   E'Senza SSL il sito è marchiato ''Non sicuro''.\nI browser bloccano i form di contatto e il checkout se la connessione non è protetta.',
   E'SSL Let''s Encrypt incluso e con rinnovo automatico.\nCosto: zero. Chi te lo fa pagare a parte sta gonfiando il conto.',
   27, 'seed'),
  ('it', 'link-interni', 'Link interni', 'Internal Linking', 'L',
   E'Link da una pagina del tuo sito a un''altra pagina dello stesso sito.\nDiversi dai backlink, che provengono da siti esterni.',
   E'Distribuiscono l''autorità SEO tra le pagine e aiutano Google a capire la gerarchia.\nNessun link interno = pagina orfana = invisibile.',
   E'Ogni pagina nuova deve ricevere almeno 2-3 link da altre sezioni.\nUsa anchor text descrittivi, non ''clicca qui''.',
   28, 'seed')
ON CONFLICT (slug, locale) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────
-- 4) site_seo_cities — 135 città da apps/sito-v3/src/data/seo-cities.ts
-- ─────────────────────────────────────────────────────────────────
INSERT INTO public.site_seo_cities (slug, nome, regione, tipo, tier, source)
VALUES
  -- Abruzzo
  ('l-aquila', E'L''Aquila', 'Abruzzo', 'capoluogo', 2, 'seed'),
  ('chieti', 'Chieti', 'Abruzzo', 'capoluogo', 2, 'seed'),
  ('pescara', 'Pescara', 'Abruzzo', 'capoluogo', 2, 'seed'),
  ('teramo', 'Teramo', 'Abruzzo', 'capoluogo', 2, 'seed'),
  -- Basilicata
  ('potenza', 'Potenza', 'Basilicata', 'capoluogo', 2, 'seed'),
  ('matera', 'Matera', 'Basilicata', 'capoluogo', 2, 'seed'),
  -- Calabria
  ('catanzaro', 'Catanzaro', 'Calabria', 'capoluogo', 2, 'seed'),
  ('cosenza', 'Cosenza', 'Calabria', 'capoluogo', 2, 'seed'),
  ('crotone', 'Crotone', 'Calabria', 'capoluogo', 2, 'seed'),
  ('reggio-di-calabria', 'Reggio di Calabria', 'Calabria', 'capoluogo', 2, 'seed'),
  ('vibo-valentia', 'Vibo Valentia', 'Calabria', 'capoluogo', 2, 'seed'),
  -- Campania
  ('napoli', 'Napoli', 'Campania', 'capoluogo', 1, 'seed'),
  ('avellino', 'Avellino', 'Campania', 'capoluogo', 2, 'seed'),
  ('benevento', 'Benevento', 'Campania', 'capoluogo', 2, 'seed'),
  ('caserta', 'Caserta', 'Campania', 'capoluogo', 2, 'seed'),
  ('salerno', 'Salerno', 'Campania', 'capoluogo', 2, 'seed'),
  -- Emilia-Romagna
  ('bologna', 'Bologna', 'Emilia-Romagna', 'capoluogo', 1, 'seed'),
  ('ferrara', 'Ferrara', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('forli', 'Forli', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('modena', 'Modena', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('parma', 'Parma', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('piacenza', 'Piacenza', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('ravenna', 'Ravenna', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('reggio-nell-emilia', E'Reggio nell''Emilia', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  ('rimini', 'Rimini', 'Emilia-Romagna', 'capoluogo', 2, 'seed'),
  -- Friuli-Venezia Giulia
  ('trieste', 'Trieste', 'Friuli-Venezia Giulia', 'capoluogo', 2, 'seed'),
  ('gorizia', 'Gorizia', 'Friuli-Venezia Giulia', 'capoluogo', 2, 'seed'),
  ('pordenone', 'Pordenone', 'Friuli-Venezia Giulia', 'capoluogo', 2, 'seed'),
  ('udine', 'Udine', 'Friuli-Venezia Giulia', 'capoluogo', 2, 'seed'),
  -- Lazio
  ('roma', 'Roma', 'Lazio', 'capoluogo', 1, 'seed'),
  ('frosinone', 'Frosinone', 'Lazio', 'capoluogo', 1, 'seed'),
  ('latina', 'Latina', 'Lazio', 'capoluogo', 1, 'seed'),
  ('rieti', 'Rieti', 'Lazio', 'capoluogo', 2, 'seed'),
  ('viterbo', 'Viterbo', 'Lazio', 'capoluogo', 2, 'seed'),
  -- Liguria
  ('genova', 'Genova', 'Liguria', 'capoluogo', 2, 'seed'),
  ('imperia', 'Imperia', 'Liguria', 'capoluogo', 2, 'seed'),
  ('la-spezia', 'La Spezia', 'Liguria', 'capoluogo', 2, 'seed'),
  ('savona', 'Savona', 'Liguria', 'capoluogo', 2, 'seed'),
  -- Lombardia
  ('milano', 'Milano', 'Lombardia', 'capoluogo', 1, 'seed'),
  ('bergamo', 'Bergamo', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('brescia', 'Brescia', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('como', 'Como', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('cremona', 'Cremona', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('lecco', 'Lecco', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('lodi', 'Lodi', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('mantova', 'Mantova', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('monza', 'Monza', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('pavia', 'Pavia', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('sondrio', 'Sondrio', 'Lombardia', 'capoluogo', 2, 'seed'),
  ('varese', 'Varese', 'Lombardia', 'capoluogo', 2, 'seed'),
  -- Marche
  ('ancona', 'Ancona', 'Marche', 'capoluogo', 2, 'seed'),
  ('ascoli-piceno', 'Ascoli Piceno', 'Marche', 'capoluogo', 2, 'seed'),
  ('fermo', 'Fermo', 'Marche', 'capoluogo', 2, 'seed'),
  ('macerata', 'Macerata', 'Marche', 'capoluogo', 2, 'seed'),
  ('pesaro', 'Pesaro', 'Marche', 'capoluogo', 2, 'seed'),
  -- Molise
  ('campobasso', 'Campobasso', 'Molise', 'capoluogo', 2, 'seed'),
  ('isernia', 'Isernia', 'Molise', 'capoluogo', 2, 'seed'),
  -- Piemonte
  ('torino', 'Torino', 'Piemonte', 'capoluogo', 1, 'seed'),
  ('alessandria', 'Alessandria', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('asti', 'Asti', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('biella', 'Biella', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('cuneo', 'Cuneo', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('novara', 'Novara', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('verbania', 'Verbania', 'Piemonte', 'capoluogo', 2, 'seed'),
  ('vercelli', 'Vercelli', 'Piemonte', 'capoluogo', 2, 'seed'),
  -- Puglia
  ('bari', 'Bari', 'Puglia', 'capoluogo', 2, 'seed'),
  ('andria', 'Andria', 'Puglia', 'capoluogo', 2, 'seed'),
  ('barletta', 'Barletta', 'Puglia', 'capoluogo', 2, 'seed'),
  ('brindisi', 'Brindisi', 'Puglia', 'capoluogo', 2, 'seed'),
  ('foggia', 'Foggia', 'Puglia', 'capoluogo', 2, 'seed'),
  ('lecce', 'Lecce', 'Puglia', 'capoluogo', 2, 'seed'),
  ('taranto', 'Taranto', 'Puglia', 'capoluogo', 2, 'seed'),
  ('trani', 'Trani', 'Puglia', 'capoluogo', 2, 'seed'),
  -- Sardegna
  ('cagliari', 'Cagliari', 'Sardegna', 'capoluogo', 2, 'seed'),
  ('carbonia', 'Carbonia', 'Sardegna', 'capoluogo', 2, 'seed'),
  ('nuoro', 'Nuoro', 'Sardegna', 'capoluogo', 2, 'seed'),
  ('oristano', 'Oristano', 'Sardegna', 'capoluogo', 2, 'seed'),
  ('sassari', 'Sassari', 'Sardegna', 'capoluogo', 2, 'seed'),
  -- Sicilia
  ('palermo', 'Palermo', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('agrigento', 'Agrigento', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('caltanissetta', 'Caltanissetta', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('catania', 'Catania', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('enna', 'Enna', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('messina', 'Messina', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('ragusa', 'Ragusa', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('siracusa', 'Siracusa', 'Sicilia', 'capoluogo', 2, 'seed'),
  ('trapani', 'Trapani', 'Sicilia', 'capoluogo', 2, 'seed'),
  -- Toscana
  ('firenze', 'Firenze', 'Toscana', 'capoluogo', 1, 'seed'),
  ('arezzo', 'Arezzo', 'Toscana', 'capoluogo', 2, 'seed'),
  ('grosseto', 'Grosseto', 'Toscana', 'capoluogo', 2, 'seed'),
  ('livorno', 'Livorno', 'Toscana', 'capoluogo', 2, 'seed'),
  ('lucca', 'Lucca', 'Toscana', 'capoluogo', 2, 'seed'),
  ('massa', 'Massa', 'Toscana', 'capoluogo', 2, 'seed'),
  ('pisa', 'Pisa', 'Toscana', 'capoluogo', 2, 'seed'),
  ('pistoia', 'Pistoia', 'Toscana', 'capoluogo', 2, 'seed'),
  ('prato', 'Prato', 'Toscana', 'capoluogo', 2, 'seed'),
  ('siena', 'Siena', 'Toscana', 'capoluogo', 2, 'seed'),
  -- Trentino-Alto Adige
  ('trento', 'Trento', 'Trentino-Alto Adige', 'capoluogo', 2, 'seed'),
  ('bolzano', 'Bolzano', 'Trentino-Alto Adige', 'capoluogo', 2, 'seed'),
  -- Umbria
  ('perugia', 'Perugia', 'Umbria', 'capoluogo', 2, 'seed'),
  ('terni', 'Terni', 'Umbria', 'capoluogo', 2, 'seed'),
  -- Valle d'Aosta
  ('aosta', 'Aosta', E'Valle d''Aosta', 'capoluogo', 2, 'seed'),
  -- Veneto
  ('venezia', 'Venezia', 'Veneto', 'capoluogo', 2, 'seed'),
  ('belluno', 'Belluno', 'Veneto', 'capoluogo', 2, 'seed'),
  ('padova', 'Padova', 'Veneto', 'capoluogo', 2, 'seed'),
  ('rovigo', 'Rovigo', 'Veneto', 'capoluogo', 2, 'seed'),
  ('treviso', 'Treviso', 'Veneto', 'capoluogo', 2, 'seed'),
  ('verona', 'Verona', 'Veneto', 'capoluogo', 2, 'seed'),
  ('vicenza', 'Vicenza', 'Veneto', 'capoluogo', 2, 'seed'),
  -- Ciociaria / Frosinone (Frosinone già sopra come capoluogo)
  ('acquafondata', 'Acquafondata', 'Lazio', 'ciociaria', 3, 'seed'),
  ('acuto', 'Acuto', 'Lazio', 'ciociaria', 3, 'seed'),
  ('alatri', 'Alatri', 'Lazio', 'ciociaria', 1, 'seed'),
  ('alvito', 'Alvito', 'Lazio', 'ciociaria', 3, 'seed'),
  ('amaseno', 'Amaseno', 'Lazio', 'ciociaria', 3, 'seed'),
  ('anagni', 'Anagni', 'Lazio', 'ciociaria', 1, 'seed'),
  ('aquino', 'Aquino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('arce', 'Arce', 'Lazio', 'ciociaria', 3, 'seed'),
  ('arnara', 'Arnara', 'Lazio', 'ciociaria', 3, 'seed'),
  ('arpino', 'Arpino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('atina', 'Atina', 'Lazio', 'ciociaria', 3, 'seed'),
  ('ausonia', 'Ausonia', 'Lazio', 'ciociaria', 3, 'seed'),
  ('belmonte-castello', 'Belmonte Castello', 'Lazio', 'ciociaria', 3, 'seed'),
  ('boville-ernica', 'Boville Ernica', 'Lazio', 'ciociaria', 3, 'seed'),
  ('broccostella', 'Broccostella', 'Lazio', 'ciociaria', 3, 'seed'),
  ('campoli-appennino', 'Campoli Appennino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('casalattico', 'Casalattico', 'Lazio', 'ciociaria', 3, 'seed'),
  ('casalvieri', 'Casalvieri', 'Lazio', 'ciociaria', 3, 'seed'),
  ('cassino', 'Cassino', 'Lazio', 'ciociaria', 1, 'seed'),
  ('castelliri', 'Castelliri', 'Lazio', 'ciociaria', 3, 'seed'),
  ('castelnuovo-parano', 'Castelnuovo Parano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('castrocielo', 'Castrocielo', 'Lazio', 'ciociaria', 3, 'seed'),
  ('castro-dei-volsci', 'Castro dei Volsci', 'Lazio', 'ciociaria', 3, 'seed'),
  ('ceccano', 'Ceccano', 'Lazio', 'ciociaria', 1, 'seed'),
  ('ceprano', 'Ceprano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('cervaro', 'Cervaro', 'Lazio', 'ciociaria', 3, 'seed'),
  ('colfelice', 'Colfelice', 'Lazio', 'ciociaria', 3, 'seed'),
  ('collepardo', 'Collepardo', 'Lazio', 'ciociaria', 3, 'seed'),
  ('colle-san-magno', 'Colle San Magno', 'Lazio', 'ciociaria', 3, 'seed'),
  ('coreno-ausonio', 'Coreno Ausonio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('esperia', 'Esperia', 'Lazio', 'ciociaria', 3, 'seed'),
  ('falvaterra', 'Falvaterra', 'Lazio', 'ciociaria', 3, 'seed'),
  ('ferentino', 'Ferentino', 'Lazio', 'ciociaria', 1, 'seed'),
  ('filettino', 'Filettino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('fiuggi', 'Fiuggi', 'Lazio', 'ciociaria', 1, 'seed'),
  ('fontana-liri', 'Fontana Liri', 'Lazio', 'ciociaria', 3, 'seed'),
  ('fontechiari', 'Fontechiari', 'Lazio', 'ciociaria', 3, 'seed'),
  ('fumone', 'Fumone', 'Lazio', 'ciociaria', 3, 'seed'),
  ('gallinaro', 'Gallinaro', 'Lazio', 'ciociaria', 3, 'seed'),
  ('giuliano-di-roma', 'Giuliano di Roma', 'Lazio', 'ciociaria', 3, 'seed'),
  ('guarcino', 'Guarcino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('isola-del-liri', 'Isola del Liri', 'Lazio', 'ciociaria', 1, 'seed'),
  ('monte-san-giovanni-campano', 'Monte San Giovanni Campano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('morolo', 'Morolo', 'Lazio', 'ciociaria', 3, 'seed'),
  ('paliano', 'Paliano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pastena', 'Pastena', 'Lazio', 'ciociaria', 3, 'seed'),
  ('patrica', 'Patrica', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pescosolido', 'Pescosolido', 'Lazio', 'ciociaria', 3, 'seed'),
  ('picinisco', 'Picinisco', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pico', 'Pico', 'Lazio', 'ciociaria', 3, 'seed'),
  ('piedimonte-san-germano', 'Piedimonte San Germano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('piglio', 'Piglio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pignataro-interamna', 'Pignataro Interamna', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pofi', 'Pofi', 'Lazio', 'ciociaria', 3, 'seed'),
  ('pontecorvo', 'Pontecorvo', 'Lazio', 'ciociaria', 3, 'seed'),
  ('posta-fibreno', 'Posta Fibreno', 'Lazio', 'ciociaria', 3, 'seed'),
  ('ripi', 'Ripi', 'Lazio', 'ciociaria', 3, 'seed'),
  ('rocca-d-arce', E'Rocca d''Arce', 'Lazio', 'ciociaria', 3, 'seed'),
  ('roccasecca', 'Roccasecca', 'Lazio', 'ciociaria', 3, 'seed'),
  ('san-biagio-saracinisco', 'San Biagio Saracinisco', 'Lazio', 'ciociaria', 3, 'seed'),
  ('san-donato-val-di-comino', 'San Donato Val di Comino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('san-giorgio-a-liri', 'San Giorgio a Liri', 'Lazio', 'ciociaria', 3, 'seed'),
  ('san-giovanni-incarico', 'San Giovanni Incarico', 'Lazio', 'ciociaria', 3, 'seed'),
  ('san-vittore-del-lazio', 'San Vittore del Lazio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sant-ambrogio-sul-garigliano', E'Sant''Ambrogio sul Garigliano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sant-andrea-del-garigliano', E'Sant''Andrea del Garigliano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sant-apollinare', E'Sant''Apollinare', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sant-elia-fiumerapido', E'Sant''Elia Fiumerapido', 'Lazio', 'ciociaria', 3, 'seed'),
  ('santopadre', 'Santopadre', 'Lazio', 'ciociaria', 3, 'seed'),
  ('serrone', 'Serrone', 'Lazio', 'ciociaria', 3, 'seed'),
  ('settefrati', 'Settefrati', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sgurgola', 'Sgurgola', 'Lazio', 'ciociaria', 3, 'seed'),
  ('sora', 'Sora', 'Lazio', 'ciociaria', 1, 'seed'),
  ('strangolagalli', 'Strangolagalli', 'Lazio', 'ciociaria', 3, 'seed'),
  ('supino', 'Supino', 'Lazio', 'ciociaria', 3, 'seed'),
  ('terelle', 'Terelle', 'Lazio', 'ciociaria', 3, 'seed'),
  ('torre-cajetani', 'Torre Cajetani', 'Lazio', 'ciociaria', 3, 'seed'),
  ('torrice', 'Torrice', 'Lazio', 'ciociaria', 3, 'seed'),
  ('trevi-nel-lazio', 'Trevi nel Lazio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('trivigliano', 'Trivigliano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('vallecorsa', 'Vallecorsa', 'Lazio', 'ciociaria', 3, 'seed'),
  ('vallemaio', 'Vallemaio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('vallerotonda', 'Vallerotonda', 'Lazio', 'ciociaria', 3, 'seed'),
  ('veroli', 'Veroli', 'Lazio', 'ciociaria', 1, 'seed'),
  ('vicalvi', 'Vicalvi', 'Lazio', 'ciociaria', 3, 'seed'),
  ('vico-nel-lazio', 'Vico nel Lazio', 'Lazio', 'ciociaria', 3, 'seed'),
  ('villa-latina', 'Villa Latina', 'Lazio', 'ciociaria', 3, 'seed'),
  ('villa-santa-lucia', 'Villa Santa Lucia', 'Lazio', 'ciociaria', 3, 'seed'),
  ('villa-santo-stefano', 'Villa Santo Stefano', 'Lazio', 'ciociaria', 3, 'seed'),
  ('viticuso', 'Viticuso', 'Lazio', 'ciociaria', 3, 'seed')
ON CONFLICT (slug) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────
-- 5) site_services — 22 servizi (11 matrix+standalone × 2 locale) da
--    apps/sito-v3/src/data/services.ts + services-en.ts
-- ─────────────────────────────────────────────────────────────────
INSERT INTO public.site_services (locale, slug, title, lead, deliverables, icon, category, sort_order, source)
VALUES
  -- IT MATRIX
  ('it', 'web-design', 'Web Design',
   E'Il tuo sito non è una brochure online.\nÈ il primo posto dove le persone decidono se fidarsi di te.\nLo costruisco partendo da te — niente template, niente scorciatoie.',
   '["Design cucito sulla tua identità","SEO tecnica già configurata","Privacy/cookie GDPR a posto","Un anno di assistenza inclusa"]'::jsonb,
   'globe', 'matrix', 0, 'seed'),
  ('it', 'e-commerce', 'E-Commerce',
   E'Aprire un e-commerce non vuol dire mettere prodotti su una pagina e sperare che qualcuno compri.\nCostruisco store che convertono, gestibili senza un team IT.',
   '["Catalogo + carrello + checkout fluidi","Integrazione pagamenti (Stripe / PayPal)","Sincronizzazione magazzino","Email transazionali curate"]'::jsonb,
   'shopping-cart', 'matrix', 1, 'seed'),
  ('it', 'sviluppo-web', 'Sviluppo Web',
   E'A volte un sito vetrina non basta.\nTi serve una piattaforma che fa cose: gestionali, prenotazioni, area clienti, integrazioni con i tuoi strumenti.',
   '["Applicazioni custom su misura","API e integrazioni terze parti","Aree riservate e gestionali","Performance da SaaS moderno"]'::jsonb,
   'code', 'matrix', 2, 'seed'),
  ('it', 'seo', 'SEO & Visibilità',
   E'Niente trucchi, niente promesse vuote.\nFaccio in modo che chi cerca quello che offri ti trovi e capisca al volo perché sei tu la scelta giusta.',
   '["Audit tecnico completo","Strategia keyword & contenuti","Local SEO (Google Business)","Monitoraggio mensile"]'::jsonb,
   'magnifying-glass', 'matrix', 3, 'seed'),
  -- IT STANDALONE
  ('it', 'manutenzione-siti', 'Manutenzione siti',
   E'Il tuo sito è online — ma chi lo controlla?\nAggiornamenti, backup, monitoring, fix urgenti.\nUn canone mensile chiaro, senza sorprese.',
   '["Backup e ripristino","Update CMS, plugin, dipendenze","Monitoring uptime e performance","Fix urgenti entro 24h"]'::jsonb,
   'wrench', 'standalone', 10, 'seed'),
  ('it', 'assistenza-wordpress', 'Assistenza WordPress',
   E'WordPress è potente — e fragile.\nPulisco siti compromessi, sistemo plugin in conflitto, blocco gli attacchi prima che facciano danni.',
   '["Security hardening (firewall, 2FA)","Pulizia malware e ripristino","Risoluzione conflitti plugin","Performance tuning (cache, query)"]'::jsonb,
   'shield-check', 'standalone', 11, 'seed'),
  ('it', 'wordpress-migrazione', 'Migrazione & Hosting WordPress',
   E'Sito lento o host che ti tradisce?\nTrasloco WordPress senza downtime, configuro hosting performante, taglio i tempi di caricamento.',
   '["Migrazione zero-downtime","Setup hosting tuned per WP","CDN e cache configurati","Migrazione DNS e certificati SSL"]'::jsonb,
   'cloud-arrow-up', 'standalone', 12, 'seed'),
  ('it', 'performance-cwv', 'Performance & Core Web Vitals',
   E'Il sito è bello ma carica in 8 secondi.\nSu mobile fa sparire i clienti, su Google scivola in fondo.\nSistemo LCP, CLS, INP fino a passare il check.',
   '["Audit Lighthouse + WebPageTest","LCP < 2.5s, CLS < 0.1, INP < 200ms","Image optimization + lazy loading","Report before/after misurabile"]'::jsonb,
   'gauge', 'standalone', 13, 'seed'),
  ('it', 'accessibility-wcag', 'Accessibilità WCAG',
   E'Dal 28 giugno 2025 l''European Accessibility Act è in vigore.\nSe vendi online, il sito deve essere accessibile o paghi multe.\nAudit WCAG 2.1 AA + remediation.',
   '["Audit screen reader (NVDA + VoiceOver)","Contrast + keyboard navigation check","ARIA fixes + semantic HTML","Accessibility statement pubblicabile"]'::jsonb,
   'wheelchair', 'standalone', 14, 'seed'),
  ('it', 'analytics-setup', 'Analytics & Tag Manager',
   E'Hai un sito ma non sai chi compra, chi rimbalza, da dove vengono.\nSetup GA4 + GTM corretto, eventi conversione tracciati, dashboard letta in 5 minuti.',
   '["GA4 property + GTM container","Eventi e-commerce / lead form","Consent Mode v2 (GDPR-compliant)","Dashboard Looker Studio personalizzata"]'::jsonb,
   'chart-line-up', 'standalone', 15, 'seed'),
  -- EN MATRIX
  ('en', 'web-design', 'Web Design',
   E'Your website is not an online brochure.\nIt is the first place people decide whether to trust you.\nI build it starting from you — no templates, no shortcuts.',
   '["Design tailored to your identity","Technical SEO already configured","GDPR privacy / cookies in order","One year of support included"]'::jsonb,
   'globe', 'matrix', 0, 'seed'),
  ('en', 'e-commerce', 'E-Commerce',
   E'Opening an e-commerce store does not mean putting products on a page and hoping someone buys.\nI build stores that convert, manageable without an IT team.',
   '["Catalogue, cart and checkout that flow","Payment integration (Stripe / PayPal)","Inventory sync","Transactional emails done with care"]'::jsonb,
   'shopping-cart', 'matrix', 1, 'seed'),
  ('en', 'sviluppo-web', 'Web Development',
   E'Sometimes a brochure site is not enough.\nYou need a platform that does things: back-office tools, bookings, client areas, integrations with your stack.',
   '["Custom applications built to fit","APIs and third-party integrations","Client areas and admin panels","Performance of a modern SaaS"]'::jsonb,
   'code', 'matrix', 2, 'seed'),
  ('en', 'seo', 'SEO & Visibility',
   E'No tricks, no empty promises.\nI make sure the people searching for what you offer find you and understand right away why you are the right pick.',
   '["Full technical audit","Keyword and content strategy","Local SEO (Google Business)","Monthly monitoring"]'::jsonb,
   'magnifying-glass', 'matrix', 3, 'seed'),
  -- EN STANDALONE
  ('en', 'manutenzione-siti', 'Site Maintenance',
   E'Your site is online — but who is watching it?\nUpdates, backups, monitoring, urgent fixes.\nA clear monthly fee, no surprises.',
   '["Backup and restore","CMS, plugin and dependency updates","Uptime and performance monitoring","Urgent fixes within 24h"]'::jsonb,
   'wrench', 'standalone', 10, 'seed'),
  ('en', 'assistenza-wordpress', 'WordPress Support',
   E'WordPress is powerful — and fragile.\nI clean up compromised sites, sort out conflicting plugins, and block attacks before they do damage.',
   '["Security hardening (firewall, 2FA)","Malware cleanup and restore","Plugin conflict resolution","Performance tuning (cache, queries)"]'::jsonb,
   'shield-check', 'standalone', 11, 'seed'),
  ('en', 'wordpress-migrazione', 'WordPress Migration & Hosting',
   E'Slow site or a host that lets you down?\nI move WordPress with no downtime, configure performant hosting, and cut load times.',
   '["Zero-downtime migration","WP-tuned hosting setup","CDN and cache configured","DNS migration and SSL certificates"]'::jsonb,
   'cloud-arrow-up', 'standalone', 12, 'seed'),
  ('en', 'performance-cwv', 'Performance & Core Web Vitals',
   E'The site looks good but loads in 8 seconds.\nOn mobile it pushes customers away, on Google it slips down the page.\nI fix LCP, CLS, INP until they pass the check.',
   '["Lighthouse + WebPageTest audit","LCP < 2.5s, CLS < 0.1, INP < 200ms","Image optimization + lazy loading","Measurable before/after report"]'::jsonb,
   'gauge', 'standalone', 13, 'seed'),
  ('en', 'accessibility-wcag', 'WCAG Accessibility',
   E'From 28 June 2025 the European Accessibility Act is in force.\nIf you sell online, the site must be accessible or you pay fines.\nWCAG 2.1 AA audit + remediation.',
   '["Screen reader audit (NVDA + VoiceOver)","Contrast + keyboard navigation check","ARIA fixes + semantic HTML","Publishable accessibility statement"]'::jsonb,
   'wheelchair', 'standalone', 14, 'seed'),
  ('en', 'analytics-setup', 'Analytics & Tag Manager',
   E'You have a site but no idea who buys, who bounces, where they come from.\nProper GA4 + GTM setup, conversion events tracked, dashboard readable in 5 minutes.',
   '["GA4 property + GTM container","E-commerce / lead form events","Consent Mode v2 (GDPR-compliant)","Custom Looker Studio dashboard"]'::jsonb,
   'chart-line-up', 'standalone', 15, 'seed')
ON CONFLICT (slug, locale) DO NOTHING;
