-- 127: Seed default workflow templates into the `workflows` table.
--
-- Mirrors apps/api/scripts/seed-default-workflows.ts so that production DBs
-- (where the script can't easily run because tsx is a devDependency) get the
-- same 9 starter templates the first time this migration is applied.
--
-- All workflows are inserted in 'paused' state — admin must toggle the switch
-- in /workflows to activate them. Inserts are guarded with WHERE NOT EXISTS
-- on the exact name so re-running the migration runner is a no-op (the ledger
-- already prevents re-application, this is belt-and-braces in case the
-- migration is replayed manually).
--
-- Placeholders inside `nodes` match the actual payloads emitted by fireEvent()
-- in contacts.ts / quote-public.ts / calendar/public.ts / domain-alerts.ts.
-- If you change the seed in scripts/seed-default-workflows.ts, add a NEW
-- migration (don't edit this one) — migrations are append-only.

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Alert dominio in scadenza', 'Notifica Telegram quando un dominio gestito sta per scadere.', 'paused', 'event', '{"event_type":"dominio_scadenza"}'::jsonb, E'[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"dominio_scadenza"}},{"id":"tg","type":"tool_send_telegram","position":{"x":420,"y":200},"data":{"message":"⏰ <b>Dominio in scadenza</b>\\n{{domain_name}} scade tra {{days_remaining}} giorni.\\nCliente: {{customer_name}}"}}]'::jsonb, '[{"id":"e-trg-tg","source":"trg","target":"tg"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Alert dominio in scadenza');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Conferma booking al cliente', 'Quando un cliente prenota una call: gli invia subito un''email di conferma con l''orario.', 'paused', 'event', '{"event_type":"booking_creato"}'::jsonb, '[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"booking_creato"}},{"id":"mail","type":"tool_send_email","position":{"x":420,"y":200},"data":{"to":"{{attendee_email}}","subject":"Prenotazione confermata — {{event_type_slug}}","body":"<p>Ciao {{attendee_name}},</p><p>La tua prenotazione per <b>{{event_type_slug}}</b> è confermata per il <b>{{start_time}}</b>.</p><p>A presto,<br/>Federico</p>"}}]'::jsonb, '[{"id":"e-trg-mail","source":"trg","target":"mail"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Conferma booking al cliente');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Daily digest', 'Ogni mattina alle 09:00 riassume i KPI del giorno precedente (lead, bookings, pagamenti) e li invia su Telegram.', 'paused', 'cron', '{"interval_hours":24,"time":"09:00"}'::jsonb, E'[{"id":"trg","type":"trigger_cron","position":{"x":100,"y":200},"data":{"interval_hours":24,"time":"09:00"}},{"id":"q","type":"tool_db_query","position":{"x":420,"y":200},"data":{"query":"SELECT (SELECT COUNT(*) FROM leads WHERE created_at > NOW() - INTERVAL ''24 hours'') AS leads_24h, (SELECT COUNT(*) FROM calendar_bookings WHERE created_at > NOW() - INTERVAL ''24 hours'') AS bookings_24h, (SELECT COUNT(*) FROM payments WHERE created_at > NOW() - INTERVAL ''24 hours'' AND status = ''completed'') AS payments_24h, (SELECT COALESCE(SUM(amount), 0) FROM payments WHERE created_at > NOW() - INTERVAL ''24 hours'' AND status = ''completed'') AS revenue_24h","params":[]}},{"id":"sum","type":"llm_summarize","position":{"x":740,"y":200},"data":{"max_length":80,"style":"telegrafico"}},{"id":"tg","type":"tool_send_telegram","position":{"x":1060,"y":200},"data":{"message":"📊 <b>Digest giornaliero</b>\\n{{summary}}"}}]'::jsonb, '[{"id":"e-trg-q","source":"trg","target":"q"},{"id":"e-q-sum","source":"q","target":"sum"},{"id":"e-sum-tg","source":"sum","target":"tg"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Daily digest');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Dominio scadenza → WhatsApp cliente', 'Quando un dominio gestito sta per scadere, avvisa il cliente proprietario via WhatsApp. Richiede WhatsApp (GOWA) configurato.', 'paused', 'event', '{"event_type":"dominio_scadenza"}'::jsonb, '[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"dominio_scadenza"}},{"id":"wa","type":"tool_send_whatsapp","position":{"x":420,"y":200},"data":{"phone":"{{customer_phone}}","category":"operational","message":"Ciao {{customer_name}}, ti scrivo da calicchia.design: il dominio {{domain_name}} scade tra {{days_remaining}} giorni. Vuoi rinnovarlo?"}}]'::jsonb, '[{"id":"e-trg-wa","source":"trg","target":"wa"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Dominio scadenza → WhatsApp cliente');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Lead urgente con AI', 'Classifica il lead in arrivo per urgenza (alta/media/bassa) e manda una notifica Telegram solo se ''alta''. Gli altri vanno solo a log.', 'paused', 'event', '{"event_type":"nuovo_lead"}'::jsonb, E'[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"nuovo_lead"}},{"id":"cls","type":"llm_classify","position":{"x":420,"y":200},"data":{"categories":["alta","media","bassa"],"prompt":"Classifica l''urgenza del lead (parole come ''urgente'', ''subito'', ''oggi'' → alta; budget/scadenza chiari → media; richieste generiche → bassa)."}},{"id":"cond","type":"logic_condition","position":{"x":740,"y":200},"data":{"condition":"input.category == ''alta''","true_label":"Urgente","false_label":"Non urgente"}},{"id":"tg","type":"tool_send_telegram","position":{"x":1060,"y":20},"data":{"message":"🚨 <b>Lead URGENTE</b>\\nNome: {{name}}\\nEmail: {{email}}\\nTel: {{phone}}"}},{"id":"log","type":"output_log","position":{"x":1060,"y":380},"data":{"message":"Lead non urgente: {{name}} ({{category}})"}}]'::jsonb, '[{"id":"e-trg-cls","source":"trg","target":"cls"},{"id":"e-cls-cond","source":"cls","target":"cond"},{"id":"e-cond-tg","source":"cond","target":"tg","sourceHandle":"true"},{"id":"e-cond-log","source":"cond","target":"log","sourceHandle":"false"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Lead urgente con AI');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Notifica nuovo booking', 'Avvisa su Telegram quando un cliente prenota una call o un appuntamento.', 'paused', 'event', '{"event_type":"booking_creato"}'::jsonb, E'[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"booking_creato"}},{"id":"tg","type":"tool_send_telegram","position":{"x":420,"y":200},"data":{"message":"📅 <b>Nuova prenotazione</b>\\n{{attendee_name}} — {{event_type_slug}}\\n{{start_time}}"}}]'::jsonb, '[{"id":"e-trg-tg","source":"trg","target":"tg"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Notifica nuovo booking');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Notifica nuovo lead', 'Avvisa su Telegram appena arriva un nuovo lead dal sito.', 'paused', 'event', '{"event_type":"nuovo_lead"}'::jsonb, E'[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"nuovo_lead"}},{"id":"tg","type":"tool_send_telegram","position":{"x":420,"y":200},"data":{"message":"🆕 <b>Nuovo lead</b>\\nNome: {{name}}\\nEmail: {{email}}\\nTel: {{phone}}\\nAzienda: {{company}}"}}]'::jsonb, '[{"id":"e-trg-tg","source":"trg","target":"tg"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Notifica nuovo lead');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Preventivo firmato → crea progetto', 'Quando un preventivo viene firmato: notifica Telegram e crea automaticamente il progetto con task AI.', 'paused', 'event', '{"event_type":"preventivo_firmato"}'::jsonb, E'[{"id":"trg","type":"trigger_event","position":{"x":100,"y":200},"data":{"event_type":"preventivo_firmato"}},{"id":"tg","type":"tool_send_telegram","position":{"x":420,"y":200},"data":{"message":"✅ <b>Preventivo firmato!</b>\\nCliente: {{signer_name}}\\nTitolo: {{title}}\\nImporto: €{{total}}"}},{"id":"mkproj","type":"tool_create_project","position":{"x":740,"y":200},"data":{"quote_id":"{{quote_id}}"}}]'::jsonb, '[{"id":"e-trg-tg","source":"trg","target":"tg"},{"id":"e-tg-mkproj","source":"tg","target":"mkproj"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Preventivo firmato → crea progetto');

INSERT INTO workflows (name, description, status, trigger_type, trigger_config, nodes, edges, variables)
SELECT '[default] Weekly digest', 'Ogni lunedì alle 09:00: riassume i KPI della settimana precedente (lead, bookings, pagamenti, revenue) via AI e li invia su Telegram.', 'paused', 'cron', '{"interval_hours":168,"time":"09:00"}'::jsonb, E'[{"id":"trg","type":"trigger_cron","position":{"x":100,"y":200},"data":{"interval_hours":168,"time":"09:00"}},{"id":"q","type":"tool_db_query","position":{"x":420,"y":200},"data":{"query":"SELECT (SELECT COUNT(*) FROM leads WHERE created_at > NOW() - INTERVAL ''7 days'') AS leads_7d, (SELECT COUNT(*) FROM calendar_bookings WHERE created_at > NOW() - INTERVAL ''7 days'') AS bookings_7d, (SELECT COUNT(*) FROM payments WHERE created_at > NOW() - INTERVAL ''7 days'' AND status = ''completed'') AS payments_7d, (SELECT COALESCE(SUM(amount), 0) FROM payments WHERE created_at > NOW() - INTERVAL ''7 days'' AND status = ''completed'') AS revenue_7d, (SELECT COUNT(*) FROM client_projects WHERE created_at > NOW() - INTERVAL ''7 days'') AS new_projects_7d","params":[]}},{"id":"sum","type":"llm_summarize","position":{"x":740,"y":200},"data":{"max_length":100,"style":"telegrafico"}},{"id":"tg","type":"tool_send_telegram","position":{"x":1060,"y":200},"data":{"message":"📈 <b>Weekly digest</b>\\n{{summary}}"}}]'::jsonb, '[{"id":"e-trg-q","source":"trg","target":"q"},{"id":"e-q-sum","source":"q","target":"sum"},{"id":"e-sum-tg","source":"sum","target":"tg"}]'::jsonb, '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM workflows WHERE name = '[default] Weekly digest');
